### ISSUE TITLE
Transfer all relevant issues to this repo

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#1]
**Goal:**
Have a clean state to work on in this public repo

**Context:**
In our process to work fully in public all relevant issues from the old internal repo need to be transferred. 

**Tasks:**
- [x] Transfer relevant `backlog` issues
- [x] Transfer relevant `To Do` issues -> doublecheck with @valiafetisov 
- [x] Transfer relevant `In progress` issues -> doublecheck with @valiafetisov / @BracketJohn 
- [ ] Transfer `Done` issues to keep relevant history / documentation

**Comment by LukSteib** [comment]
>  Transfer Done issues to keep relevant history / documentation

We decided not to transfer the already `done` issues to this repo as well. Hence this issue can be closed.
