### ISSUE TITLE
Implement a /features page

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#101]
**Goal:**
Provide a page to users that describes all of the features of our tool(s) 

**Context:**
We agreed to create a feature page that lists all of the functionality of our tools in bullet lists. This should help a user that wants to inspect further what actions are faciliated via our UI (and which are not).
For that we have to create a dedicated subpage `/features` that allows to provide this overview

**Tasks:**
- [x] use existing landingblock with background image and heading `Feature overview` 
- [x] Use existing header without only with dark mode switch
   - [x] Maker Logo with text `Collateral auctions` that links to `/collateral` page (similar to /dashboard header)  
- [x] path: auctions.makerdao.network/features
- [x] Include the text (provided in gdoc below) and structure it nicely (correct spacing etc.)
   - [x] **note:** the comment on T&C at the end of the document is out of scope. Everything else should be included. 
- [x] Ensure responsivenes
- [x] Include a link to our footer called `Features` that links to this newly created page 

**Assets:**
Gdoc: https://docs.google.com/document/d/13pEGxUQlJ45kkCNCFATZRs8zw8mFJINmHx2MqAmqTGo/edit#
