### ISSUE TITLE
Investigate flashbot RPC endpoint to mitigate front-running issue

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#11]
**Goal:**
Investigate applicability of flashbot RPC to our UI

**Context:**
Message from PE:
```
hey guys, I missed the presentation today but will catch it on the recording.
I did have a suggestion
when one joins arbitrum or optimism, there is a JS widget that adds that RPC endpoint to metamask.
you should absolutely do this, but for the flashbots RPC endpoint.
https://rpc.flashbots.net/
this will help solve the front-running problem.
```

**Tasks:**
- [ ] understand the mechanics behind flashbot RPC
- [ ] determine whether this might be useful for our UI
- [ ] propose next steps
