### ISSUE TITLE
Implement link to T&C pdf

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#111]
**Goal:**
When clicking on the `Terms and Conditions` link in the T&C popup the user is provided with a PDF in a new tab

**Context:**
On our current T&C popup we link to the `/terms` subpage. We want to change this behavior in the future and open a pdf in a new browser tab when clicking the respective links on the popup. 

**Tasks:**
- [x] Change wording in current popup from "Terms of Service" to "Terms and Conditions"
- [x] Replace existing link to `/terms` subpage with link to pdf (see pdf in assets below)
   - [x] ensure that PDF is provided in new browser tab once user clicks the link 

**Assets:**
[Unified-Auction-UI_Terms&Conditions.pdf](https://github.com/sidestream-tech/unified-auctions-ui/files/8111306/Unified-Auction-UI_Terms.Conditions.pdf)
