### ISSUE TITLE
Release 0.9.0

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#114]
### Planned Release Scope
-   Product stream
    - [ ] Get makerdao.com domain https://github.com/sidestream-tech/auction-ui/issues/287
    - [ ] Coordinate the interlinking of unified auctions ui   
-   Blockchain stream
    - [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/45
    - [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/33
    - [ ] #108
    - [x] push chaoslabs testing setup https://github.com/sidestream-tech/unified-auctions-ui/issues/83
    - [ ] Start working on the logic issues from https://github.com/sidestream-tech/unified-auctions-ui/issues/117
-   Devops stream
    - [ ] https://github.com/sidestream-tech/unified-auctions-ui/issues/66
-   UI/fixes stream
    - [x] Start working on the UI-related issues from https://github.com/sidestream-tech/unified-auctions-ui/issues/117
-   Bonus
    - [ ] introduce tests for critical functionality:  fetching, authorisation and execution
    - [ ] Interlink all other UIs with our UI (open PRs to other websites / source codes) - https://github.com/sidestream-tech/unified-auctions-ui/issues/93
    - [ ] add uniswap v3 support
---

Predecessor: #99

- [x] double-check with @valiafetisov and @LukSteib whether release makes sense
- [x] test staging environment
- [x] release images via UI https://github.com/sidestream-tech/auction-ui/releases/new 
- [x] Deploy staging to production _goal: 11.02. , 12:00_ 
   - [x] Test prod environment
- [x] Share release notes in makerForum _goal: 11.02

**Comment by valiafetisov** [comment]
- I would also add https://github.com/sidestream-tech/unified-auctions-ui/issues/108
- I would rewrite https://github.com/sidestream-tech/unified-auctions-ui/issues/33 to the changed goal
- I would start splitting `Bid with DAI` rn
- We need to at least reply to ChaosLabs

**Comment by LukSteib** [comment]
Release images created:
https://github.com/sidestream-tech/unified-auctions-ui/releases/tag/v0.9.0

Check on https://production.auction-ui.k8s.sidestream.tech/ successful ✔️ 

@BracketJohn let's proceed. 
(Note: Unfortunately no progress on the domain change - so same procedure as last sprints)

**Comment by BracketJohn** [comment]
Deployed following: https://github.com/sidestream-tech/unified-auctions-ui/issues/23#issuecomment-1013030870

Deployment done, please checkout the application (:

**Comment by LukSteib** [comment]
> Deployment done, please checkout the application (:

Looking good. 

I call the Release done ✅
