### ISSUE TITLE
Implement `AccessDaiBlock` component 

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#115]
### Goal

Implemented `AccessDaiBlock` component in the storybook

### Context

Similar to the `AuthorisationBlock` we would need to have component titles as `Allow access to DAI`, with one button (which is active or inactive depending on the `isDaiAccessGranted` and `disabled`)

### Assets

Component disabled:
![MakerDAO@2x (1)](https://user-images.githubusercontent.com/3393626/155959472-a148a64c-51f2-40b3-b227-1e58742ac61e.png)

Component with `isDaiAccessGranted` true:
![MakerDAO@2x (5)](https://user-images.githubusercontent.com/3393626/155961968-b7750119-007d-47da-b595-46ab5cfe217f.png)

The context:
![MakerDAO - Bid with DAI (total)@2x](https://user-images.githubusercontent.com/3393626/155960690-ea3409c8-1884-4e11-8749-2a269e060b88.png)

### Tasks
- [x] create new `AccessDaiBlock` inside `transaction` folder
- [x] please check that `isExplanationsShown` is taken into the account
- [x] please check that `isLoading` is taken into the account
- [x] create a story

**Comment by valiafetisov** [comment]
@LukSteib please prepare the correct text for the component

**Comment by LukSteib** [comment]
Text: 

To bid on an auction with Dai, first funds need to be deposited to the VAT.(Explainer Component: The[ VAT contract](https://docs.makerdao.com/smart-contract-modules/core-module/vat-detailed-documentation#2-contract-details) is the core vault engine of the Maker Protocol and manages the central accounting invariants of DAI. Depositing and interacting with the VAT is necessary in order to participate in auctions.) The following transaction authorizes the wallet address to deposit into the VAT. It is a prerequisite to participate in the auction.
