### ISSUE TITLE
Implement `DepositBlock` component

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#116]
### Goal

Implemented `DepositBlock` component in the storybook

### Context

Similar to other transaction blocks, we will need to have component titled as `Deposit`, with _one button for now_: `Deposit minimum amount`. The button should be:
- disabled when `disabled` prop is provided
- read as `Deposit minimum amount` by default
- read as `Enough DAI is available` if `Minimum to deposit` is 0 (please account for BigNumber zeros)

The component should receive:
- `disabled`, `boolean`
- `walletDAI`, `BigNumber` – Amount available in the wallet
- `walletVatDAI`, `BigNumber` – Currently deposited amount
- `transactionAmountDAI`, `BigNumber` – Transaction amount that the user wants to bid, not directly shown, instead `Minimum to deposit` is calculated based on that one and `walletVatDAI` (`transactionTotalDAI – walletVatDAI`, but not less than `0`)

### Assets

(disabled, no walletDAI and walletVatDAI):
![MakerDAO@2x (10)](https://user-images.githubusercontent.com/3393626/155966871-f1ed8087-fbba-4b18-b194-00ff5e08aa56.png)

(disabled, walletDAI and walletVatDAI provided):
![MakerDAO@2x (9)](https://user-images.githubusercontent.com/3393626/155966678-241af06a-bef7-4a78-b0bd-f2726057d545.png)

(not disabled, walletDAI and walletVatDAI provided):
![MakerDAO@2x (6)](https://user-images.githubusercontent.com/3393626/155964667-049d3318-b0c9-4419-a63d-8fb2f5b296cc.png)

(not disabled, walletDAI and walletVatDAI provided, but min amount is 0):
![MakerDAO@2x (8)](https://user-images.githubusercontent.com/3393626/155965246-456c8ce0-ef1a-4715-97d0-c08dfebac136.png)

### Tasks
- [x] create new `DepositBlock` inside `transaction` folder
- [x] please check that `isExplanationsShown` is taken into the account
- [x] please check that `isLoading` is taken into the account
- [ ] create a story for all possible states

**Comment by valiafetisov** [comment]
@LukSteib please check/provide the actual text(s) for the block/buttons

**Comment by LukSteib** [comment]
> @LukSteib please check/provide the actual text(s) for the block/buttons

@valiafetisov back question to required auth steps. My current understanding:
* There is one auth step required that allows to deposit dai to Vat (covered by #115)
* There is one auth step required that enables Dai bidding (will be covered in dedicated auth block - see [1])
* There is one auth step required that enables bidding on the specific ilk type (will be covered by dedicated auth block - see [2])

-> Is this understanding correct? If so, the block at hand here would not require an auth tx.



[1]
<img width="509" alt="image" src="https://user-images.githubusercontent.com/36229155/155973410-04fab9ee-fd59-46d8-9dcf-93ff742c2b60.png">

[2]
<img width="511" alt="image" src="https://user-images.githubusercontent.com/36229155/155973444-d5edda37-2713-45f9-a706-af873cd5d53d.png">

**Comment by LukSteib** [comment]
Text:
```
To participate in the auction you need to deposit enough Dai to the VAT. Below is an overview on the current Dai balance in your wallet that can be used to make an deposit. The amount already deposited. And the minimum amount to deposit in order to participate in the auction based on the bid you want to make. 
You can either directly deposit the minimum amount to bid or manage your Dai balance in the VAT.
```
Suggestion for buttons:
* `Deposit minimum amount` / `Enough Dai available`✔️
* Change `Manage VAT` to `Manage Dai in Vat`

**Comment by valiafetisov** [comment]
> `Manage DAI in VAT`

Ok! But this button is _not_ implemented in this issue, see below `with one button for now`

> You can either directly deposit the minimum amount to bid or manage your Dai balance in the VAT.

Let's also remove/change this sentence, for the same reasons

**Comment by LukSteib** [comment]
> Ok! But this button is not implemented in this issue, see below with one button for now

I see - agree

> Let's also remove/change this sentence, for the same reasons

edited
