### ISSUE TITLE
Bidding with DAI feature

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#117]
### Context

This issue a is tracking issue to implement `Bid with DAI` feature

### Assets

- https://github.com/sidestream-tech/unified-auctions-ui/issues/96#issuecomment-1054227644

### Subissues

- [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/115
- [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/116
- [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/118
- [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/124
- [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/126
- [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/133
- [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/120
- [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/123
- [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/121
- [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/125
- [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/134
- [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/135
- [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/136
- [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/145
