### ISSUE TITLE
Implement `BidBlock` component

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#118]
### Goal

Implemented `BidBlock` component in the storybook

### Context

Similar to other transaction blocks, we will need to have component `BidBlock` titled as `Bid`, with one button `Bid XXX.XX DAI for XXX.XX ${collateralSymbol}`.

### Assets

![MakerDAO@2x (11)](https://user-images.githubusercontent.com/3393626/155977444-8025d625-a001-4be6-8ed1-653f6e5860e4.png)

### Tasks
- [x] create new `BidBlock` inside `transaction` folder
- [x] please check that `isExplanationsShown` is taken into the account
- [x] please check that `isLoading` is taken into the account
- [x] please check that `disabled` is taken into the account
- [x] create a story for all possible states
