### ISSUE TITLE
Implement `BidTransactionTable` component

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#120]
### Goal

Implemented `BidTransactionTable` component in the storybook

### Context

Similar to the `SwapTransactionTable`, `BidTransactionTable` is a table showing key values of the auction. Besides showing the values the table offers interactive elements (marked with green color in the UI):
- an input to enter bid amount (defaults to total price _changing_  with every drop)
- a button to set bid amount to minimum
- a button to set bid amount to total price
- reset button (if the bid amount was changed) has the same functionality as `set bid amount to total price` above

Please note that additional complexity is in the details:
- the input should be focused on load
  - we allow use to input add any amount of floating point numbers (and always display them without formatting)
  - we disallow user to enter other symbols
  - when the value is `total`, we format it with animated number (ie with 2 decimals)
- because of the above, bidding value that is equal to total is stored as something else than a number
   proposal: `export type transactionAmountDAI = BigNumber | 'total'`
- editing is validated and the error message is shown in a non-closable tooltip with the red bg
  - we validate that the value is not less than new `auction.minimumBid` value
  - we validate that the value is not more than `auction.totalPrice - auction.minimumBid`
- total value is changing due to the dropping price, but if the user has edited it, it always stays with the edited value (but the validation is reactive, ie a computed prop)

Notes:
- it may be beneficial to move complex input logic to a separate component, but may also not (: 
- it may be beneficial to write validation logic as part of the `core`, since we would need it in other places as well

### Assets
![MakerDAO@2x (15)](https://user-images.githubusercontent.com/3393626/155981637-7bf47927-56b2-4140-aaa3-36c84a8462f0.png)

### Tasks
- [x] create new `BidTransactionTable` inside `transaction` folder
- [x] please handle `isFinished` and `isActive` states properly (disabling/cleaning up input)
- [x] create a story for all possible states
  - [x] implement a story that periodically drops price

**Comment by LukSteib** [comment]
> a button to set bid amount to minimum
a button to set bid amount to total price

These are not buttons a user can interact with but rather more rows with additional indicators or am I missing something?

**Comment by LukSteib** [comment]
> The values of those new raws are clickable, that's why they are green

I see! Didn't get it from the color coding in the Mock alone. 
In general I like this idea to have the ability to select `Max` and `Min` bid via button click. And not having the `Reset to Total` button as it has the same functionality. 

So like the following:
<img width="759" alt="image" src="https://user-images.githubusercontent.com/36229155/156208798-e718d3ce-8b0e-45b9-860f-db97924b483a.png">



Upside: 
* More intuitive for the user
* Known `Max` `Min` behavior from other Defi tools 

Downside: 
* break with structured table
* less intuitiv "reset" to new total price after price drop

@valiafetisov what's your opinion

**Comment by valiafetisov** [comment]
You can actually see in the whimsical that [I've considered quite a few options](https://user-images.githubusercontent.com/3393626/156213104-4d1249b1-b3ba-434e-a884-2282dec00e90.png) and I think this one is the most clear in terms of UI. I think `max` is not the same as dynamic `total price` and I don't see a need to "stick" those values to the input. I would argue that it's ok to leave it as is, or, if you find it confusing, just further highlight the possibility to click on them: via underline, button or text (ie `apply`):

<img width="562" alt="Screenshot 2022-03-01 at 18 00 00" src="https://user-images.githubusercontent.com/3393626/156213954-84f373bf-9c97-44f1-a425-ea494e740d29.png">

**Comment by LukSteib** [comment]
> further highlight the possibility to click on them: via underline, button or text (ie Set)

I like that one. Makes it more explicit for the user.

**Comment by valiafetisov** [comment]
Then, I would propose something like that in the end (where the whole row is clickable):
<img width="509" alt="Screenshot 2022-03-01 at 18 17 55" src="https://user-images.githubusercontent.com/3393626/156216765-89b7e21f-8f05-468e-9fdc-1c3816e0998a.png">
