### ISSUE TITLE
Implement `BidTransaction` component

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#121]
### Goal

Implemented `BidTransaction` component via the `AuctionFakeData` container

### Context

Similar to the `SwapTransaction`, we need to implement `BidTransaction` first using stub data. All the underlying component should be ready at this time: `AccessDaiBlock`, `DepositBlock`, `BidBlock`, `BidTransactionTable`. 

Note that `Bid with DAI` button should stay disabled in this issue as it will be implemented later.

### Assets

- https://github.com/sidestream-tech/unified-auctions-ui/issues/96#issuecomment-1054227644

### Tasks
- [ ] create new `BidTransaction` inside `transaction` folder
- [ ] please handle `isFinished` and `isActive` states properly (reuse error handling from another transaction component)
- [ ] the flow should be testable in `AuctionFakeData` or the storybook
