### ISSUE TITLE
Implement `setAllowanceAmount` logic

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#123]
### Goal

Implemented `setAllowanceAmount` logic (store only, no UI)

### Context

Similar to the `authorizeWallet` and `fetchWalletAuthorizationStatus` this PR should extend `authorizations` store to include `setAllowanceAmount` and `fetchAllowanceAmount`. The actual, blockchain-related logic should be implemented inside `core/src/authorizations.ts`. Note that we also want to have some kind of de-auth possibility.

The actual transactions that should be executed can be found in the `liquidations.makerdao.com` source code:
https://github.com/makerdao/liquidations-portal/blob/0c6af9c5dcacbf60aeb39e9c3a7617180d2ae304/stores/approvals.ts#L89

Note: the UI for this functionality will be implemented in #115.

### Tasks
- [x] extend `authorizations` core
- [x] extend `authorizations` store with 3 new actions, new state
- [ ] extend `refetch` and `reset` actions to support fetching
- [x] in the PR description, provide example store commands to be called in the browser console for testing

**Comment by benediktkaiser** [comment]
I had a look into this issue today and yesterday. As far as I can see the following steps must be executed in order to authorise Dai Access.

- Get `MCD_JOIN_DAI` contract
- Retrieve address from the retrieved contract
- Call `maker.getToken` and pass the address as a prop.

As we are no longer using `DAIJs`, I was wondering what exactly `maker.getToken` does. Does it call a contract or is it some other kind of function? 
Once I understand what it does, I might be able to mimimic it with `ether.js`. @valiafetisov, if you have any quick tips, I would love to hear them!

**Comment by valiafetisov** [comment]
> I was wondering what exactly maker.getToken does

Judging by the name it's a dai token contract. You can get the same contract by calling `getContract(network, `DAI`)`. But you can, of course, just search for the `getToken` inside dai.js source code.

**Comment by valiafetisov** [comment]
`authorizeAccessToDAI(network: string, amount?: BigNumber)`
- get `MCD_JOIN_DAI` contract address
- if no amount specified, set maximum possible amount, as in [`approveUnlimited`](https://github.com/makerdao/dai.js/blob/3f57eac9798a53a9bd96197514fe6d6fde5672de/packages/dai/src/eth/tokens/Erc20Token.ts#L68-L82)
- call `approve` on the `MCD_DAI` passing `MCD_JOIN_DAI` address and the amount
