### ISSUE TITLE
Implement wallet-related logic

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#124]
### Goal

Vuex store actions to fetch wallet data and `deposit`/`withdrew`

### Context

When the wallet is connected/disconnected/wallet address has changed, we want to update `wallet` store with new values:
- `walletDAI` – amount of DAI (`MCD_DAI`) tokens in the connected wallet
- `walletETH` – amount of ETH the connected wallet
- `walletVatDAI` – amount of DAI in the VAT related to that wallet

Therefore, we need to extend vuex store to add new variables and add two `core` functions to fetch that data. For inspiration, please refer to the [liquidations portal source code](https://github.com/makerdao/liquidations-portal).

We also need to add functions to `deposit` and `withdrew` DAI to/from VAT. For inspiration, please refer to https://github.com/makerdao/dai.js/blob/3511e9f4db70285d3a85776d22933dd092ba87e0/packages/dai-plugin-liquidations/src/LiquidationService.ts#L343-L354

### Tasks
- [x] investigate how it's done, document here with links
- [ ] implement required functions inside the `core`
- [ ] extend `wallet` store with the variables as well as new actions
- [ ] fetch this information when wallet is connected/changed
- [ ] add `deposit` and `withdrew` transactions to the `core`
- [ ] add `deposit` and `withdrew` actions
- [ ] in the PR description, provide example store commands to be called in the browser console for testing

**Comment by valiafetisov** [comment]
So in total, we need to have some new `core` functions:
- `fetchWalletBalanceETH(network, walletAddress)`
   - fetch `await provider.getBalance(walletAddress)`
   - convert it to our big number with correct number of decimals
- `fetchWalletBalanceDAI(network, walletAddress)`
   - get `MCD_DAI` contract interface `await getContract(network, 'DAI')`
   - fetch `await contract.balanceOf(walletAddress)`
   - convert it to our big number with correct number of decimals
- `depositToVAT(network, amount)`
   - get `MCD_JOIN_DAI` contract interface
   - call `await contract.join(walletAddress, integerAmount)`
- `withdrewFromVAT(network, amount)`
   - get `MCD_JOIN_DAI` contract interface
   - call `await contract.exit(walletAddress, integerAmount)`
