### ISSUE TITLE
Implement `WalletPopup` component

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#135]
### Goal

Implemented `WalletPopup` component in the storybook

### Context

For the [`Bidding with DAI` feature](https://github.com/sidestream-tech/unified-auctions-ui/issues/117), this issue is to assemble wallet popup from text and already implemented components:
- https://github.com/sidestream-tech/unified-auctions-ui/issues/133
- https://github.com/sidestream-tech/unified-auctions-ui/issues/134

Please note:
- the component should provide wallet information under a single prop `wallet` with all info (address, amounts, update date)
- the component should re-emit events from the sub components
  - an event to refetch wallet info
  - an event to deposit
  - an event to withdraw
- if the wallet is not connected, we should show `WalletBlock` instead of the table

### Assets
- Correct text for the component: https://docs.google.com/document/d/1BnHalnU9MWxUKvI_u39X0gDvc3YObQnHCsnwaK4c_7g/edit#heading=h.vzx3e4cwp5zr
- Latest mock: https://github.com/sidestream-tech/unified-auctions-ui/issues/126

### Tasks
- [ ] create new `WalletPopup` inside `wallet` folder
- [ ] create stories for all edge cases
- [ ] please check that `isConnecting` prop is taken into the account
- [ ] please check that `isLoading` prop is taken into the account
- [ ] please check that `isExplanationsShown` prop is taken into the account
