### ISSUE TITLE
Support `UniswapV3Callee` callee

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#137]
### Goal
Swap regular ERC20 collaterals via new `UniswapV3Callee` callee instead of the old `UniswapV2CalleeDai`

### Context
Since Uniswap V2 is loosing popularity and doesn't provide good source of the liquidity anymore, we should add support for the `UniswapV3Callee` callee. Reference implementation can be found in the [auction-demo-keeper repo](https://github.com/makerdao/auction-demo-keeper/tree/main/src) and we also already use Uniswap V3 inside `WstETHCurveUniv3Callee` (which we should split into separate function instead): 
https://github.com/sidestream-tech/unified-auctions-ui/blob/5494c084e8f42cbdb962e39651b136c3dda196a6/core/src/calleeFunctions/WstETHCurveUniv3Callee.ts#L51-L63

Note: according to the auction-demo-keeper config, [one collateral is still using the old UniV2 callee](https://github.com/makerdao/auction-demo-keeper/blob/6db7431aa07b657d4e9cf2aae35f9c1302595a79/config/mainnet.json#L183-L195), therefore we should:
- investigate the reasoning
  - is it about the liquidity size?
  - do we need to dynamically/manually compare prices between v2 vs v3 exchanges?
- do not drop support for the old v2 callee

### Tasks
- [ ] Implement callee functions, according to the [Collateral onboarding](https://github.com/sidestream-tech/unified-auctions-ui/tree/main/core#collateral-onboarding) guide
- [ ] Update `WstETHCurveUniv3Callee` to use new Univ3 helpers
- [ ] Investigate the reasoning to keep both
  - [ ] Potentially change type of the `COLLATERALS[collateralType].exchange.callee` from `string` to `string[]`

**Comment by valiafetisov** [comment]
https://github.com/makerdao/exchange-callees/blob/49f9b5569d6f05f84924119757afef33247ec243/addresses.json

**Comment by Tejas-Choudekar** [comment]
I have started implementing the getcalleedata function and we already have the below parameters ready:
address to,            // address to send remaining DAI to
address gemJoin,       // gemJoin adapter address
uint256 minProfit,     // minimum profit in DAI to make [wad]

Need some help understanding the below fields for the getcalleedata function:

1. bytes memory path,     // packed encoding of (address, fee, address [, fee, address…])
We have used memory path as an array of addresses in V2 but here the implementation looks different, do we have something of this sorts already implemented that I can refer? If not then how shall I proceed this?

2. address charterManager // pass address(0) if no manager
Do we have a charterManager address in our application? If not then what should be the value of address(0)?

**Comment by valiafetisov** [comment]
Hey @Tejas-Choudekar, first of all, please try to use markdown code blocks for the code in your next comments to improve its readability 🙂 

> We have used memory path as an array of addresses in V2 but here the implementation looks different, do we have something of this sorts already implemented that I can refer? If not then how shall I proceed this?

As you correctly stated it's just a token addresses that are separated with fee. For inspiration you can look into [auction-demo-keeper](https://github.com/makerdao/auction-demo-keeper/blob/c14d0d332542cdbc75e2c7a541d9ca9928f0be30/src/clipper.js#L127-L146) implementation.

> Do we have a charterManager address in our application? If not then what should be the value of address(0)?

We don't have `charterManager`, I guess you can try to pass `0x` string or look up the helper inside `ethers` library for addresses.

**Comment by benediktkaiser** [comment]
Hi @valiafetisov! We need some further clarification on how to approach this first part. 

> As you correctly stated it's just a token addresses that are separated with fee. For inspiration you can look into [auction-demo-keeper](https://github.com/makerdao/auction-demo-keeper/blob/c14d0d332542cdbc75e2c7a541d9ca9928f0be30/src/clipper.js#L127-L146) implementation.

We checked the code you linked above, however many variables don't line up with those found in our projects. 

```js
let values = [
     Config.vars.collateral[this._collateralName].uniV3Path[0].tokenA
];
```

Why kind of object is being referenced here? We neither have something called `Config` nor any object that has to do with collaterals that has the key `uniV3Path`. 

Could you maybe provide a short outline of how we can include this logic in our own code with some more hints?

Thanks!

**Comment by valiafetisov** [comment]
Those are token address of the routes. I actually already wrote encoder in other PR but can't guarantee it's correctly implemented, since that pr is not yet merged https://github.com/sidestream-tech/unified-auctions-ui/blob/4dc4c2c482640a069a5eda07c0d97928f88f3e8e/core/src/calleeFunctions/helpers/uniswapV3.ts#L12-L27
