### ISSUE TITLE
Update stories to TypeScript

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#14]
#### Goal
Update all existing stories (and their imports) to be rewritten in `.ts`

#### Context
As it turns out, if stories are not written in ts, we don't catch many potential errors related to types, typing problems are not even reported/catched when supplying wrong data. Therefore, we should prevent that by writing everything in typescript. After this issue, there should be no functional `js` files in our project.

#### Tasks
- [x] rewrite all stories in ts
- [x] rewrite all imported files in ts (e.g.: `generateFakeAuction.js`)
- [ ] find a linting rule that prevents us from creating new `.js` files (except in the frontend root folder, where we store configs)
