### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#141]
### Planned Release Scope
-   Product stream
    - [ ] Get makerdao.com domain https://github.com/sidestream-tech/auction-ui/issues/287
    - [ ] Check current priorities in community (`crvstETH` onboarding vs. `PAXG` onboarding vs. ??) 
-   Blockchain stream
    - [x] Bidding with Dai feature
       - [x] #123 
       - [x] #124
    - [x] #108
    - [ ] #94
    - [ ] push chaoslabs testing setup https://github.com/sidestream-tech/unified-auctions-ui/issues/83
-   Devops stream
    - [ ] https://github.com/sidestream-tech/unified-auctions-ui/issues/66
-   UI/fixes stream
    - [x] #121 
    - [x] #125 
    - [x] #134 
    - [x] #135 
    - [x] #136
-   Bonus
    - [ ] introduce tests for critical functionality:  fetching, authorisation and execution
    - [ ] #137 
    - [ ] Interlink all other UIs with our UI (open PRs to other websites / source codes) - https://github.com/sidestream-tech/unified-auctions-ui/issues/93
---

Predecessor: #114

- [ ] double-check with @valiafetisov and @LukSteib whether release makes sense
- [ ] test staging environment
- [ ] release images via UI https://github.com/sidestream-tech/auction-ui/releases/new 
- [ ] Deploy staging to production _goal: 25.03. , 12:00_ 
   - [ ] Test prod environment
- [ ] Share release notes in makerForum _goal: 25.03

**Comment by LukSteib** [comment]
Release images created:

https://github.com/sidestream-tech/unified-auctions-ui/releases/tag/v1.0.0

**Comment by BracketJohn** [comment]
@LukSteib deployment to https://unified-auctions.makerdao.com/ is done. Note that `production.` is now unavailable (forever!).

Now doing manual deploy step to auctions.makerdao.network.

**Comment by LukSteib** [comment]
Checked https://unified-auctions.makerdao.com/ -> looking good ✔️ 

Checked https://auctions.makerdao.network/ -> looking good ✔️ 

Call it a successful release v1.0.0

**Comment by BracketJohn** [comment]
We did need to make an in between release of v1.0.1, fyi, maybe this is important for you!
