### ISSUE TITLE
Update `Bid with DAI` flow

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#145]
### Goal

Updated `Bid with DAI` flow that takes into account new discoveries on how it actually works

### Context

After the implementation of https://github.com/sidestream-tech/unified-auctions-ui/issues/124, we've [figured out](https://github.com/sidestream-tech/unified-auctions-ui/pull/143#issuecomment-1067709984) that:
- Depositing to VAT requires only `allowance` auth step
- Withdrawing from VAT requires only `wallet` auth step

After the implementation of https://github.com/sidestream-tech/unified-auctions-ui/issues/123, we've [figured out](https://github.com/sidestream-tech/unified-auctions-ui/pull/144#issue-1169910469) that:
- Allowance is non-binary transaction: users can set the exact amount of DAI that can be deposited to VAT (or a very big number, which is count as "unlimited")

Therefore, we should update the mock to reflect those learnings in the UI.

### Tasks
- [x] update allowance auth block
  - [x] to take allowance amount into consideration
  - [x] to let user specify exact allowance
- [x] update depositing block if needed
- [x] update wallet popup with new auth step
- [x] publish and discuss new mock
- [x] update related issues or the UI directly

**Comment by valiafetisov** [comment]
Due to the complexity of the allowance logic should not be executed depending on the amount of bidding I had to rearrange blocks around. Deposit/withdrawal flows also more than anticipated, requiring their own auth steps depending on the action.

Based on all the above and to avoid creating more confusion I came up with a new UI base element: a panel. Panels have a clear "status" title indicating if they need user attention or not and also expand / collapse itself based on the same logic. They can be reused between bid and swap transactions and the wallet popup. They also works well with our "expert mode". Basically, it's a tiny wrapper over the `Blocks` we already have, which makes better use of the title and the space.

![MakerDAO@2x (41)](https://user-images.githubusercontent.com/3393626/158814354-d6b17695-8fb9-4f5d-8043-148e1da7da19.png)

**Comment by benediktkaiser** [comment]
I really like this new panel approach. I find it makes it a lot easier to quickly introduce these new steps and it is very clear for the users to follow. 

I also like that we would use it in our current Swap Transaction system, as it would ensure that our entire UI is very consistant. 

I wanted to ask what our guidelines would be on using color states:

As far as I understand we show red (danger) when an issue persists that does not allow the user to execute the transaction and we use yellow (warning) to display information the user should now, but we don't limit if they can execute the transaction. Is this correct?

**Comment by valiafetisov** [comment]
> Is this correct?

Yeah, that's the current idea, although I'm not a sure about using red color, since it indicates some kind of error while it's actually not an error, but an unfulfilled requirement. Currently, there are 3 colors: red, yellow, green, grey; and a few icons: attention, cross, checkmark.

**Comment by LukSteib** [comment]
I like this panel based approach. Some thoughts / questions:

* What would the expert mode look like? Only having the status message and buttons in a panel with the explainer texts?
* I am not sure whether we should directly "endorse" Uniswap in our primary button once a user has not enough Dai to deposit. I see that not having a primary button here would somewhat break our flow. Hesitant whether we should just provide refresh button here though. 
* We do not provide the "shortcut" way of depositing the required amount of Dai for bidding (ie. this case is now always managed via the WalletPopup) any longer, correct? Due to the complexity of the non binary allowance auth step?
* I see the point of color coding red indicating an error while it's actually not an error. However it also draws the user's attention to the missing requirement and hence provides guidance. The latter aspect might be lost with a different color coding, so I think it is fine.

**Comment by valiafetisov** [comment]
> * What would the expert mode look like? Only having the status message and buttons in a panel with the explainer texts?

The expert mode is visible on the very first screen: it's basically the same, but without the inner explanation texts.

> * I am not sure whether we should directly "endorse" Uniswap in our primary button once a user has not enough Dai to deposit. I see that not having a primary button here would somewhat break our flow. Hesitant whether we should just provide refresh button here though.

Ok, we can keep only the refresh button and the links to other dexes in the explanation text.

> * We do not provide the "shortcut" way of depositing the required amount of Dai for bidding (ie. this case is now always managed via the WalletPopup) any longer, correct? Due to the complexity of the non binary allowance auth step?

Yes, user may not need any allowance at all, if they already have enough DAI in VAT, therefore initially designed flow is misleading. I can design the shortcut version of this flow, but it will have steps on its own, so can be too much complicated for the user. It may look [more or less like this](https://user-images.githubusercontent.com/3393626/159229301-f4f66482-7089-49ee-9965-69bdb34465ba.png), which I think a bit too much information on a single page.

> * I see the point of color coding red indicating an error while it's actually not an error. However it also draws the user's attention to the missing requirement and hence provides guidance. The latter aspect might be lost with a different color coding, so I think it is fine.

Alright! If we will use a single `BasePanel` for all of the panels, we can quickly change it later on.

**Comment by LukSteib** [comment]
> The expert mode is shown on the very first screen of the mock: it's basically the same panels, but without the inner explanation texts.

Alright, sounds and looks good.

> Ok, we can have only the refresh button, keeping the links to other dexes in the explanation text.

Let's do it this way.

> I can design the shortcut version of this flow, but it will have steps on its own, so can be too much complicated for the user. It may look [more or less like this](https://user-images.githubusercontent.com/3393626/159230047-8be1bbb8-d7ca-4456-a842-d734a00a7847.png), which I think a bit too much information on a single page.

Agree that it makes things on one page very complicated. Let's stick to your proposal to have the Wallet Popup always as separate step for now.
