### ISSUE TITLE
Investigate fetching of Maker protocol parameters

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#15]
#### Goal
Get Maker protocol parameters from the appropriate blockchain

#### Context
We should get the parameters of the Maker protocol (per collateral type or in their terminology, per `ilk`) in order to, for example, display information about when is the next price drop. You can see they are being fetched on https://daiauctions.com and you can investigate how it's done in the source code of this website here https://github.com/martinlsanchez/daiauctions (although the source code seems to be minified 🙁)

Also, current https://liquidations.makerdao.com portal (source can be found at https://github.com/makerdao/liquidations-portal/) also fetching those values as they display numbers such as `dust limit`. Most probably the best place to learn about that is to start by reading source code of the liquidations portal or via [dai.js documentation](https://docs.makerdao.com/build/dai.js/getting-started) (although dai.js docs are incomplete, does not include liquidations plugin).

#### Tasks
- [x] investigate how it's done in https://github.com/makerdao/liquidations-portal/
- [x] document how it is done here on the high-level (what exact method is called, what happens after that?)
- [x] document what data is available (dump raw example data here)
- [ ] shortly investigate if there is a better/easier way
- [ ] propose implementation for our use-case
- [ ] discuss findings and implementation proposal with @valiafetisov
