### ISSUE TITLE
Create `BasePanel` component

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#152]
### Goal
New reusable `BasePanel` component in the storyook

### Context
Based on the proposal made in https://github.com/sidestream-tech/unified-auctions-ui/issues/145, we want to have a new kind of base element for our UI: a panel. A panel is a component consisting of:
- prop `state`
  - `inactive`
  - `incorrect`
  - `complete`
  - `notice`
- prop and slots for each state
- An icon (based on the state)
- Default child slot to include content within the frame
- An expandable logic _with animation_ (default is based on the state, but the title is still user-clickable/collapsable/expandable and reacts to the `state` change)

Notes: 
- This component doesn't need to have `isExplanationsShown` prop, since this logic will be inside the child slot
- For the `prop and slot` logic, please use "fallback content" feature https://v2.vuejs.org/v2/guide/components-slots.html#Fallback-Content
- Example usage of the component:
```
<BasePanel
    :state="currentState"
    inactive="The VAT balance is unknown until a wallet is connected"
    incorrect="The amount is not present in the VAT"
    complete="The amount is present in the VAT"
>
  Content and buttons
</BasePanel>
```

### Assets
- `inactive`
    ![MakerDAO@2x (44)](https://user-images.githubusercontent.com/3393626/159236509-0aa2fb21-609c-4068-96d6-dafd197a8eff.png)

- `incorrect`
    ![MakerDAO@2x (43)](https://user-images.githubusercontent.com/3393626/159236647-f9c46055-94ed-4223-925a-5831528c352f.png)

- `complete`
   ![MakerDAO@2x (45)](https://user-images.githubusercontent.com/3393626/159236566-1d33914c-b8d7-4175-a7c2-c51fb372317a.png)

- `notice`
   ![MakerDAO@2x (47)](https://user-images.githubusercontent.com/3393626/159236779-1ba782eb-9ea7-4c76-a869-f9bd75bb0500.png)
 
- Slotted title
    ![MakerDAO@2x (48)](https://user-images.githubusercontent.com/3393626/159237613-cbed8c7d-e281-496b-9758-28eef319f9a8.png)

- Stack of the panels (please note that the panel borders should overlap each other with `.BasePanel + .BasePanel` css selector)
    ![MakerDAO@2x (49)](https://user-images.githubusercontent.com/3393626/159238007-ed2e1b5e-7ce8-4042-9877-71e805b72b67.png)

### Tasks
- [x] Create a BasePanel component
- [ ] Add stories for all possible use-cases
  - [x] Multi-line title
  - [x] Title via named slot (eg with the wallet address)
  - [ ] Stack of the panels
  - [ ] Animation between `incorrect` and `complete` states
