### ISSUE TITLE
Expand Dark Mode toggle

### ISSUE THREAD

**Issue by zoey-kaiser** [sidestream-tech/unified-auctions-ui#16]
**Goal**
Our current dark mode toggle only allows users to switch between dark and light mode. We wanted to add a third option to switch to the device preference. Currently the device preference is only taken if the user does not select  a theme, however we want to give the user the ability to switch back to their device preference. In the toggle add a computer icon as the icon for the device theme.

**Tasks**

- [ ] Add a third theme option  called "device". (You may need to re-structure how the dark mode state works (or use `null`))
- [ ] When `device` theme is selected the device theme will be taken
- [ ] Make  `device` the default theme

**Media*

https://user-images.githubusercontent.com/30908158/136959293-ae3d93c2-c027-4c9e-a4bc-235e77ac6ce7.mov
