### ISSUE TITLE
Release v1.1.0

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#162]
### Planned Release Scope
- Product stream 
   - Consolidate requirements and think about mid term roadmap
   - Coordinate re-direct DNS settings 
   - facilitate a meeting with C. Mooney for exchange on keeper
   - sidestream-tech/unified-auctions-ui#172
-   Blockchain stream
    - [x] sidestream-tech/auction-ui#401 
    - [x] sidestream-tech/unified-auctions-ui#94
    - [ ] push chaoslabs testing setup https://github.com/sidestream-tech/unified-auctions-ui/issues/83
-   Devops stream
    - [ ] https://github.com/sidestream-tech/unified-auctions-ui/issues/66
-   UI/fixes stream 
     - [x] sidestream-tech/unified-auctions-ui#128 
     - [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/162#issuecomment-1087246062
     - [x] sidestream-tech/unified-auctions-ui#177 
-   Bonus
    - [ ] sidestream-tech/unified-auctions-ui#137 
    - [ ] Interlink all other UIs with our UI (open PRs to other websites / source codes) - https://github.com/sidestream-tech/unified-auctions-ui/issues/93
---

Predecessor: sidestream-tech/unified-auctions-ui#114

- [ ] In-between deployment once sidestream-tech/unified-auctions-ui#94 is done
- [ ] double-check with @valiafetisov and @LukSteib whether release makes sense
- [ ] test staging environment
- [ ] release images via UI https://github.com/sidestream-tech/auction-ui/releases/new 
- [ ] Deploy staging to production _goal: 14.04.22
   - [ ] Test prod environment
- [ ] Share release notes in makerForum _goal: 14.04.22

**Comment by LukSteib** [comment]
Additionally I see different alternatives for next larger features that we need to conceptualise in this sprint
* **Partial swap feature**
  * value add: If there is not enough or low lquidity for the collateral that is going to be swapped it might be more profitable for a user to execute the swap partially. 
  * pro
    * addition to the existing swap transaction based flow
  * con
    * the value add might be low compared to the effort since most of the time a complete swap is more profitable and hence preferred by user
* **Flap auctions**
  * value add: The second important type of auctions that we can move under the umbrella of unified auctions. Especially in recent time a lot of these auctions have been started. Hence, high interest among the broader community in this type of auction
  * pro
    * see value add. Important further auction type that we would start to tackle
  * con
    * a strong interest in moving this auction type to the liquidiation 2.0 mechanism was raised within the community not only lately. It is an item on the PE roadmap. Logic that we are implementing now might need to be refactored in the not to far future (sunk cost?)
  * reference UI: https://auctions.makerdao.com/flap
  * reference repo: https://github.com/makerdao/auctions-ui

**Comment by valiafetisov** [comment]
I think the release should be named `0.11.0` as initially proposed, since we're following [semantic versioning](https://semver.org/). Why was the previous release changed to `1.0.0`?

Regarding the scope, I would remove something from the blockchain stream, since I'm working on it alone atm and would add more tasks for the UI stream. After working on the panels in the wallet popup I also thought that it's better to create an issue per each panel type, so it's less messy and more properly tested in isolation, therefore I need to create additional issues for:

- adding stories for existing panels
  - `AllowanceAmountCheckPanel`
  - `WalletAuthorizationCheckPanel`
  - `WalletDaiDepositCheckPanel`
  - `WalletVatDaiWithdrawCheckPanel`
- Implement new `WalletConnectedCheckPanel`
- Implement new `CollateralAuthorizationCheckPanel` 
- Implement new `GrossProfitCheckPanel`
- Implement new `NetProfitCheckPanel`
- Implement new `AuctionRestartPanel` which contains `WalletConnectedCheckPanel` and restart functionality

**Comment by valiafetisov** [comment]
I've created few issues for panels, @LukSteib feel free to help with the rest 🙂 

Besides, maybe for the next sprint, to unload it from my mind:
- optimise for mass liquidation
    - test mass liquidation using forking or simulation with ~100 active auctions
    - subscribe to events instead of constantly refetching all auctions (similar to https://github.com/sidestream-tech/unified-auctions-ui/issues/173)
    - improve profitability time calculation to use less / limited resources
- properly handle finished and partly taken auction state
- remove stub data to optimise container logic
- add bots on other platforms
- https://github.com/sidestream-tech/unified-auctions-ui/issues/150
