### ISSUE TITLE
Update Bidding with DAI `the amount to receive` logic

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#165]
### Goal

Fixed `amount to receive` indication in the BidTransactionTable

### Context

After executing first Bid with DAI transaction, we realised that the user doesn't receive the whole amount of collateral. More info here: https://github.com/sidestream-tech/unified-auctions-ui/pull/163#issuecomment-1082005735. Based on this, we need to:
- [x] Create new `core` function which will calculate actual `amount to receive` based on the input value
- [x] Add store logic to fetch collateral in the VAT
- [x] Add store logic to withdraw collateral from VAT to Wallet

### Tasks
- [x] Implement all the above
- [x] Provide testing commands in the PR description
