### ISSUE TITLE
Enable TailwindCSS JIT mode

### ISSUE THREAD

**Issue by zoey-kaiser** [sidestream-tech/unified-auctions-ui#17]
**Goal**
TailwindCSS offers a new feature called `Just-In-Time` compiling. It complies the tailwind classes every time the files are updated, removing the need for reloading the site on the introduction of never before used classes. It also removes the need to enable variants for dark, active etc. Lastly it lets us use custom sizes (h-[5px]).

https://tailwindcss.com/docs/just-in-time-mode

**Tasks**

- [ ] Research if the JIT mode works in our project
- [ ] Add it to the project and storybook
- [ ] Test for any errors (if they occur, find a fix)
- [ ] Once everything works also add it to the vue-nuxt-ts-scafold
