### ISSUE TITLE
Discuss approach to manage VAT w/o auction

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#172]
**Goal:**
Conceptualise how a user can manage funds in VAT different from active auction based flow. 

**Context:**
The user needs to be able to interact with the VAT in different ways:
* deposit Dai in order to bid
* withdraw Dai from VAT back to wallet
* withdraw collateral (after successful bid on auction) 

Points 1+2 are currently enabled via the WalletPopup. Point 3 is currently enabled via the WithdrawBlock at the bottom of the BidTransaction page. 
The downside of the current approach: Interaction with VAT requires an active auction
In order to overcome this downside we need to provide a way that allows the user to interact with VAT even if there is no active auction.

First proposal: 
* Facilitate all possible VAT interactions via the WalletPopup
* Implement a way to trigger the WalletPopup without the need for an active auction

**Tasks:**
- [x] Discuss solution alternatives
- [x] Update Mock accordingly
- [x] Write implementation issues

**Comment by LukSteib** [comment]
This was partially addressed in #156. We provide a way for the user to `Manage Wallet` via our header.
Meaning:
* deposit Dai in order to bid (addressed ✅ )
* withdraw Dai from VAT back to wallet (addressed ✅ )
* withdraw collateral (still open) 

So we might think about whether and how to enable withdrawal of collateral independent from active auctions

**Comment by valiafetisov** [comment]
> withdraw collateral

Since there are 37 collaterals at the moment, we need to execute 37 different requests to check their balance, so maybe we can do it in a separate page / popup? In the end it will look quite similar to the collateral table in the dashboard and besides displaying amount and a button to withdraw we can add token address + authorization status there as well (since users may want to pre-authorize it). So: create a table with all collaterals as rows, `collateralType, address, authorization status / button, balance / withdraw button` as columns + a new popup or a panel inside wallet popup.

**Comment by valiafetisov** [comment]
![MakerDAO@2x](https://user-images.githubusercontent.com/3393626/163956942-83e3ea32-ea79-40df-9bef-784a7a36f6b2.png)

**Comment by LukSteib** [comment]
Like the proposal above 👍 And I agree to handle it in a separate popup. 
Currently the heading of our wallet popup says "Manage Dai in VAT". We might provide a clickable second option that says "Manage collateral in VAT" and let the user switch between the two.

**Comment by valiafetisov** [comment]
Closing this, as the outstanding feature will be implemented in https://github.com/sidestream-tech/unified-auctions-ui/issues/214
