### ISSUE TITLE
Create stories for `WalletDaiDepositCheckPanel` and `WalletVatDaiWithdrawCheckPanel`

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#175]
### Goal
Stories that cover all edge cases

### Context
New components were implemented in the last sprint, but the stories are missing. This issue is about implementing the stories to check all possible edge cases and also learn how the components are implemented. 

Please note that every prop that receives BigNumber, should have a story with `NaN` and undefined. We should also check that `disabled` and `isLoading` works properly in all combinations. In the end I expect there is like 10+ stories for each component with every combination that makes sense.

### Tasks
- [ ] create stories for `WalletDaiDepositCheckPanel`
- [ ] create stories for `WalletVatDaiWithdrawCheckPanel`
- [ ] make sure `isCorrect` is handled via action
