### ISSUE TITLE
Implement new `WalletConnectedCheckPanel`

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#176]
### Goal

New panel that checks wallet connection

### Context
Since we're moving to the universal panel approach, we should make a new component that checks "if a wallet is connected" and "display actions to connect it in case it's not". The states of the panel can be on [the mock](https://github.com/sidestream-tech/unified-auctions-ui/issues/145#issuecomment-1070902434) and on the existing WalletBlock, but please edit the texts to be be universal so the panel can be reused in many different places regardless of the context. This particular panel will be used in:
- bid transaction page
- swap transaction page
- reset auction
- wallet popup

Please refer to the existing panels `AllowanceAmountCheckPanel`, `WalletAuthorizationCheckPanel`, `WalletDaiDepositCheckPanel` and `WalletVatDaiWithdrawCheckPanel` for the inspiration. Please note that the panel should emit valid `isCorrect` value on state change. Please add stories that cover all potential edge cases.

### Tasks
- [ ] create the panel
- [ ] add all possible stories with all combination of props
- [ ] edit / propose new text and titles for different states in the code itself
