### ISSUE TITLE
Implement new `CollateralAuthorizationCheckPanel`

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#179]
### Goal

New panel that checks authorization for collateral type

### Context
Since we're moving to the universal panel approach, we should make a new component that checks "if the collateral type of the auction at hand was already authorized for the wallet" and "display actions to connect it in case it's not". The states of the panel can be found on [the mock](https://github.com/sidestream-tech/unified-auctions-ui/issues/145#issuecomment-1070902434) and on the existing AuthorisationBlock, but please edit the texts to be be universal so the panel can be reused in many different places regardless of the context. This particular panel will be used in:
- bid transaction page
- swap transaction page

Please refer to the existing panels `AllowanceAmountCheckPanel`, `WalletAuthorizationCheckPanel`, `WalletDaiDepositCheckPanel` and `WalletVatDaiWithdrawCheckPanel` for the inspiration. Please note that the panel should emit valid `isCorrect` value on state change. Please add stories that cover all potential edge cases.

### Tasks
- [x] create the panel
- [x] add all possible stories with all combination of props
- [ ] edit / propose new text and titles for different states in the code itself
