### ISSUE TITLE
Implement new `GrossProfitCheckPanel`

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#180]
### Goal

New panel that checks gross profit of transaction

### Context
Since we're moving to the universal panel approach, we should make a new component that checks "if transaction gross profit is positive" and "prevent user from being able to execute if gross profit is negative". One state of the panel can be found on [the mock](https://github.com/sidestream-tech/unified-auctions-ui/issues/145#issuecomment-1070902434).
States needed (please extend list if you come up with more relevant ones):
* gross profit positive
* gross profit negative
* Unknown
* Expert mode

Please edit the texts to be be universal so the panel can be reused in many different places regardless of the context. This particular panel will be used in:
- swap transaction page

Please refer to the existing panels `AllowanceAmountCheckPanel`, `WalletAuthorizationCheckPanel`, `WalletDaiDepositCheckPanel` and `WalletVatDaiWithdrawCheckPanel` for the inspiration. Please note that the panel should emit valid `isCorrect` value on state change. Please add stories that cover all potential edge cases.

### Tasks
- [x] create the panel
- [x] add all possible stories with all combination of props
- [x] edit / propose new text and titles for different states in the code itself
