### ISSUE TITLE
Implement new `NetProfitCheckPanel`

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#181]
### Goal

New panel that checks net profit of transaction

### Context
Since we're moving to the universal panel approach, we should make a new component that checks "if transaction net profit is positive" and "warn user to execute with negative net profit". One state of the panel can be found on [the mock](https://github.com/sidestream-tech/unified-auctions-ui/issues/145#issuecomment-1070902434).
States needed (please extend list if you come up with more relevant ones):
* net profit positive
* net profit negative
* Loading
* Unknown
* Expert mode

Please edit the texts to be be universal so the panel can be reused in many different places regardless of the context. This particular panel will be used in:
- swap transaction page

Please refer to the existing panels `AllowanceAmountCheckPanel`, `WalletAuthorizationCheckPanel`, `WalletDaiDepositCheckPanel` and `WalletVatDaiWithdrawCheckPanel` for the inspiration. Please note that the panel should emit valid `isCorrect` value on state change. Please add stories that cover all potential edge cases.

### Tasks
- [x] create the panel
- [x] add all possible stories with all combination of props
- [x] edit / propose new text and titles for different states in the code itself
