### ISSUE TITLE
Implement new `WithdrawCollateralPanel`

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#183]
### Goal

New panel that allows user to withdraw collateral from VAT

### Context
Since we're moving to the universal panel approach, we should make a new component that allows a user to withdraw collateral of the auction at hand from VAT to wallet. The states of the panel can be found on the existing WithdrawCollateralBlock, but please edit the texts to be be universal so the panel can be reused in many different places regardless of the context. This particular panel will be used in:
- bid transaction page
- swap transaction page

Please refer to the existing panels `AllowanceAmountCheckPanel`, `WalletAuthorizationCheckPanel`, `WalletDaiDepositCheckPanel` and `WalletVatDaiWithdrawCheckPanel` for the inspiration. Please note that the panel should emit valid `isCorrect` value on state change. Please add stories that cover all potential edge cases.

### Tasks
- [x] create the panel
- [x] add all possible stories with all combination of props
- [ ] edit / propose new text and titles for different states in the code itself

**Comment by LukSteib** [comment]
I am hesitant whether this panel fits to the logic of the other panel states. 
This one has no direct impact on transaction execution. Moreover the user is not required to withdraw collateral immediately. So an error state with heading "Nothing to withdraw" imo is not really appropriate here. 

I would propose the following states:
`Disabled` (in case there is no collateral of this type deposited to VAT):
<img width="455" alt="image" src="https://user-images.githubusercontent.com/36229155/161566628-3bbc77c2-f706-446e-b5ec-5809e1b25f96.png">

`WithdrawPossible` (in case there is collateral of this type deposited to VAT):
<img width="572" alt="image" src="https://user-images.githubusercontent.com/36229155/161567341-e036a1aa-0c90-4496-a9d3-667c9533d596.png">





Downside: We cannot use it as an universal withdraw block for collateral that might be used on the WalletPopup or somewhere else later on.
@valiafetisov what is your opinion?

**Comment by LukSteib** [comment]
> but the one with notice state feels out of place, maybe we just need to change notice title to not be yellow, not sure

Agree! Updated the tiny mock above.
