### ISSUE TITLE
Investigate surplus auctions logic

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#188]
### Goal

Step-by-step explanation how it works, implementation proposal

### Context

Besides collateral auctions that are already supported by the UI and the keeper, we also want to support Maker surplus auctions ([or `flap` auctions using maker terminology](https://docs.makerdao.com/smart-contract-modules/system-stabilizer-module/flap-detailed-documentation)). It is currently supported by the https://auctions.makerdao.com/flap platform ([source code](https://github.com/makerdao/auctions-ui)), but our UI should eventually support all auction types. There are other projects like [flap-auctions-api](https://github.com/makerdao/flap-auctions-api) that may implement desired functionality in other languages that can also be used for reference.

The main goal of the issue is to investigate what smart contracts are responsible for those types of auctions, how existing tools deal with it. This should be done by documenting it in the issue using english terms (instead of maker terms).

For the example of this kind of research issue, you can have a look at the recent `Implement wallet-related logic` issue https://github.com/sidestream-tech/unified-auctions-ui/issues/124 and its investigation result https://github.com/sidestream-tech/unified-auctions-ui/issues/124#issuecomment-1064277892 as well as the PR https://github.com/sidestream-tech/unified-auctions-ui/pull/143 itself.

### Tasks
- [x] investigate how it's done, document here with links to the source code
  - [x] insure step-by-step process is documented including steps that are unknown at the moment (eg authorization step)
- [ ] Discuss the scope
- [ ] Propose clear implementation approach

**Comment by KirillDogadin-std** [comment]
Here're some (ongoing) investigation records

contract name: `MCD_FLAP`  https://github.com/makerdao/auctions-ui/blob/master/constants.js#L39

Probably will need the following fucntions in the core for the feature:
    - transferMKRtoAddress - `tend` gets realised and the user can bet MKR on the auction
    - confirmWinningBid - `deal` is realised and the user can withdraw DAI from the auction
    - https://github.com/makerdao/auctions-ui/blob/master/hooks/useAuctionActions.js#L46-L62

additional functions that might be related.

https://github.com/makerdao/auctions-ui/blob/master/hooks/useAuctionActions.js#L46-L62
https://github.com/makerdao/auctions-ui/blob/master/hooks/useAllowances.js#L86-L96

So far I did not manage to figure out how the auth should look like in the upcoming implementation but just to keep track, here's some relevant info:  
(auth?) https://github.com/makerdao/auctions-ui/blob/master/hooks/useAllowances.js#L190-L204
(auth?) https://github.com/makerdao/auctions-ui/blob/master/hooks/useAllowances.js#L19


misc: [provider](https://github.com/makerdao/auctions-ui/blob/master/providers/MakerProvider.js)
misc: Accroding to https://github.com/makerdao/flap-auctions-api/blob/04d5250e107d7c2263968e1fec39ee38d57745f6/flap_auctions/events_extractor.py#L79-L111 we might need to react to events:
    - deal
    - tend
    - kick

**Comment by KirillDogadin-std** [comment]
[__source__](https://docs.makerdao.com/smart-contract-modules/system-stabilizer-module/flap-detailed-documentation#illustration-of-the-bidding-flow)

 - To start the auction, conditions of the system surplus have to be met: https://github.com/makerdao/dss/blob/fa4f6630afb0624d04a003e920b0d71a00331d98/src/vow.sol#L149
     - vat.dai ( vow contract address ) should be greater or equal the margin than the sum of:
         - vat.sin ( vow contract address )
         - vow.hump
         - vow.bump
     - vat.sin should be equal to the sum of:
         - vow.Sin
         - vow.Ash
 - There's a running auction that was `kick`ed by `flap`
 - We fetch the auction
     - first fetch the `kicks` which is the id of the latest auction or 0
         - we can use the kicks to retreive the auction data by calling the `bids` (public state) and passing the `[id]`
     - we fetch the event called `Kick` as in [here](https://github.com/makerdao/flap-auctions-api/blob/04d5250e107d7c2263968e1fec39ee38d57745f6/flap_auctions/events_extractor.py#L99-L110) and store parts of it
 - We observe the `Tend` events:
     - other people can add bids to the auction via calling `tend` and specifying the new
     (grater, it's greater by at least the minimal value of `beg`, `beg` is the property of the FLAP contract. https://github.com/makerdao/dss/blob/fa4f6630afb0624d04a003e920b0d71a00331d98/src/flap.sol#L70) price
         - this will return money to the previous bidder from the funds of the new one
         - it will send the rest of the tend's money to the Flap storage.
         - it will reset the expiration timer;
 - auction ends when the expiration happens:
     - `end` is set to be now + `tau` https://github.com/makerdao/dss/blob/fa4f6630afb0624d04a003e920b0d71a00331d98/src/flap.sol#L72 on auction start
     - `tic` is set [here](https://github.com/makerdao/dss/blob/fa4f6630afb0624d04a003e920b0d71a00331d98/src/flap.sol#L155) upon the subsequent bid `=` now + `ttl` https://github.com/makerdao/dss/blob/fa4f6630afb0624d04a003e920b0d71a00331d98/src/flap.sol#L71
     - when either of the above stated time moments have passed, the auction ends and the winner can collect the lot.
 - when the auction is closed, the winner can collect the prize by calling `deal` https://github.com/makerdao/dss/blob/fa4f6630afb0624d04a003e920b0d71a00331d98/src/flap.sol#L157 which:
     - this moves the prize to the winner's wallet
     - burns the bid



___auth required___

- unlock mkr for the auction (what is this???)
- call `vat.hope`
- the dai allowance to `DaiJoin` should be set to the bid amount (probably ??? )

**Comment by valiafetisov** [comment]
Main source of information: latest [makerdao/dss/src/flap.sol](https://github.com/makerdao/dss/blob/fa4f6630afb0624d04a003e920b0d71a00331d98/src/flap.sol) with rate limiting [introduced ~3 months ago](https://github.com/makerdao/dss/commit/60690042965500992490f695cf259256cc94c140)

 - To start a surplus (`flap`) auction, `vow.flap()` have to be called with no arguments
   - The method will execute only at [certain conditions](https://github.com/makerdao/dss/blob/fa4f6630afb0624d04a003e920b0d71a00331d98/src/vow.sol#L149-L150)
     - There should be sufficient amount of surplus: `vat.dai(vow contract address)` should be greater or equal than the sum of:
         - `vat.sin(vow contract address)`
         - `vow.hump()`
         - `vow.bump()`
     - System debt should be 0: `vat.sin(vow contract address)` should be equal to the sum of:
         - `vow.Sin()`
         - `vow.Ash()`
     - Total amount of auctioned DAI (`flap.fill()`) should be lower or equal than the limit (`flap.lid()`)
   - Starting an auction
     - Would [execute `flap.kick`](https://github.com/makerdao/dss/blob/fa4f6630afb0624d04a003e920b0d71a00331d98/src/vow.sol#L151) with:
       - `vow.bump()` as `lot` – DAI in return for bid
       - `0` as `bid` – amount of MRK to be paid
     - Would effectively add new record to `flap.bids` with
       - `bids[id].bid` – amount of MRK to be paid
       - `bids[id].lot` – amount of DAI to be received
       - `bids[id].guy` – the address of the wallet who made the bid (and will be able to receive DAI)
       - `bids[id].end` – final time when auction will end (now + `flap.tau()` – 2 days atm)
     - Would emit `Kick` event with `(id, lot, bid)`
 - To fetch an auction, there are two options:
     - a) 
         - fetch the latest integer id of the bid (aka `flap.kicks()`) – note that initially it's `0`
         - use latest id to retrieve auction data by getting appropriate bids record (`flap.bids(id)`) – note that if auction is completed, there will be no data under the id
     - b)
       - fetch `flap` event called `Kick` and process its parameters as in [flap-auctions-api](https://github.com/makerdao/flap-auctions-api/blob/04d5250e107d7c2263968e1fec39ee38d57745f6/flap_auctions/events_extractor.py#L99-L110)
 - Bidding (ie executing `flap.tend(id, lot, bid)`)
     - There are several checks before the new bid is accepted
       - Check that auction is not expired (`bids[id].tic > now || bids[id].tic == 0` and `bids[id].end > now`)
       - DAI to be received should be exactly the same as previously (`lot == bids[id].lot`)
       - MKR to be paid should be greater than previously (`bid >  bids[id].bid`)
       - MKR to be paid should be greater than previously by `flap.beg()` percent, [see here](https://github.com/makerdao/dss/blob/fa4f6630afb0624d04a003e920b0d71a00331d98/src/flap.sol#L146)
     - This will
         - return MRK to the previous bidder from the funds of the new one (within VAT, I believe)
         - send the increased part of the MRK to the flapper address
         - update `bids[id].bid` value
         - reset expiration time to the new value (`bids[id].tic` = now + `flap.ttl()`, 3 hours atm)
         - emit `Tend` event
- Restarting an auction
  - In case there were no bids (ie `bids[id].tic` is `0`), the auction will expire after `bids[id].end` time (currently end is set to be 2 days after auction start) and will not allow any more bids or collection of DAI
  - There is a public method (`flap.tick(id)`) executing which will update `bids[id].end` time
    - Only executed if no bids were made yet (bids[id].tic` is `0`)
    - Can be executed by anyone
    - Doesn't emit any events! 🤯 
- In order for the bidder to collect DAI
   - Several conditions should be met
     - `bids[id].tic` can not be `0` – meaning that there should be at least one bid (except the initial)
     - Auction have to be expired – either because of bid timeout or auction end (`bids[id].tic < now || bids[id].end < now`)
   - In order to receive DAI, `flap.deal(id)` should be executed by someone (not necessarily the winner), which
     - will move DAI saved in VAT under flap address to `bids[id].guy` address (by the amount of latest `lot`)
     - will burn MKR saved in VAT under flap address (by the amount of latest `bid`)
     - will delete auction record (`delete bids[id]`)
     - will update `flap.fill` – total amount of currently running flap auctions
- DAI in the VAT can be withdrawn to the actual wallet

There is also a possibility to return previous bid and delete auction by calling `flap.yank(id)`

### Authentication

- MKR collateral authorization is required to bid (`tend`) but doesn't seem to be required to start auction (`flap`/`kick`)
- DAI authorization (`vat.hope()`) is required to move DAI around, so I suppose it's required for every execution (TODO: check)
- MRK allowance? Since we need MKR to bid
- DAI allowance to `DaiJoin` (TODO: check when and why, since no DAI suppose to be withdrawn, but MKR)

**Comment by valiafetisov** [comment]
Should we include functionality to start surplus auction within the UI already? I can see few pros/cons:
- `+` there is just one place to check it (technically we need to make at least 6 calls to check if it's possible to execute `vow.flap`, few others to show other related parameters)
- `+` it would also make sense if we would need to test it ourselves (we would only need to increase surplus in hardhat)
  - `-` we may start testing it by running over previous version of the flap without the `lid`
- `-` to insure equal participation it will be enough to only announce started auctions via twitter and insure clear UI

My proposal is to start without `kick` functionality, at least not in the UI, to limit the scope, but I would try to keep it in mind for the future.

@LukSteib, what do you think?

**Comment by valiafetisov** [comment]
General ideas:
- We should rename maker vocabulary to english terms
- Frontend should receive/call only high-level methds that makes sense eg a single function `subscribeToSurplusAuctions`, and should not know internal logic (so the internal logic shuold be converted to high-level `state` for example)
- Please have a look at the mock first https://github.com/sidestream-tech/unified-auctions-ui/issues/288

### Implementation suggestion

- Core `surplus.ts`
    - Create function to fetch auction by index `fetchSurplusAuctionByIndex(network, index)`
        - fetch events related to the auction, filtering by its index
        - returns renamed and transformed auction with events array
            ```ts
            // NB: this is only a proposal
            interface SurplusAuctionData {
                bidAmountMKR: BigNumber | undefined; // amount of MRK (bid)
                receiveAmountDAI: BigNumber; // amount of DAI to be received (lot)
                receiverAddress: string; // the address of the wallet who receives DAI (guy)
                auctionEndDate: Date; // final date when auction will end (now + `flap.tau()` – 2 days atm) (end)
                bidEndDate: Date; // (tic)
                earliestEndDate: Date; // earliest of auctionEndDate and auctionEndDate
                state: 'just-started' | 'have-bids' | 'ready-for-collection' | 'collected' | 'requires-restart'; // auction state determined from fetched events
            }
            interface SurplusBid extends SurplusAuctionData {
                type: 'start' | 'bid' | 'collect'; // as 'Kick', 'Tend', 'Deal'
                transactionHash: string;
                transactionDate: Date; // determined from block number (see `fetchDateByBlockNumber`)
                // other SurplusAuctionData fields
            }
            interface SurplusAuction extends SurplusAuctionData {
                events: SurplusEvent[];
            }
            ```
        - in case the `currentState === 'just-started'`, we should additionally fetch `flap.kicks(index)` to check that the auction was not restarted (because calling `flap.tick(index)` [resets `auctionEndDate`, but emits no events](https://github.com/makerdao/dss/blob/fa4f6630afb0624d04a003e920b0d71a00331d98/src/flap.sol#L133-L137)) – this should also be fetched after the restart transaction execution
    - Create a function to fetch "active" auctions `fetchCurrentSurplusAuctions(network)`
        - gets latest `index` via `flap.kicks()`
        - gets all auctions in a loop via calling `flap.bids()` with decreasing `index` until it reaches an auction with with `end === 0`
        - executes `fetchSurplusAuctionByIndex` for each valid `index`
    - Create a function to subscribe to auction updates `subscribeToSurplusAuctions(network, callback)`
        - execute `fetchCurrentSurplusAuctions`
            - return list of auctions via `callback(auctions)`
        - subscribe via websocket to new events
            - as soon as there is new event, execute `fetchSurplusAuctionByIndex` to refetch related auction
                - return auction via `callback([auction])`
    - Make sure it's possible to call collateral authorization and collateral allowance functions (and also ones that fetch their statuses) with MKR as a parameter
    - Make sure it's possible to call balance and VAT balance with MRK, deposit and withdrawal
    - Create a function to restart `restartSurplusAuction` (`tick`)
      - call refetch for this auction, emit `subscribeToSurplusAuctions` callback to refresh restarted auction
    - Create a function to bid `bidToSurplusAuction` (`tend`)
    - Create a function to collect `collectSurplusAuction` (`deal`)

- Frontend `surplus` store
    - create new store `Record<surplusAuction.id, SurplusAuction>`
    - action to `setup`
        - set is loading
        - call `subscribeToSurplusAuctions`
        - populate auctions
    - action to reset
    - action to bid
    - action to collect
    - setup action to call all related fetching / 

- Frontend 
    - Create `SurplusAuctionTable`
    - Create `SurplusEventsTable`
    - Create `SurplusAuctionTransactionTable`
    - Add MKR balance and MKR VAT balance to the wallet modal
    - Add MKR to the collareal modal
    - Create new `WalletMkrDepositCheckPanel` component in storybook
    - Create new `HighestBidCheckPanel` component in storybook
    - Create new `CollectSurplusAuctionPanel` component in storybook
    - Create new `SurplusAuctionRestartPanels` component in storybook
    - Create `SurplusAuction` component and page with restart and error states
    - Create `SurplusAuctionTransaction` component and page with all panels
    - Create `SurplusAuctionContainer`

**Comment by KirillDogadin-std** [comment]
> Make sure it's possible to call collateral authorization and collateral allowance functions (and also ones that fetch their statuses) with MKR as a parameter
> Make sure it's possible to call balance and VAT balance with MRK, deposit and withdrawal

could you elaborate on what you imply by _"call with MKR"_, please?

**Comment by valiafetisov** [comment]
Currently, we already have functions to interact with `gemLike` contracts. For example [`withdrawCollateralFromVat`](https://github.com/sidestream-tech/unified-auctions-ui/blob/ab0d9eb87f0c35417f06af1918922093c73b0b61/core/src/wallet.ts#L75-L86) which accepts `collateralType` as input. But MKR is not a "collateral type" in our internal sense and can't be added to the [list of collaterals](https://github.com/sidestream-tech/unified-auctions-ui/blob/main/core/src/constants/COLLATERALS.ts). So you either need to modify `withdrawCollateralFromVat` to accept MKR (which would require a lot of refactoring and renaming) or simply copy existing logic into `withdrawMRKFromVat` and modify it to work with MKR. Looking at the code, I actually think second option would make more sense.

**Comment by benediktkaiser** [comment]
As I needed to create the first types for the frontend issues I currently updated the type mocking to:

```js
export type SurplusAuctionStates =
    | 'just-started'
    | 'have-bids'
    | 'ready-for-collection'
    | 'collected'
    | 'requires-restart';

export type SurplusAuctionEventTypes = 'start' | 'bid' | 'collect';

export declare interface SurplusAuctionData {
    bidAmountMKR?: BigNumber;
    receiveAmountDAI: BigNumber;
    receiverAddress: string;
    auctionEndDate: Date;
    bidEndDate?: Date;
    earliestEndDate: Date;
    state: SurplusAuctionStates;
}

export declare interface SurplusEvent extends SurplusAuctionData {
    type: SurplusAuctionEventTypes;
    address: string;
    transactionHash: string;
    transactionDate: Date;
}

export declare interface InitialSurplusAuction extends SurplusAuctionData {
    id: number;
    network: string;
    events: SurplusEvent[];
}

export declare interface SurplusAuction extends InitialSurplusAuction {
    marketUnitPrice: BigNumber;
    highestBid?: BigNumber;
    auctionPrice?: BigNumber;
}
```

**Comment by KirillDogadin-std** [comment]
Regarding the block of the external code that reacts to [3 types of events](https://github.com/makerdao/flap-auctions-api/blob/04d5250e107d7c2263968e1fec39ee38d57745f6/flap_auctions/events_extractor.py#L79-L111):

apparently, with ethers it's not straighforward (mb even not really possible) to get the similar result.

As verbally discussed, I've looked into the possibility of getting the transactions list that is relevant to the specific contract.
Due to me still not having the complete understanding of the underlying processess, i'd like to get the external input to the picture.

__Discoveries__

- [Ethers](https://docs.ethers.io/v5/api/contract/contract/#Contract) is capable of doing the [filtering](https://docs.ethers.io/v5/concepts/events/#events--filters) per contract
- But this relies still on the contract to emit the event
- As the Dai implements erc20, and the contract itself has the event `Kick` defined, i assume that the hypothetical filtering then has to only take into account the events (kick, transfer, approval)

Then, according to https://github.com/makerdao/dss/blob/master/src/dai.sol (and essentially https://github.com/makerdao/dss/blob/master/src/flap.sol) 

- the tend event could be detected as `Transfer` to the contract address
- the deal event burns the MKR, so this would be a `Transfer` to the 0 address.

Does this base idea and concept for implementation?

**Comment by KirillDogadin-std** [comment]
The [previous version](https://etherscan.io/address/0xc4269cc7acdedc3794b221aa4d9205f564e27f0d#events) emits apparently as expected kick only. The rest is nameless and apparently requires the approach of the existing python lib

**Comment by valiafetisov** [comment]
Ethers.js have two different apis for event subscriptions: `provider.on` and `contract.on` – we wouldn't want to use the provider, otherwise we would need to parse every single mined block. It would also not allow us to fetch previous events (otherwise we would need to retrieve all blockchain blocks to find particular event). Using `pending` pool is also problematic, since we only want to fetch confirmed transactions (transactions under a few other blocks), but `pending` transactions are not even mined yet. Therefore, we need to use `contract.on` and fetch the events not explicitly emitted, but recorded through the `transaction log`.

`pymaker` library first [fetches](https://github.com/makerdao/pymaker/blob/08821054d009a3b75fd83b248008002391a9c95a/pymaker/auctions.py#L125) events via [`getLogs`](https://web3py.readthedocs.io/en/stable/web3.eth.html#web3.eth.Eth.get_logs) filtered by the contract address, then parses useful events [using their signatures](https://github.com/makerdao/pymaker/blob/48eec6f81ea9bae3d6592be5a2d73c870323c1c5/pymaker/auctions.py#L347-L353). Can you try to fetch raw events from the previous flap contract (for now you can use hardhat to roll back to the block where this address is still in chainlog, eg 14073986), post them here and see if we can distinguish those events by the same signatures?

**Comment by valiafetisov** [comment]
Based on the investigation into the events, the conclusion is that we're not able to fetch information about previous `tend`s and `deal`s. We're also not able to fetch `Kick` for a particular auction because its id property is not indexed therefore we can only fetch all Kicks or none. Therefore, I suggest to remove the whole possibility to get previous transactions.

I've updated the mock https://github.com/sidestream-tech/unified-auctions-ui/issues/288 based on the findings and also the previous comments left in whimsical.

Implementation proposal should be changed accordingly: we do not fetch events, remove `SurplusEvent` type:

```ts
export type SurplusAuctionState =
    | 'just-started'
    | 'have-bids'
    | 'ready-for-collection'
    | 'collected'
    | 'requires-restart';

export declare interface SurplusAuctionData {
    id: number;
    network: string;
    state: SurplusAuctionState;
    bidAmountMKR: BigNumber; // amount of MRK (bid)
    receiveAmountDAI: BigNumber; // amount of DAI to be received (lot)
    unitPrice: BigNumber; // bidAmountMKR/receiveAmountDAI or the other way around
    receiverAddress: string; // the address of the wallet who receives DAI (guy)
    auctionEndDate: Date; // final date when auction will end (now + `flap.tau()` – 2 days atm) (end)
    bidEndDate?: Date; // (tic)
    earliestEndDate: Date; // earliest of auctionEndDate and auctionEndDate
}

export declare interface SurplusAuction extends SurplusAuctionData {
    marketUnitPrice: BigNumber;
    // ...transaction prices
}
```

**Comment by KirillDogadin-std** [comment]
surplus event though contains the initial bid. That means that in order to figure out the difference between `just-started` and `have-bids` one has to get the initial bid. That is done via the event.

Then i assume the two states here have to be merged into one state something like `live`

**Comment by valiafetisov** [comment]
Initial bid suppose to always be zero since `kick` is called via [vow.flap](https://github.com/makerdao/dss/blob/fa4f6630afb0624d04a003e920b0d71a00331d98/src/vow.sol#L151). But the proper way to distinguish between `just-started` and `have-bids` is via `bidEndDate` (tic) which [is not set during `kick`](https://github.com/makerdao/dss/blob/fa4f6630afb0624d04a003e920b0d71a00331d98/src/flap.sol#L117-L132) – this is, at least, how [the contract code is doing it](https://github.com/makerdao/dss/blob/fa4f6630afb0624d04a003e920b0d71a00331d98/src/flap.sol#L135).
