### ISSUE TITLE
Improve gas fetching

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#189]
### Goal

Better strategy for gas fetching

### Context

Currently we use a regular https endpoint to fetch fast gas price data, which is not optimal: it sometimes overloaded and down and it doesn't work with forking. Instead, we can implement support for the chainlink fast gas oracle https://data.chain.link/ethereum/mainnet/gas/fast-gas-gwei. To get current gas data we just need to fetch `latestAnswer` on [0x169e633a2d1e6c10dd91238ba11c4a708dfef37c](https://etherscan.io/address/0x169e633a2d1e6c10dd91238ba11c4a708dfef37c#readContract) or even better using `fast-gas-gwei.data.eth` handle. Potentially we can also use it with hardhat forking (instead of currently hardcoded values) to see actual historical gas data of the fork.

### Tasks
- [x] Replace gas data fetching with new logic
- [x] Optimise for [EIP-1559](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1559.md)
- [x] Remove hardcoded value for the `localhost` network
- [x] Test
