### ISSUE TITLE
Add gas-related data to the dashboard

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#198]
### Goal
Dashboard contains another small table with gas-related data

### Context
During the discussion in https://github.com/sidestream-tech/unified-auctions-ui/issues/194#issuecomment-1096318570, we realised that it's currently impossible to check that gas prices work correctly in the mainnet (or any other network) if there is no auctions. Therefore, we want to display this data in the dashboard.

The table should contain at least:
- 3 rows with `GasParameters` (`gasPrice` or `maxPriorityFeePerGas` and `maxFeePerGas` depending on the network some are expected to be undefined)
- 1 row with `baseFeePerGas`
- 3 rows with `approximateTransactionFees`

| Gas Parameter | Value in ETH | Value in DAI |
|---|---|---|
| `gasPrice` | 0.0000134 | Unknown |
| `maxPriorityFeePerGas` |  | Unknown |
| `maxFeePerGas` |  | Unknown |
| `baseFeePerGas` |  | Unknown |
| `biddingTransactionFee` |  |  |
| `authTransactionFee` |  |  |
| `restartTransactionFee` |  |  |

Please add enough decimal points to the value formatting, so it's actually visible

### Tasks
- [x] Create store action to fetch all required gas data
- [x] Add new table to the dashboard
- [ ] Test that all gas prices are correct

**Comment by valiafetisov** [comment]
A better and more technical term for `gasUsed` is `gasLimit`, at least that's what I used in our initial conversation https://github.com/sidestream-tech/unified-auctions-ui/pull/194#issuecomment-1096318570. We of course use it in our calculations of the `biddingTransactionFee`, `authTransactionFee` and `restartTransactionFee`. 

> I think we need to distinguish between swap tx and bidding tx

Yes, that can be another improvement issue. To:
- rename `biddingTransactionFee*` to `swapTransactionFee*`
- rename `totalFeeETH` to `totalSwapFeeETH` everywhere including the bot
- add new `biddingTransactionFee*` to the types and `getApproximateTransactionFees`
- display proper `total*` fee depending on the transaction type

**Comment by benediktkaiser** [comment]
> * 3 rows with `approximateTransactionFees`

In what currency do I display these? `ETH` or `DAI`? I would personally recommend `DAI` as `1 DAI = 1 USD`, however if the other fees are all in `ETH` I would tend to prefer `ETH`.

**Comment by benediktkaiser** [comment]
> > * 3 rows with `approximateTransactionFees`
> 
> In what currency do I display these? `ETH` or `DAI`? I would personally recommend `DAI` as `1 DAI = 1 USD`, however if the other fees are all in `ETH` I would tend to prefer `ETH`.

Nevermind this.
