### ISSUE TITLE
Clean up repository

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#2]
**Goal:**
Have a clean repo to work on

**Context:**
In our transition to move day to day work in open source repo as well we need to ensure a clean state of the repo and that all of the pipelines in place run smoothly

**Tasks:**
- [x] merge approved PRs from old repo -> push changes to main branch
- [x] write comment for re-submission of old PRs
- [x] check all pipelines
- [x] do clean up
