### ISSUE TITLE
Add external link to the vault explorer

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#200]
### Goal
Every auction table have a link to the vault explorer

### Context
Currently we only display field `Vault address` in the table (which may actually be vault owner?). We want to first investigate:
- What is actually the existing value that we display (owner or the vault)?
- If the auction data fetching from the clipper contains vault id?
- How can we get `vaultIndex` (or I guess it's "managed vault id") from the auction values

Then, we want to add link to the vault http://mcdstate.info/vault/27353 and maybe the link to the owner.

### Tasks
- [ ] investigate, write down the results
- [ ] extend "enreach" functions to get `vaultIndex` if needed
- [ ] add link(s) to the auction table

**Comment by benediktkaiser** [comment]
I was looking into the API offered by mcdstate. 

You can make an API call to `https://data-api.makerdao.network/v1/vaults/liquidations/auctions` along with some filters. One of these filters appears to be the `auction_id` as well as the `ilk`. I assume that these match our auction index along with the collateral ilk.
[Source](https://data-api.makerdao.network/redoc#operation/read_auctions_v1_vaults_liquidations_auctions_get)

I think that we can use this API to retrieve the ID of the auction on their website. Then we could include the link on our UI. 

Steps:

- [ ] When enriching the auction, make an API call to retrieve the mcdstate ID
- [ ] Add the mcdstate ID to the Auction Object
- [ ] Link to the ID via our UI. 

Extra:
We could also link the owners profile http://mcdstate.info/owner/0x87a67e7dc32fdc79853d780c6f516312b4a503b5

**Comment by benediktkaiser** [comment]
So I did some testing via PostMan to see if I can match our Auctions to the correct Auction IDs.

I wanted to try and fetch this auction: https://etherscan.io/tx/0x50fac62b516004c9df1ef6acbbccc98156f5472e8ca7e23f89c8033c4937e339

I made the API call with the `ilk` and `auction_id`:

![Screenshot 2022-04-14 at 07 33 21](https://user-images.githubusercontent.com/30908158/163320230-96707641-4e88-4f72-af33-43738e582217.png)

This returned the following vault id:
http://mcdstate.info/vault/27973

Conclusion:
I am able to retrieve the vault ids, however the vault owners and a bunch of other data does not match up.

@valiafetisov does this information look correct to you or will we have to see if we can find a different approach?

**Comment by benediktkaiser** [comment]
I did another one just for fun and it seems to line up pretty well.

![Screenshot 2022-04-14 at 07 38 50](https://user-images.githubusercontent.com/30908158/163320788-590482ac-6cda-4d8f-bbea-4e6747e2e651.png)
 
http://mcdstate.info/vault/22294

The dates for both of the auctions were correct, so I assume I am just looking at the wrong places for the other information. May have something to do with the fact that I am looking at the transactions on etherscan, not the actual vault.

**Comment by LukSteib** [comment]
Some assumptions / remarks:
* we are currently fetching `vaultAddress` from the auction data. This is equivalent to the `urn` key one receives in the response from the API call shown above
  * mental model for `urn`: The vaults on chain address 
* With the `auction_id` and the `ilk` type of an active action we are able to do the API request above and receive `vault` id. 
* The `vault` id (e.g. 22294) can be used to create mcdstate link to vault (e.g. http://mcdstate.info/vault/22294)
  * we can then replace the existing auction table row "vault address" change to "vault information" and provide the link there
