### ISSUE TITLE
Whitelisting collaterals

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#206]
### Goal

Keeper user is able to specify collaterals for the keeper as env variable

### Context
Currently our [keeper bot](https://github.com/sidestream-tech/unified-auctions-ui/tree/main/bot#readme) checks and tries to participate in auctions for all supported collaterals. Same with the twitter bot. Instead, we want the possibility to specify which collaterals should be "whitelisted". This however should be an optional variable and the default behaviour should stay the same.

### Tasks
- [x] introduce new env variable for the bot, eg `ETH-A, MATIC-A`
- [x] extend readme with explanation and example
- [x] parse provided value and validate it (providing `ETH-X` or `FKSALJF` should throw an error on startup)
- [x] extend logs with whitelisting status (eg `auctions: fetching only ETH-A, MATIC-A auctions`)
- [x] test bot using [our hardhat setup](https://github.com/sidestream-tech/unified-auctions-ui/tree/main/hardhat#readme)
