### ISSUE TITLE
Handle Transaction Block Change

### ISSUE THREAD

**Issue by benediktkaiser** [sidestream-tech/unified-auctions-ui#21]
### Goal
Properly handle `transaction block hash changed` error

### Context
The problem was first detected in the [Support Goerli network PR](https://github.com/sidestream-tech/auction-ui/pull/360#pullrequestreview-850618221).

Possible cause: after mining a transaction, the transaction block in was mined may change. When this happens, the loading prompt, does not disappear and stays there forever. In addition you get a console error.

```js
Uncaught (in promise) Error: transaction block hash changed
    at TransactionObject._callee$ (TransactionObject.js?8004:136:1)
    at tryCatch (runtime.js?bb97:63:1)
    at Generator.invoke [as _invoke] (runtime.js?bb97:294:1)
    at Generator.eval [as next] (runtime.js?bb97:119:1)
    at asyncGeneratorStep (asyncToGenerator.js?4033:3:1)
    at _next (asyncToGenerator.js?4033:25:1)
```

A good starting place could be around https://github.com/sidestream-tech/auction-ui/blob/main/core/src/tracker.ts#L63, as this is where we track the transactions.

In addition to that a somehow related problems was experienced after successful auction execution:
* The `Execute` button became executable again for ~10sec after successful auction execution before the auction was indicated as being finished in UI
*  No etherscan link to the tx was provided neither on transaction page nor on auction page

As indicated in this [comment](https://github.com/sidestream-tech/auction-ui/pull/360#issuecomment-1011991048) suspicion is that the problems stated above are related to `transactionManager` inside `dai.js`. 
Let's use this issue to 
a) investigate the problem further
b) start thinking about alternative approaches

### Todo

- [ ] Find the actual cause of the problem (ie where the `transaction block hash changed` is thrown in dai.js or elsewhere)
- [ ] Document the reason
- [ ] Propose a solution
- [ ] Fix the problem

**Comment by valiafetisov** [comment]
This should also be closed in #46, since we don't user transaction manager anymore
