### ISSUE TITLE
Deploy release v1.1.0

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#210]
Predecessor: sidestream-tech/unified-auctions-ui#114

**Goal:**
Deploy release v1.1.0 to production environment

**Context:**
Planned production deployment: 14.04.22 ~4pm 
Target production domain: https://auctions.makerdao.network/
Automated pipeline domain: https://unified-auctions.makerdao.com/

**Tasks:**
- [x] double-check staging environment (@benediktkaiser , @valiafetisov , @florianstoecker , @LukSteib )
- [x] greenlight the deployment (@LukSteib)
- [x] build release images via UI https://github.com/sidestream-tech/auction-ui/releases/new  (@LukSteib)
- [x] Deploy to production (@deusavalon)
- [x] Test prod environment (@LukSteib)
- [x] Share release notes in makerForum (@LukSteib)

**Comment by LukSteib** [comment]
Release images built: 
https://github.com/sidestream-tech/unified-auctions-ui/releases/tag/v1.1.0

**Comment by LukSteib** [comment]
Checked both deployments
* https://unified-auctions.makerdao.com/ ✔️
* https://auctions.makerdao.network/ ✔️ 

Release notes published: 
https://forum.makerdao.com/t/unified-auctions-ui-release-v1-1-0-april-14th-2022/14627
