### ISSUE TITLE
Release v1.2.0

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#212]
### Planned Release Scope
- Product stream 
    - [x] sidestream-tech/unified-auctions-ui#172
    - [ ] Test mass liquidation using forking or simulation with ~100 active auctions _(mass liquidation)_
    - [x] Coordinate re-direct DNS settings 
    - [x] Socument knowledge on flap auctions
-   Blockchain stream
    - [x] sidestream-tech/unified-auctions-ui#137 
    - [ ] https://github.com/sidestream-tech/unified-auctions-ui/issues/222 _(keeper, testing)_
-   Devops stream
    - [ ] https://github.com/sidestream-tech/unified-auctions-ui/issues/66
-   UI/fixes stream 
    - [ ] #150
    - [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/214 
    - [x] #206 _(keeper)_
    - [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/220 _(keeper)_
    - [ ] https://github.com/sidestream-tech/unified-auctions-ui/issues/221 _(mass liquidation)_
-   Bonus
    - [ ] Push forward https://github.com/sidestream-tech/unified-auctions-ui/issues/83 
    - [ ] https://github.com/sidestream-tech/unified-auctions-ui/issues/223
    - [ ] remove stub data to optimise container logic
    - [ ] Interlink all other UIs with our UI (open PRs to other websites / source codes) - https://github.com/sidestream-tech/unified-auctions-ui/issues/93

**Comment by valiafetisov** [comment]
I've reordered/moved issues around categories and also propose to include new issue that we can already optimise for the mass liquidation durability:
- [ ] do not (re)fetch all auctions when only one is opened

I will create an issue for it. Basic idea: when user opens a link to a single auction we shouldn't fetch all other ones until the user navigates to the main page.
