### ISSUE TITLE
Create collaterals popup

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#214]
### Goal

User is able to see authorization status on the supported collaterals, their balances in VAT and able to withdraw all collateral.

### Context

Currently, user is able to see collateral balance in VAT only if the is an active auction of this type. This means there is no option to withdraw collateral when there are no auctions and there is no option to pre-authorize it. Therefore, we want to create a new popup with this information and actions. 

### Assets

<details><summary>The mock</summary>

![MakerDAO@2x (5)](https://user-images.githubusercontent.com/3393626/163968637-9588cfae-54c5-4fa5-9acc-27d1dc6481ef.png)

</details>

### Tasks
- [x] create a `ManageCollateralTable` component and its stories according to the mock
  - [x] provide data as a single object and a new type `CollateralStatus`: `{type: string; address: string; isAuthorized: boolean; balance: BigNumber;}`
  - [x] Sort collaterals alphabetically
  - [x] Add icons like in the dashboard
  - [x] Token addresses should be clickable
  - [ ] Propose better explanations text above the table
  - [x] Make sure that if there is no authorizations, withdrawal button is disabled
  - [x] Make sure that if balance is 0, withdrawal button is disabled
- [x] create `ManageCollateralPopup` and its container (as with the wallet, fetching only should start on popup open)
- [x] add new option `Manage Collaterals in VAT` to the wallet selector dropdown
