### ISSUE TITLE
Improve keeper by running auctions synchronously

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#220]
### Goal

Keeper executes auctions one after the other, to avoid nonce errors

### Context

Currently we're executing auctions in parallel which already proved to be difficult since we have to keep track of the nonce. That said, twitter and keeper bots shouldn't depend on each other.

### Tasks

- [x] make keeper execute auctions one after the other
  - [x] make sure that twitter and keeper bots still works in parallel
- [x] test using hardhat
- [x] test using test network
