### ISSUE TITLE
Improve profitability time calculation

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#221]
### Goal

Profitability estimation use limited number of resources

### Context

Time till profitability calculation was initially implemented using a loop. That means the further the profit date, the more cycles the loop will take to compute it. Moreover, the loop is not limited, so if it's never going to be profitable, the number of loops can be quite big. Therefore, we want to reimplement this part using pure mathematical operations instead of the loop.

### Assets
Part of the code that needs to be rewritten:
https://github.com/sidestream-tech/unified-auctions-ui/blob/f2e8f318e20c28a2d469c90139ad67c0f8af2ab6/core/src/price.ts#L116-L119

### Tasks
- [x] Outline a formula here
- [x] Find and compare libraries that can help with computing it (popularity, support, package size, possibility to use/import only single function, precision, etc)
- [x] Propose a library candidate, get confirmation
- [x] Reimplement computation

**Comment by valiafetisov** [comment]
- The hint how to compute it you can find in the PR originally implementing this feature: https://github.com/sidestream-tech/unified-auctions-ui/pull/51#discussion_r791945744
- The comment from the bignumber.js creator on what library to use: https://github.com/MikeMcl/bignumber.js/issues/33#issuecomment-42579977

**Comment by benediktkaiser** [comment]
After looking into the issue I think the following function should work:

`10 * 0.95^n = 8`

Step 1: Divide by 10

`0.95^n = 8`

Step 2: Use [Decimal.log](https://mikemcl.github.io/decimal.js/#Dlog) to get `n`

`n = Decimal.log0.95(0.8)`

Does this seem logical to you @valiafetisov?

**Comment by valiafetisov** [comment]
Yeah, the first formula seems correct:
```
initial_price * price_drop^step_number = price_at_the_step_number
```

Then, we can say that `price_at_the_step_number` is `market_price` and to get `step_number`:

```
price_drop^step_number = market_price / initial_price
```
And then I think it will be something like
```
step_number = round_up( log(market_price / initial_price) / log(price_drop) )
```
According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/log#description 😅 


Note: please pay attention to the edge cases to limit resource usage. The main aim of this issue is to use less (or at least limited amount) of resources.
