### ISSUE TITLE
Repository Cleanup

### ISSUE THREAD

**Issue by zoey-kaiser** [sidestream-tech/unified-auctions-ui#226]
**Goal**
Clean up the repository by removing old components we don't need anymore.

**Tasks**

- [x] Document everything that needs to be updated in a high level overview in this issue
- [x] Remove unused components (from the old transaction flow)
- [ ] Update Storybook? @valiafetisov 

**Improve consistency in repo** 

- [ ] I noticed that some components use props with `is` as a prefix (`isLoading`) while others just use `Loading`. Do we want to go through and update them all to `isLoading`?

@valiafetisov do you have anything else we should consider?

**Comment by valiafetisov** [comment]
> Remove the Stub Data Network

It's quite a big change (also affects networks store, selectors, modals, etc) and I would suggest to do it in a separate PR for a cleaner history

> Do we want to go through and update them all to isLoading?

Yes, you can take care of all inconsistencies, including renaming props / store values.

But as refactoring is error-prone and in our current setup props are not validated via typescript, can you please keep a high-level list of the changes in the PR that makes sense to check during the functional review?

**Comment by benediktkaiser** [comment]
> It's quite a big change (also affects networks store, selectors, modals, etc) and I would suggest to do it in a separate PR for a cleaner history

That makes sense. I will remove it from this Issue and @LukSteib can make a new issue for this.

> But as refactoring is error-prone and in our current setup props are not validated via typescript, can you please keep a high-level list of the changes in the PR that makes sense to check during the functional review?

Definitely, I will begin by making a long checklist documenting everything that needs to be changed before going into the code.

**Comment by benediktkaiser** [comment]
## General Changes:
- When we first launched we had a custom `Coming soon` page. Do we want to:
  - Refactor it into a `maintenance page` or some sort of down page?
  - Remove the components, environment variable and corresponding secrets?
  - Keep it in for now
- I would split the `panels` folder into a more feature oriented pattern. I believe that the folder is becoming pretty messy, as we keep adding more panels.
- Below I purposed a new component folder structure. Is there anything else that you think needs to be addressed/changed @valiafetisov?

## Component Changes:

- [ ] Verify all components have stories and add stories for all components missing stories
- [ ] Remove unused components (see section below for logs)
- [ ] Purpose new component folder structure here
- [ ] Auction.stories is currently written in Typescript. Revert to Javascript to have it show up in our tests and be uniform with our other stories

## Components to be removed:
- `transaction/AccessDaiBlock` - unused
- `transaction/AuthorisationBlock.vue` - unused
- `transaction/DepositBlock` - unused
- `transaction/WithdrawCollateralBlock` - unused
- `ComingSoon` - depends on what we do with the `Coming Soon` page

## New component tree:
I loosely based this structure on this [blog](https://vueschool.io/articles/vuejs-tutorials/structuring-vue-components/).

- `common` -  general purpose components
  - `formatters` - any kind of component used to take in data, reformat it and then output it. Eg. FormatCurrency, FormatAddress
  - `inputs` - any kind of form elements or data selectors. Eg. BaseSwitch, Select
- `layout` -  layout components. Eg. Navbar, Footer
- `modals` - any kind of modal
- `auction` - any kind of component related to displaying a single auction or a list of auctions. Eg. Auction, AuctionTable
- `transaction` - all components related to transactions
  - `swapTransaction` - all components related to the swap transactions flow
  - `bidTransaction` - all components related to the bid flow
- `dashboard` - all components related to the dashboard page

Everything not mentioned can stay in the root folder, as we currently do not have enough components yet to justify creating a separate folder.

**Comment by valiafetisov** [comment]
> When we first launched we had a custom Coming soon page. Do we want to:

Let's keep it as is, as it's quite easy to edit it in case we ever need it. I would anyway do it in a separate PR.

> I would split the panels folder into a more feature or domain oriented pattern. I believe that the folder is becoming pretty messy, as we keep adding more panels.

I think it's getting quite messy because of the non-uniform naming (eg every surplus-related panels should have `Surplus` in its name, same for collateral-related and authorization-related). Anyway, I would not add more subfolders.

> Below I purposed a new component folder structure. Is there anything else that you think needs to be addressed/changed?

That would be my proposal:
- `common`
    - `formatters` (including `AnimatedNumber`)
    - `inputs` (including `BidInput`)
    - `other` (eg `LinkButton` or anything common, eg `Analytics`, `PrivacyView`, etc)
- `header` (eg `NetworkSelector`)
- `modals`
- `panels`
- `auctions`
  - `collateral` (please also rename all `Auction`-related components into `CollateralAuction*` components, eg `MainFlow` -> `CollateralAuctionFlow`)
  - `surplus` (including related transaction panels)
- ~~`transaction`~~ (I propose to move it to the respective `auctions/${type}` folder)
- `dashboard` - all components related to the dashboard page
- `wallet` - all components related to interacting with the wallet

> Everything not mentioned can stay in the root folder

No, let's clear the root and have no components there! There are many that would fit to the `dashboard` and the rest are for the `common/other`

> Components to be removed:

Agree

**Comment by valiafetisov** [comment]
> I noticed that some components use props with is as a prefix (isLoading) while others just use Loading. Do we want to go through and update them all to isLoading?

Sure, go ahead with that as well. My main proposal though, to push big refactoring as quickly as possible to avoid merge conflicts. If you think that there are some questionable changes or the ones that will take a lot of time, you should better do it via another PR!

**Comment by zoey-kaiser** [comment]
> Sure, go ahead with that as well. My main proposal though, to push big refactoring as quickly as possible to avoid merge conflicts. If you think that there are some questionable changes or the ones that will take a lot of time, you should better do it via another PR!

Sounds good, then I will do the renaming of individual variables in another PR. Meaning: The first PR will ONLY take care of the new folder structure and renaming components. I will then take care of fixing/improving stories, renaming variables in a second PR. Do you agree?

**Comment by zoey-kaiser** [comment]
After further investigation, I can conclude, that most components are pretty organised. I found no overlaps in naming or other major issues that I believe need to be addressed right now. 

Topics to keep an eye on in the future:

- Upgrade to Nuxt3
- Upgrading Storybook
