### ISSUE TITLE
Extend dashboard with liquidity

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#228]
### Goal

Information about available liquidity for each collateral type is shown in the dashboard collateral table

### Context

We want to add information about how much liquidity is available on the selected marketplace. This most probably would require adding a new function to each callee that will retrieve the number(s). One other problem: some (or rather most) collaterals is exchanged several times in sequence, for example, using routes in uniswap and it's not clear what should we show for them. All of the liquidity in sequence? Maximum possible liquidity?

### Tasks
- [ ] figure out what should be shown for the complex collaterals, outline
- [ ] discuss if it's actually makes sense
- [ ] write core-related functions (ie a function per callee)
- [ ] display values in the dashboard
