### ISSUE TITLE
Support multiple ways to swap collaterals

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#229]
### Goal

Some collaterals can exchanged via multiply callees / routes / etc

### Context

Currently we only support one callee per collaterals and a single route. But it may be beneficial to support several of them _at the same time_. Since #218 we technically have 2 different possible callees for some collaterals and in some market conditions that may be useful to choose which callee is more profitable. Technically we can also support not only multiply callees per collateral, but `callee + route` and `callee + route + fee` combinations. In the future we may specifically add multiply exchange platforms per collateral.

This issue is a tracking issue for this feature, since it requires different actions to be taken:
- to define what parameters can be changed
- agree on the user interface: do we provide user a possibility to switch them manually, do we precompute all options and "suggest" the best exchange, etc

This feature may be further complicated by the partial bidding which we currently don't support for swap transactions.

### Tasks
- [ ] Prioritise and scope the feature
  - possibility to switch dex
  - possibility to switch route
  - possibility to switch fee
  - possibility to change amount
- [ ] Discuss UI solutions
- [ ] Create mock
- [ ] Create further issues
