### ISSUE TITLE
Release 0.5.0

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#23]
### Planned Release Scope

- [x] Fix bugs introduced recently
    - [x] https://github.com/sidestream-tech/auction-ui/issues/329 (Ben)
    - [x] https://github.com/sidestream-tech/auction-ui/issues/332 (Valia)
        - [x] can also be done in the same PR https://github.com/sidestream-tech/auction-ui/issues/302
- [x] Finish continues deployments setup (Nils)
    - [x] https://github.com/sidestream-tech/auction-ui/pull/230
    - [x] sidestream-tech/auction-ui#334 
    - [x] sidestream-tech/auction-ui#345 
    - [x] sidestream-tech/auction-ui#353
    - [x] sidestream-tech/auction-ui#217 
    - [x] sidestream-tech/auction-ui#227
- [ ] Investigate RPC caching https://github.com/sidestream-tech/auction-ui/issues/288 (Valia)
- [ ] Support all collaterals (Ben)
    - [x] https://github.com/sidestream-tech/auction-ui/issues/328
    - [x] sidestream-tech/auction-ui#358 
    - [ ] add config for the outstanding collaterals https://github.com/sidestream-tech/auction-ui/issues/273
- [ ] Open source code base (Valia, Lukas, Nils)
   - [x] sidestream-tech/auction-ui#295 
   - [x] sidestream-tech/auction-ui#296 
   - [x]  Move all non flagged issues to unified-auctions-ui repo including comments (at the end of this sprint after the release 0.5.0)
   - [x] Push latest code changes to new repo `unified-auctions-ui` (at the end of this sprint after the release 0.5.0)
   - [ ] rename this repo from `auction-ui` to `auction-ui-private`
   - [ ] communicate changes with team 
- [x] Add bot to the list of services in the `/` page sidestream-tech/auction-ui#336 (Felix)
- [x] Internal dashboard (Felix)
   - [x] sidestream-tech/auction-ui#337 
   - [x] https://github.com/sidestream-tech/auction-ui/issues/343

---
- [ ] Bonus: Make dai.js write functions work server-side (based on sidestream-tech/unified-auctions-ui#7)
- [ ] Bonus: Finish https://github.com/sidestream-tech/auction-ui/pull/317
- [ ] Bonus: Finish https://github.com/sidestream-tech/auction-ui/issues/321
- [ ] Bonus: Support `UNIV3*` collateral types

---
### Deployment Tasks

Predecessor: sidestream-tech/auction-ui#310

- [x] double-check with @valiafetisov and @LukSteib whether release makes sense
- [x] release images via UI https://github.com/sidestream-tech/auction-ui/releases/new 
- [x] Deploy `head` to staging  _goal: 13.01. , 12:00_
    - [x] Test staging environment
    - [x] Fix bugs
- [x] Deploy staging to production _goal: 14.01. , 12:00_ 
   - [x] Test prod environment
- [x] Share release notes in makerForum _goal: 14.01
