### ISSUE TITLE
Deploy release v1.2.0

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#230]
Predecessor: sidestream-tech/unified-auctions-ui#114

**Goal:**
Deploy release v1.2.0 to production environment

**Context:**
Planned production deployment: 29.04.22 ~12:30 
Target production domain: https://auctions.makerdao.network/
Automated pipeline domain: https://unified-auctions.makerdao.com/

**Tasks:**
- [x] double-check staging environment (@valiafetisov , @florianstoecker , @LukSteib )
- [x] greenlight the deployment (@LukSteib)
- [x] build release images via UI https://github.com/sidestream-tech/auction-ui/releases/new  (@LukSteib)
~- [ ] Deploy to production (@deusavalon)~
- [x] Test prod environment (@LukSteib)
- [ ] Share release notes in makerForum (@LukSteib)

**Comment by LukSteib** [comment]
@deusavalon 
Since we finally established a redirect from `auctions.makerdao.network` to `unified-auctions.makerdao.com` and the latter will be deployed via our automated CD pipeline there is no concrete action for you to take over.
Only in case the automated deployed doesn't work out as expected. If this scenario happens, I will re-ping you. Other than that no action required anymore from your side for now.

**Comment by LukSteib** [comment]
Release tags:
https://github.com/sidestream-tech/unified-auctions-ui/releases/tag/v1.2.0

**Comment by LukSteib** [comment]
Checked `unified-auctions.makerdao.com` -> Release successful ✔️ 
Double-checked redirect from `auctions.makerdao.network` -> redirect working as expected ✔️

**Comment by LukSteib** [comment]
Release notes: https://forum.makerdao.com/t/unified-auctions-ui-release-v1-2-0-april-29th-2022/14861
