### ISSUE TITLE
Enable plausible.io for new domain

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#233]
**Goal:**
Ensure proper plausible based tracking for new domain

**Context:**
After switching to the new domain `unified-auctions.makerdao.com` we need to adjust [plausible.io](https://plausible.io/sites) settings as well. 
I have a feeling that adjustments need to be made in two places
a) the plausible dashboard itself where a new site needs to be created (no need to migrate old analytics since data is either way only kept for 30days in plausible)
b) ensure that nuxt config uses correct domain

**Tasks:**
- [ ] Create new site for `unified-auctions.makerdao.com` in plausible dashboard
- [x] check `domain` config for plausible in nuxt config
   - [x] since there set via env variable -> check correctness of env variable

**Comment by LukSteib** [comment]
>  check domain config for plausible in nuxt config

@valiafetisov can you have a look into that one

**Comment by LukSteib** [comment]
Based on the screenshot of the request payload and trying different configs via the plausible dashboard, following suspicion:
I have to setup plausible dashboard for `production.auction-ui.k8s.sidestream.tech` in order to see traffic on `unified-auctions.makerdao.com`. 
Does that sound feasible to you?

**Comment by benediktkaiser** [comment]
> Does that sound feasible to you?

It is sadly the exact opposite way around. You need to add `unified-auctions.makerdao.com` to the plausible dashboard. If you look at my screenshot, I assume the following is happening:

d = docker container name
u = public url

Plausible works through the public domain, which is why it should work if you use the domain for the auctions-ui.
