### ISSUE TITLE
Implement notification service for chainlog

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#235]
**Goal:**
We get notified when chainlog contract emits an event

**Context:**
During the offboarding of `T-USD` the `abacus` contract for this collateral type was changed right before the first liquidations were started. We recognised the change quickly, however with a notification service in place our response time might be improved even further. Additionally a notification would also help tracking the onboarding of new collateral types since it can inform when relevant contracts (e.g. `clipper`) for the new collateral are deployed. 
Given the outlined motivation we want to build a notification service. 

Relevant input:
* chainlog contract: https://etherscan.io/address/0xdA0Ab1e0017DEbCd72Be8599041a2aa3bA7e740F
* chainlog contract can emit various events: `UpdateVersion`, `UpdateAddress`, ...
* chainlog contract exists on testnets (e.g. `goerli`) 

Desired flow:
* chainlog contract emits an event
  * most relevant event: `UpdateAddress`
* we receive an email that informs about the event
  * email content informs in understandable terms about the event
  * e.g. for `UpdateAddress`: 
    * What address has been updated?
    * What is the contract name of the new address?
    * When did the update happen?
    * On which network did the event happen?

**Tasks:**
- [x] Clarify open questions to understand scope
- [x] outline implementation approach in issue
- [x] implement notification service
- [x] find a way to test

**Comment by valiafetisov** [comment]
> we receive an email that informs about the event

Also can be useful:
  * previous value

#### Config proposal

I would propose to generalize this service already a little bit, so we can subscribe to more important events in the future by driving it over a config. Not optimal, but very quick draft (maybe more suitable for the next version, but still good to keep in mind that we want to make them configurable and therefore would want to )

```js
const subscriptions = [
    {
        contract: '0xdA0Ab1e0017DEbCd72Be8599041a2aa3bA7e740F',
        eventName: 'UpdateVersion',
        generateText: (latestEvent, somethingElse) => `Text/html appearing in the email`
    }
];
const SUBSCRIBERS = [ // coming from env variable
    {
        email: 'xxx',
        subscriptions: ['subscription_id'],
    }
];
```

#### Implementation proposal

- Use websocket instead of polling!
  - using [ethers WebSocketProvider](https://docs.ethers.io/v5/api/providers/other/#WebSocketProvider)
  - or pure ws if above doesn't work: https://blog.infura.io/getting-started-with-infuras-ethereum-api/#websocket
- Fetch previous event using filters (like we do with finished auctions) _at the time of the new event_ (if previous state is needed, see suggestion above)
- No db/cache required here
- Please don't commit any email addresses but directly store them in the secrets
- You should create a separate service (please don't use `bot`) and use tsdx or something similar since we wouldn't need to share code with `core` here
- Please validate env variables on code start

**Comment by valiafetisov** [comment]
For testing you can use new `mailtrap` account

**Comment by benediktkaiser** [comment]
Note for myself:

I have implemented the web-socket listeners. 
Whenever a event is called I get the following data:

```js
{
  blockNumber: 31411612,
  blockHash: '0xf954fd822c10efcac244ebcfebe0aecac97481f991a26ebdce2548be76c3f0a3',
  transactionIndex: 0,
  removed: false,
  address: '0x4F96Fe3b7A6Cf9725f59d353F723c1bDb64CA6Aa',
  data: '0x00000000000000000000000000000000000000000000001b1ae4d6e2ef500000',
  topics: [
    '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
    '0x000000000000000000000000f5de760f2e916647fd766b4ad9e85ff943ce3a2b',
    '0x000000000000000000000000960382d4e3727483a98b66fc94d4f006bf1dab9c'
  ],
  transactionHash: '0x9e974bd84c44b797a38ec6ee14fcf6d81d64147204340da35017cb013709a08d',
  logIndex: 0,
  removeListener: [Function (anonymous)],
  getBlock: [Function (anonymous)],
  getTransaction: [Function (anonymous)],
  getTransactionReceipt: [Function (anonymous)],
  event: 'Transfer',
  eventSignature: 'Transfer(address,address,uint256)',
  decode: [Function (anonymous)],
  args: [
    '0xf5de760f2e916647fd766B4AD9E85ff943cE3A2b',
    '0x960382d4E3727483a98b66fC94d4F006BF1daB9c',
    BigNumber { _hex: '0x1b1ae4d6e2ef500000', _isBigNumber: true },
    src: '0xf5de760f2e916647fd766B4AD9E85ff943cE3A2b',
    dst: '0x960382d4E3727483a98b66fC94d4F006BF1daB9c',
    wad: BigNumber { _hex: '0x1b1ae4d6e2ef500000', _isBigNumber: true }
  ]
} 
```

**Comment by benediktkaiser** [comment]
New Feature ideas:

- [ ] File based config system
- [ ] Better parser for detecting errors in the receivers object
