### ISSUE TITLE
Implement more granular analytics

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#238]
**Goal:**
Gain better understanding of user behavior to improve overall service

**Context:**
We decided to get a better understanding of actual user behavior on our UI with the help of [heap.io](https://heap.io/). 
Decision for this service was made due to having used it in the past already and leverage the reference implementation.
Reference implementation can be found here: https://github.com/sidestream-tech/knowledge-cloud/pull/102

**Tasks:**
- [x] Implement heap.io support based on reference implementation (and documentation linked in assets section)
   - [x] as heap provides production and environment IDs check whether we are able to distinguish tracking for staging (https://main.auction-ui.k8s.sidestream.tech/collateral/?network=mainnet) and prod (https://unified-auctions.makerdao.com/)
- [x] Update readme referencing the correct env variables
- [ ] Check with @LukSteib if tracking works properly

**Assets:**
* Heap credentials can be found in bitwarden under "Heap Analytics Auction UI"
* Official heap documentation: https://developers.heap.io/docs/web
