### ISSUE TITLE
Setup deployment for the new `notification-service`

### ISSUE THREAD

**Issue by zoey-kaiser** [sidestream-tech/unified-auctions-ui#245]
### Goal
In #240 we added a new service to our project called the `notification-service`. In that PR we added a very "barebones" implementation of the CI to check the linting of the project. This issue is meant to address the deployment of this service. 

### Context
In addition to setting up the pipeline we also need to configure the following secrets: 

- [ ] INFURA_PROJECT_ID - same as on bot
- [ ] ETHERSCAN_API_KEY - can be created for free [here](https://docs.etherscan.io/getting-started/viewing-api-usage-statistics) 
- [ ] SMTP Settings - We need to have some sort of SMTP server with which we can send emails
  - [ ] SMTP_HOST
  - [ ] SMTP_PORT
  - [ ] SMTP_USERNAME
  - [ ] SMTP_PASSWORD
  - [ ] SMTP_EMAIL

### Tasks

- [ ] Add deployment steps to the project
- [ ] Configure all needed secrets + SMTP server
- [ ] Setup receivers list (who wants to recieves notification emails? See docs [here](https://github.com/sidestream-tech/unified-auctions-ui/blob/b0fef054a27a7f8381decea0dde04bb3e7289a94/notification-service/README.md#environment-variables))
