### ISSUE TITLE
Adjust `/` page

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#246]
**Goal:**
Have an up to date landing page

**Context:**
Some changes require to update the `/` page 

**Tasks:**
- [x] Change the naming of our tool in the list from `Swap collateral auctions` to `Collateral auctions portal`
   - [x] Change its description to "Web tool that supports participation in collateral auctions without capital requirements or by bidding with own Dai"
- [x] remove the "participate" button for the `Liquidation platform` list entry as this domain has a redirect to our UI in place
