### ISSUE TITLE
Improve our SEO

### ISSUE THREAD

**Issue by zoey-kaiser** [sidestream-tech/unified-auctions-ui#250]
### Goal
Improve our SEO handling to appear higher in search results and have link previews look nicer.

### Context
Recently we sent a through of our links through discord and noticed that we have empty link preview (see assets). We would like to update these to make them appear more visually appealing. This will hopefully motivate more people to click on our link, if they see it on social media sites. As this will also apply to Twitter, our timeline will hopefully also look a little bit nicer.

### Assets
![image](https://user-images.githubusercontent.com/30908158/167046819-a3fc42c3-1fba-4ecd-a384-ca59f446db38.png)

### Tasks

- [x] Purpose a method to easily add SEO to our different pages (I found this [package](https://nuxt-seo.frostbutter.com/))
- [x] Implement a easy method to generate new SEO properties in case we add new pages
- [x] Implement nicer SEO for all of our current pages
  - [x] draft descriptions for every page
  - [x] debate if we want to add images. If yes, where do we get them? @LukSteib 
- [x] Test the new link previews (I recommend using an extension such as [Social Share Preview](https://socialsharepreview.com/browser-extensions))

**Comment by valiafetisov** [comment]
Rendering different headers on different pages requires enabled SSR. It didn't worked some time ago when we first tried it due to some dependencies not being "universal", ie using browser-only APIs. You can try to do it again, since our dependencies changed over time (eg no dai.js). If it works, we can come up with title + description for each page and use built-in `head` method, no special package required: https://nuxtjs.org/docs/components-glossary/head/
