### ISSUE TITLE
Update fee displayed at the bidding transaction page

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#256]
### Goal

Correct fee displayed at the bidding transaction page

### Context

Currently, we have only one `totalFee*` fee that is displayed on both transaction pages. But actually, those transactions should have different fees displayed.

### Tasks
- [x] Please rename `totalFee*` auction key to be `combinedSwapFees*`
- [x] Please rename `bidTransactionFee*` auction key to be `swapTransactionFee*`
- [x] Please create `bidTransactionFeeETH` auction key to contain `gasPrice.multipliedBy(145438)` (should be done in `getApproximateTransactionFees`)
- [x] Please create `combinedBidFees*` which will be calculated the same way as `combinedSwapFees*` but using `bidTransactionFee*` instead of `swapTransactionFee*` (should be done in `enrichAuctionWithTransactionFees`)
- [x] Please change `BidTransactionTable` to display `combinedBidFees*`
