### ISSUE TITLE
Deploy v1.2.1

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#258]
#### Goal:
Deploy v1.2.1 that contains some fixes, adjustments and allows to shut down one of the environments

**Context:**
Reasoning for deployment out of regular release schedule: 
Important fixes and thought after UI adjustments. We don't see major risks or downsides with the in-between release.

Following PRs should be merged: 
- #253 
- #254 
- #255 
- #257
- #252 

#### Tasks
- [x] Ensure that PRs mentioned above are merged
- [x] Test staging environment
- [x] Create release images 
- [x] Test production

**Comment by LukSteib** [comment]
Release images can be found here: 
https://github.com/sidestream-tech/unified-auctions-ui/releases/tag/v1.2.1
