### ISSUE TITLE
Improve error message parsing

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#259]
### Goal
Collect error message and ensure they are parsed correctly in the future 

### Context
We encountered that not all error messages are parsed in a user friendly way in our UI, sometimes resulting in notification `Error: unknown` 

Errors from the RPC come in unstructured form: text + json in one variable.

This issue should be used to collect a list of known errors and create a story to display error message + result parsed by the helper 

### Tasks
- [x] Collect known error message (see first comment) 
- [x] create a story for `./helpers/parseMetamaskError` 
   - [x] display error message + result parsed by helper

**Comment by LukSteib** [comment]
1. Replacement fee too low

`Bidding error Error: replacement fee too low (error={"code":-32603,"message":"[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32000,\"message\":\"replacement transaction underpriced\"}}'","stack":"{\n  \"code\": -32603,\n  \"message\": \"[ethjs-query] while formatting outputs from RPC '{\\\"value\\\":{\\\"code\\\":-32000,\\\"message\\\":\\\"replacement transaction underpriced\\\"}}'\",\n  \"stack\": \"Error: [ethjs-query] while formatting outputs from RPC '{\\\"value\\\":{\\\"code\\\":-32000,\\\"message\\\":\\\"replacement transaction underpriced\\\"}}'`


2. Bidding error transaction failed

`Bidding error Error: transaction failed (transactionHash="0xa96d4a90c2b35868b7e87f5d00993187f09d77ab7eb38543c0cbb88bc6bc50e6", transaction={"hash":"0xa96d4a90c2b35868b7e87f5d00993187f09d77ab7eb38543c0cbb88bc6bc50e6","type":2,"accessList":null,"blockHash":null,"blockNumber":null,"transactionIndex":null,"confirmations":0,"from":"0xB2E1284Fb685dbDcc4378cF5d4E9515679527a42","gasPrice":{"type":"BigNumber","hex":"0xa8414a54fa"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","hex":"0xa8414a54fa"},"gasLimit":{"type":"BigNumber","hex":"0x0710ac"},"to":"0x71eb894330e8a4b96b8d6056962e7F116F50e06F","value":{"type":"BigNumber","hex":"0x00"},"nonce":25,"data":"0x81a794cb000000000000000000000000000000000000000000000000000000000000002f00000000000000000000000000000000000000000000000197138424311b81270000000000000000000000000000000000000016bff25f6a69e777f5741db6a0000000000000000000000000db9c76109d102d2a1e645dca3a7e671ebfd8e11a00000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000100000000000000000000000000b2e1284fb685dbdcc4378cf5d4e9515679527a4200000000000000000000000008638ef1a205be6762a8b935f5da9b700cf7322c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002bc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000bb86b175474e89094c44da98b954eedeac495271d0f000000000000000000000000000000000000000000","r":"0x2b0990ac5480cc92fea332a1b7bdf33a049b1bd59d0979f2e23c7bb9db0ca101","s":"0x060b3498c87aaed4894cd4146c37b3c1b0612137ea776a7dd7e9ff3ee8b968f8","v":1,"creates":null,"chainId":0}, receipt={"to":"0x71eb894330e8a4b96b8d6056962e7F116F50e06F","from":"0xB2E1284Fb685dbDcc4378cF5d4E9515679527a42","contractAddress":null,"transactionIndex":117,"gasUsed":{"type":"BigNumber","hex":"0xcac5"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","blockHash":"0xd394b46ea0ce8e44b7ffeb2ba79c0a7918df281273f43e3aefd800233af405b8","transactionHash":"0xa96d4a90c2b35868b7e87f5d00993187f09d77ab7eb38543c0cbb88bc6bc50e6","logs":[],"blockNumber":14759521,"confirmations":3,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x9cc2e5"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x4ef3c6e0ad"},"status":0,"type":2,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.4.5)`

**Comment by benediktkaiser** [comment]
I would wait to begin this PR until #201 is merged, as in that PR, we already create a helper function to display the error messages. 

In order to add this feature I would need to add a [AntDesign Message Wrapper](https://github.com/sidestream-tech/unified-auctions-ui/pull/201#discussion_r862688610) and this was already added in #201.

However, if we believe that it will take a considerable amount of time to implement #201, I could copy the changed files to a new PR.

**Comment by valiafetisov** [comment]
@LukSteib when creating issue, please don't forget to link it to the appropriate context. @benediktkaiser here is more context: https://github.com/sidestream-tech/auction-ui/issues/413#issuecomment-1123283235

In other words: you don't need to modify or extend antdv message in this issue. This issue is about improving parsing of the very specific errors thrown by metamask inside [tracker](https://github.com/sidestream-tech/unified-auctions-ui/blob/main/core/src/tracker.ts#L4). As specified in the issue description:

- [ ] you need to create a story which will use `parseMetamaskError`
  - [ ] one story for each error message (showing original message + processed message)
- [ ] you need to improve `parseMetamaskError` to better handle parsing of the mix of text + json that is thrown by metamask

The proposal to format the message: first show json error message (if any) then text message, eg `execution reverted: Clipper/not-running-auction (cannot estimate gas; transaction may fail or may require manual gas limit)`

**Comment by valiafetisov** [comment]
I will try to summarise again
### Problem
- Error message thrown by Metamask is too long
- Error message thrown by Metamask sometimes contains some json code that hard to read
- Error message thrown by Metamask is sometimes confusing, because the actual reason why error happens is within the json code `message` key, not in the beginning of the string (see `execution reverted: Clipper/not-running-auction` in the example data)

### Solution
- Write a function that takes Metamask error message and converts it into something more readable
  - Happily this function already exists in our code and called `parseMetamaskError`! So we just need to improve it to handle all messages from the above
  - To make this function functionally testable, let's create stories in which it is used: for this we collected example inputs above

### Technical details
- This is where the function is and will be used:
https://github.com/sidestream-tech/unified-auctions-ui/blob/95308890526d6c3404eefd71f80b47cb7e002863/core/src/tracker.ts#L38

- This is where the errors collected above are thrown:
https://github.com/sidestream-tech/unified-auctions-ui/blob/b0970c58b7258335f59403194821bbadd621339b/frontend/store/auctions.ts#L207

Which means: please remove `Bidding error Error:` from the examples above to get actual error message thrown by metamask.

**Comment by benediktkaiser** [comment]
I did some research into this topic and with the help of @LukSteib, I found the offical MetaMask npm package to help resolve their error messages:

https://www.npmjs.com/package/eth-rpc-errors

However, I am not sure if it is exactly what we want to implement. @valiafetisov what do you think?
