### ISSUE TITLE
Disable page refresh on network switch

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#263]
**Goal:**
We no longer refresh the whole page when switching the selected network

**Context:**
Currently there are three ways to switch the network: 
a) via the network dropdown in the header of the UI
b) via metamask extension
c) directly passing the desired network via URL parameter
In case there is a mismatch between UI and metamask a popup is shown to either adjust UI or to switch wallet. No matter which selection is made to align UI and wallet we hard refresh the whole page. 
This should be prevented in the future. 

**Tasks:**
- [ ] Prevent hard refresh of the application when switching network

**Comment by LukSteib** [comment]
@valiafetisov can you please elaborate and outline what needs to be done instead of hard refreshing when switching the network

**Comment by valiafetisov** [comment]
Sure:
- [ ] remove this line: https://github.com/sidestream-tech/unified-auctions-ui/blob/95308890526d6c3404eefd71f80b47cb7e002863/frontend/store/network.ts#L102
- [ ] make sure that all stores/states are cleared / refetched eg:
  - auctions, finished auctions, loading states, etc
  - authorizations
  - wallet (only address doesn't change) / balance
  - all other ones
  - [ ] Please make it as clean as possible, for example: you can create an action called `setup` in each store which does cleanup + refetching of related information (if there is any) and then another action inside `network` store to call all `setup`s, then you can call `network/setup` instead of the `window.location.reload`. Reasoning is that since now on, we would need to keep expanding those `setup` actions every time we add new data (or a new store)
- [ ] Extensively test switching networks and edge cases

**Comment by fegbert** [comment]
I think the `switchNetwork` method of the wallet returns before the everything is set correctly or the store is too slow. This leads to
1. the `fix network` popup opening for a small amount of time
2. the `getMakerNetwork` getter returning `undefined` for that time, which leads to errors setting up the other stores.

for example, this code:
```ts
await dispatch('setWalletNetwork', newNetwork);
await this.app.router.replace({
    path: rootState.route.path,
    query: {
        network: newNetwork,
    },
});
console.log('wallet network: ', getters.getWalletNetwork);
console.log('page network: ', getters.getPageNetwork);
console.log('maker network: ', getters.getMakerNetwork);
dispatch('setup');
```

leads to these outputs:

```
wallet network:  goerli
page network:  kovan
maker network:  undefined
```

@valiafetisov do you have an idea for a solution? 🙂

**Comment by valiafetisov** [comment]
You should use `.push` instead of `.replace`, maybe that helps?

**Comment by valiafetisov** [comment]
Also, you need to request wallet network change before changing the network, which I assume is already happening

**Comment by fegbert** [comment]
Sorry, probably should've explained this a bit more

the `window.location.reload()` is actually in the `fixWalletNetwork` action which is only called when switching via the `fix network ` popup.
The code above is actually inside the `setPageNetwork` action where I am replacing the line
```ts
window.location.href = `${rootState.route.path}?network=${newNetwork}` 
```
since it also reloads the page.


> Also, you need to request wallet network change before changing the network

Thats just calling the `setWalletNetwork` action, right? That is what calls `wallet.switchNetwork`

 I am awaiting this before switching the page network, but it still takes some time after the await for the `getWalletNetwork` getter to update to the new network.

This is what the problem currently is, since I need to wait for the getter to update, but awaiting the `setWalletNetwork` dispatch isn't long enough.

> You should use .push instead of .replace, maybe that helps?

With this both values don't update as soon as their promises are resolved 😅 

--- 

This example was switching from `goerli` to `kovan`
```
wallet network:  goerli
page network:  kovan
maker network:  undefined
``` 

So the page network switched fine, but the wallet network still needs more time although I am awaiting it

**Comment by valiafetisov** [comment]
Ohh, my mistake! [In my original comment](https://github.com/sidestream-tech/unified-auctions-ui/issues/263#issuecomment-1127499092) I meant to remove this line:
https://github.com/sidestream-tech/unified-auctions-ui/blob/95308890526d6c3404eefd71f80b47cb7e002863/frontend/store/network.ts#L85

`fixWalletNetwork` and `window.location.reload()` suppose to work without any navigation as soon as the wallet network is switched. But even that can be out of scope of this issue

**Comment by fegbert** [comment]
I did remove that line, but I still need to set the network param somewhere, so I replaced it with the nuxt router so I can set it without the page refreshing.

My problem right now is the wallet network setter.

If I call
```ts
await dispatch('setWalletNetwork', newNetwork);
...
const walletNetwork = getters.getWalletNetwork;
```
I would expect `walletNetwork` to be `newNetwork`, but for quite some time it isn't.
