### ISSUE TITLE
Enable keeper pre-authorisation for wallet and collaterals

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#264]
**Goal:**
Keeper implementation allows to pre-authorise wallet and collaterals

**Context:**
Currently the keeper is implemented in a way that once an active auction is fetched the keeper checks whether the two required authorisation steps (ie. wallet auth and collateral auth) need to be done in order to participate in the auction. 
There are two reasons that require us to change that behavior and enable the authorisation steps in advance of an active auction:
* speed of execution matters when there is a profitable auction
* authorisation tx can be timed in order to use low gas fees

With this issue we want to introduce the capability to do authorisations without the need for an active auction.

_Proposal:_
* Introduce a new env variable that allows to enable or disable pre-authorisation steps
  * if pre-authorisation is enabled on startup the wallet auth state is checked and authorised if not done yet
  * if pre-authorisation is enabled on startup the collateral auth state (! for withelisted collaterals only !) is checked and authorised if not done yet 
  * if pre-authorisation is disabled, the authorisation is only done once the keeper is about to participate in an auction (ie. current behavior) 
* Reasoning for this proposal: 
  * there should be an active way for a keeper operator to decide on authorisation since the related transactions incur fees that at this point in time are not covered by the resulting profit from an auction. Hence it needs to be a conscious decision to do the auth steps in advance with the risk of not amortsing them in the future

**Tasks:**
- [ ] Decide on implementation approach
- [ ] Implement the approach
   - [ ] adjust keeper related readme accordingly 
- [ ] Test pre-authorisation on testnet

**Comment by LukSteib** [comment]
@valiafetisov can you please give feedback on the proposal outlined above or make a more elegant counter proposal for the way to do pre-authorisation

**Comment by valiafetisov** [comment]
I agree with the proposal! Technically speaking:
- [ ] Let's make new `KEEPER_PREAUTHORIZE` to be boolean, `false` by default
  - [ ] don't forget to properly parse the string values like "FALSE" coming from the env variable
  - [ ] don't forget to update the readme
- [ ] Let's make a new ts file where this is evaluated and executed (please reuse/refactor the check+authorisation from the keeper function)
- [ ] Let's check it on setup before the loop and await for it (so auctions are not executed before auths are finished)
- [ ] Make sure is it only applied to the whitelisted collaterals (if they are provided)
