### ISSUE TITLE
Fix heap io integration

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#267]
**Goal:**
Ensure to receive user data for staging and production

**Context:**
Currently we only receive user data for development environment. 

Staging console shows the following error:
`heapIO initialization failed. Analytics are disabled`
Stack trace:
`loadAnalytics	@	5733c0d.js:1`

Production console shows the following error:
`HEAPIO_ID is not defined. Analytics are disabled`
Stack trace:
`loadAnalytics | @ | 50a2c41.js:1`

For all three environments the correct `heapio_id` is set via env variables (double checked that)

**Tasks:**
- [x] Investigate heap problems on staging and production
   - [x] document reasons in this issue
- [x] Fix potential problems

**Comment by fegbert** [comment]
> `heapIO initialization failed. Analytics are disabled`

This seems to appear when the user is on a page other than `/`.
The heap io file is located at `~/js/heapIO.js`, so for production it should look at:
```
https://unified-auctions.makerdao.com/js/HeapIO.js
```
However, for some reason it factors in the current path, so if the user is on the collateral page, it searches the file at
```
https://unified-auctions.makerdao.com/collateral/js/HeapIO.js
```
I don't know why it does this though. In local testing it works fine 🙁 

---

> `HEAPIO_ID is not defined. Analytics are disabled`

I noticed that I didn't add the `heapio_id` to the `build_args` in the `.drone.yml`. Think that should be the fix since that is the only place that differs from other env variables. My bad 🤦‍♂️
