### ISSUE TITLE
Cache profitability calculation

### ISSUE THREAD

**Issue by benediktkaiser** [sidestream-tech/unified-auctions-ui#268]
### Goal
In #249 we slightly modified the way that we calculate the profitability of an Auction. In this PR we want to refactor the code, to allow use to cache the previous values. This will hopefully save some computing time and increase performance. 

### Context
In the first version of the profitability calculation, we looped through the time it would need to reach a profitable net profit. In #221, we then switched to a logarithms based system, that calculated the time through the help of math rather than loops. The next step in our optimisation process is to cache the value. 

Currently we recalculate the time remaining based on the current date. This requires recalculation every second. In this issue we want to refactor the code to do the following:

- Determine the initial Price per collaterals (take `initialPrice` and divide it by `collateralAmount`(We need to verify that this actually works correctly))
- Determine the steps needed to reach profitability based on the marketPrice
- Add the needed time to the auction start date.
- Return this date
- In the frontend calculate the time remaining between the current date and the date returned from the function

_More infos can be found [here](https://github.com/sidestream-tech/unified-auctions-ui/pull/249#discussion_r867944183)._

### Tasks

- [ ] Verify that we can get the initial price per collateral by dividing `initialPrice` and `collateralAmount`
- [ ] Implement the new algorithm
- [ ] Compare calculation time/resources of the two systems (just for fun 😅 )
