### ISSUE TITLE
Better indicate when needs to be restarted

### ISSUE THREAD

**Issue by florianstoecker** [sidestream-tech/unified-auctions-ui#28]
**Goal**
Better indicate when an auction needs to be restarted.

**Context**
Currently, it is not that clear when an auction needs to be restarted and the columns `Market Difference` & `Auction Price` are showing _Unknown_. Let's discuss what can be done to better indicate that an auction needs to be restarted & explain the two columns showing unknown.

**Tasks**
- [x] When the auction is active/not finished, but not tradable, change `Market Difference` text from `Unknown` to `Not tradable`, but keep it gray (note that this should also be changed in the auction page)
- [x] Change `See details` button text to `Participate` when the auction is active
- [x] Change `See details` button text to `Restart auction` when the auction is inactive
- [x] Keep `See details` when the auction is finished
- [x] On the auction page: replace `Auction Price Total` with `Unknown` when the auction is inactive
   - [x] Add a tooltip(like in the screenshots below) here that says something like "Since the auction is not active, there is no total Auction Price for this auction." 
- [x] Add `Connect a Wallet` block with text above `Restart Auction` block in case no wallet is connected – so we have active call to action in the page at all times (right now there is no hint to the user why the restart button is inactive)

**Assets**
![image](https://user-images.githubusercontent.com/36764271/152138126-cd2f2692-a3bb-41ee-a87e-c55067a2b45e.png)

**Comment by benediktkaiser** [comment]
I had already completed this feature [here](https://github.com/sidestream-tech/auction-ui/pull/376).

However it was discussed (and I think agreed upon) to not implement this issue. Correct me if I am wrong @valiafetisov.

**Comment by florianstoecker** [comment]
You're right. There was miscommunication in the issue creation process. We will somehow give a better indication on when an auction needs to be restarted, but not in the way it was planned in this previous issue. I got this on my agenda and will bring it up again.

**Comment by benediktkaiser** [comment]
Okay! I will move this issue back to ToDo then!

**Comment by valiafetisov** [comment]
The point we had [in the previous discussion](https://github.com/sidestream-tech/auction-ui/pull/376): we can better inform user about two different situations:
  - a) Pair is not tradable
  - b) Auction is inactive/finished

- for `b)` we don't know what the price of that auction is right now (although we can fetch it from medianizer) so it's correct to say "Unknown".
- for `a)` it is technically an error, and we may consider showing an error `Error: The pair of "BAL/ETH...` exactly like in the dashboard, although, since it's an expected error, red colour may convey wrong message that our UI is broken, instead of stating that it's the state of the uniswap liquidity

Therefore, with other additions I suggest to:
- [ ] When the auction is active/not finished, but not tradable, change `Market Difference` text from `Unknown` to `Not tradable`, but keep it grey (note that this should also be changed in the auction page)
- [ ] Change `See details` button text to `Participate` when the auction is active
- [ ] Change `See details` button text to `Restart auction` when the auction is inactive
- [ ] Keep `See details` when the auction is finished
- [ ] On the auction page: replace `Auction Price Total` with `Unknown` when the auction is inactive
- [ ] Add `Connect a Wallet` block with text above `Restart Auction` block in case no wallet is connected – so we have active call to action in the page at all times (right now there is no hint to the user why the restart button is inactive)

**Comment by florianstoecker** [comment]
Thanks for the feedback! Few minor things to say:

> On the auction page: replace Auction Price Total with Unknown when the auction is inactive

Let's also have a tooltip(like in the screenshot below) here that says something like "Since the auction is not active, there is no total Auction Price for this auction." since I would not make sense out of only seeing "Unknown" in the column.

> right now there is no hint to the user why the restart button is inactive

There is: 
![image](https://user-images.githubusercontent.com/36764271/151925719-227fa864-185b-45f9-b46c-3a4b8ffbb8ba.png)
But nevertheless, let's include that block when a user hasn't connected yet! 

The other points are very fine with me. Like the ideas!
