### ISSUE TITLE
Weekly Scope Unified-Auctions-UI KW 22

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#280]
## Weekly Scope

The weekly scope is about all the work that should happen in this week in this project. It is the task of the project / product manager to plan this in advance. This issue can then be used to discuss and adapt scope or to retroactively check what was planned for a week.

### Tasks
- Product stream 
    - [ ] Properly setup heap analytics 
    - [ ] Check infrastructure cleanup problems
    - [ ] support conceptualisation of flap auctions (user journey)
    - [ ] Create Mock for flap auctions
-   Blockchain stream
    - [ ] #232 _(fix)_
    - [ ] https://github.com/sidestream-tech/unified-auctions-ui/issues/222 _(keeper, testing)_
    - [ ] #263
    - [ ] #188  
-   UI/others stream 
    - [ ] #150
    - [ ] #259 
    - [ ] https://github.com/sidestream-tech/unified-auctions-ui/issues/241
    - [ ] #265
-   Bonus
    - [ ] Push forward https://github.com/sidestream-tech/unified-auctions-ui/issues/83
    - [ ] #226
