### ISSUE TITLE
Implement surplus auctions logic

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#283]
### Goal

Vuex store actions to fetch surplus auctions and participate in them.

### Context

Besides collateral auctions that are already supported by the UI and the keeper, we also want to support Maker surplus auctions ([or `flap` auctions using maker terminology](https://docs.makerdao.com/smart-contract-modules/system-stabilizer-module/flap-detailed-documentation)). It is currently supported by the https://auctions.makerdao.com/flap platform ([source code](https://github.com/makerdao/auctions-ui)), but our UI should eventually support all auction types. There are other projects like [flap-auctions-api](https://github.com/makerdao/flap-auctions-api) that may implement desired functionality in other languages that can also be used for reference.

After the main investigation has been concluded in https://github.com/sidestream-tech/unified-auctions-ui/issues/188 it should be clear how to move forward.

### Tasks
- [ ] Ensure that implementation proposal is clear, ask any questions
- [ ] Implement required functions inside the `core` folder (note that some logic related to the VAT deposit / withdrawal is already implemented)
  - [ ] fetch auctions
  - [ ] execute authorization(s)
  - [ ] execute bidding
- [ ] Extend store with new states as well as new actions (suggestion: please create a separate store module, eg `surplus`)
- [ ] Provide example store commands to be called in the browser console for testing implemented functionality (in the PR description)
