### ISSUE TITLE
Move production deoployment to same kubernetes cluster as the staging deployment

### ISSUE THREAD

**Issue by BracketJohn** [sidestream-tech/unified-auctions-ui#29]
**Goal**

Move the production deployment into the same cluster as the staging deployment to reduce overhead.

**Context**

Currently, we have two separate deployments clusters:
- sidestream: our own cluster that we use for almost all of our services,
- maker: a separate cluster in a separate account that we use just for maker

This split was originally created to ensure proper billing. Now that we have `kubecost` we can see the exact spent per namespace (read: application deployment) inside the cluster, so there's no more need for the separation that causes operational overhead.

**Tasks**

- [ ] wait for https://github.com/sidestream-tech/devops/issues/85 to be resolved
- [x] add a new  deployment pipeline into our own sidestream cluster
  - [x]  listens for two hosts:
    - [x] `auctions.makerdao.network`
    - [x] `production.auction-ui.k8s.sidestream.tech`
  - [x] deploy on a "tag" event
  - [x] deploy the latest tag for now (as there last tag event was missed)
  - [x] use `localhost` secrets to not impact infura quota
- [ ] verify the deployment using https://production.auction-ui.k8s.sidestream.tech
- [ ] ask MakerDAO to point DNS records to sidestream cluster
- [ ] verify that `auctions.makerdao.network` is still reachable + stable
- [ ] remove the host production.auction-ui.k8s.sidestream.tech from the deployment

**Comment by BracketJohn** [comment]
@LukSteib can you do a test release and then checkout https://production.auction-ui.k8s.sidestream.tech?

If this works the next step is to point the ` unified-auctions.makerdao.com` domain to `a3e8b1eeee31b434e917a365fad89c15-5a625aefe5c46f96.elb.eu-central-1.amazonaws.com` and then check it out.

**Comment by LukSteib** [comment]
> @LukSteib can you do a test release and then checkout https://production.auction-ui.k8s.sidestream.tech?

* Created new release tag (see: https://github.com/sidestream-tech/unified-auctions-ui/releases/tag/v0.6.2) 
* https://production.auction-ui.k8s.sidestream.tech/ is reflecting the current state of `main` branch
-> test successful ✔️

**Comment by BracketJohn** [comment]
Nice, then let's tackle:
> If this works the next step is to point the unified-auctions.makerdao.com domain to a3e8b1eeee31b434e917a365fad89c15-5a625aefe5c46f96.elb.eu-central-1.amazonaws.com and then check it out.

**Comment by LukSteib** [comment]
> If this works the next step is to point the unified-auctions.makerdao.com domain 

Yep, can progress here only once we are in control of it. Will follow up here once this is the case
