### ISSUE TITLE
Create function to fetch auction by index

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#295]
### Goal
Fetch surplus auction information based on index

### Context
The issue is a subset of the implementation proposal you can find [here](https://github.com/sidestream-tech/unified-auctions-ui/issues/188#issuecomment-1152161469)

### Tasks
- [ ] Create new file in core `surplus.ts`
- [ ] Create function to fetch auction by index `fetchSurplusAuctionByIndex(network, index)`
    - [ ] fetch events related to the auction, filtering by its index
    - [ ] returns renamed and transformed auction with events array
    - [ ]  in case the `currentState === 'just-started'`, we should additionally fetch `flap.kicks(index)` to check that the auction was not restarted (because calling `flap.tick(index)` [resets `auctionEndDate`, but emits no events](https://github.com/makerdao/dss/blob/fa4f6630afb0624d04a003e920b0d71a00331d98/src/flap.sol#L133-L137)) – this should also be fetched after the restart transaction execution

### Assets

 Proposal:
```typescript
// NB: this is only a proposal
interface SurplusAuctionData {
    bidAmountMKR: BigNumber | undefined; // amount of MRK (bid)
    receiveAmountDAI: BigNumber; // amount of DAI to be received (lot)
    receiverAddress: string; // the address of the wallet who receives DAI (guy)
    auctionEndDate: Date; // final date when auction will end (now + `flap.tau()` – 2 days atm) (end)
    bidEndDate: Date; // (tic)
    earliestEndDate: Date; // earliest of auctionEndDate and auctionEndDate
    state: 'just-started' | 'have-bids' | 'ready-for-collection' | 'collected' | 'requires-restart'; // auction state determined from fetched events
}
interface SurplusBid extends SurplusAuctionData {
    type: 'start' | 'bid' | 'collect'; // as 'Kick', 'Tend', 'Deal'
    transactionHash: string;
    transactionDate: Date; // determined from block number (see `fetchDateByBlockNumber`)
    // other SurplusAuctionData fields
}
interface SurplusAuction extends SurplusAuctionData {
    events: SurplusEvent[];
}
```

**Comment by KirillDogadin-std** [comment]
@valiafetisov one concern has risen

as by https://github.com/sidestream-tech/unified-auctions-ui/issues/188#issuecomment-1152161469 the suggestion is have 3 types of events as in the python package that is referenced in the same comment.

The problem is that, sadly, the only event that the solidity code of the flap surplus auction emits is the `kick` event (beginning of the auction). For the generation of the other 2 events suggested, we either would have to reimplement/borrow/... the fucnctionality that has the event log parsed.

__So, the state is:__

- The event log + its analysis does not really seem feasible / make sense to implement.
	- the [python implementation](https://github.com/makerdao/flap-auctions-api/blob/04d5250e107d7c2263968e1fec39ee38d57745f6/flap_auctions/events_extractor.py#L79-L111) has the 3 events it reacts to.
	- it uses the `pymaker` package that generates the event log for you.
		- under the hood the package goes through the [blockchain log](https://github.com/makerdao/pymaker/blob/08821054d009a3b75fd83b248008002391a9c95a/pymaker/auctions.py#L476) and generates the event by [comparng signatures](https://github.com/makerdao/pymaker/blob/08821054d009a3b75fd83b248008002391a9c95a/pymaker/auctions.py#L360). 
 - The original contract only has one event [link](https://github.com/makerdao/dss/blob/fa4f6630afb0624d04a003e920b0d71a00331d98/src/flap.sol#L86)

___

queston becomes how we handle this and what exactly are the requirements of the end result. I would like to ask you to reiterate over the made suggestions (maybe +mock) and whether events are indeed needed in full.
