### ISSUE TITLE
Fetch "active" surplus auctions

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#296]
### Goal
Fetch active surplus auction information

### Context
The issue is a subset of the implementation proposal you can find [here](https://github.com/sidestream-tech/unified-auctions-ui/issues/188#issuecomment-1152161469)

Work should be done inside `surplus.ts`

### Tasks
- [ ] Create a function to fetch "active" auctions `fetchCurrentSurplusAuctions(network)`
   - [ ] gets latest `index` via `flap.kicks()`
   - [ ] gets all auctions in a loop via calling `flap.bids()` with decreasing `index` until it reaches an auction with with `end === 0`
   - [ ] executes `fetchSurplusAuctionByIndex` for each valid `index`
