### ISSUE TITLE
Subscribe to surplus auction updates

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#297]
### Goal
Update surplus auctions

### Context
The issue is a subset of the implementation proposal you can find [here](https://github.com/sidestream-tech/unified-auctions-ui/issues/188#issuecomment-1152161469)

Work should be done inside `surplus.ts`

### Tasks
- [ ] Create a function to subscribe to auction updates `subscribeToSurplusAuctions(network, callback)`
   - [ ] execute `fetchCurrentSurplusAuctions`
      - [ ] return list of auctions via `callback(auctions)`
   - [ ] subscribe via websocket to new events
      - [ ] as soon as there is new event, execute `fetchSurplusAuctionByIndex` to refetch related auction
         - [ ] return auction via `callback([auction])`
