### ISSUE TITLE
Enable surplus auction interaction

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#299]
### Goal
User is able to
* restart auction
* bid on an auction
* collect an auction

### Context
The issue is a subset of the implementation proposal you can find [here](https://github.com/sidestream-tech/unified-auctions-ui/issues/188#issuecomment-1152161469)

Work should be done inside `surplus.ts`

### Tasks
- [ ] Create a function to restart `restartSurplusAuction` (`tick`)
   - [ ] call refetch for this auction, emit `subscribeToSurplusAuctions` callback to refresh restarted auction
- [ ] Create a function to bid `bidToSurplusAuction` (`tend`)
- [ ] Create a function to collect `collectSurplusAuction` (`deal`)
