### ISSUE TITLE
Make the Table Component look more dynamic & round

### ISSUE THREAD

**Issue by florianstoecker** [sidestream-tech/unified-auctions-ui#3]
**Goal**
The appearance of the table component for the visualization of auction data is more round & dynamic.

**Context**
As of now, our table component looks simple & basic, see [here](https://auctions.makerdao.network/collateral?network=kovan). Let's customize this table a bit, so that it appears more round & dynamic. You can find a screenshot on how it should look like after this issue in the assets. We are using Ant Design for this table, you can find more information on this component [here](https://www.antdv.com/components/table/)

**Tasks**
- [ ] Look into the component documentation mentioned above
- [ ] Implement the necessary changes to the auctions' table storyboard only
- [ ] Ping @valiafetisov for a technical review & @florianstoecker for a functional review.
- [ ] Implement requested changes to the table

**Assets**
![image](https://user-images.githubusercontent.com/36764271/149137672-1a4f9f60-1059-4adf-b14d-22c8da6b9acd.png)
