### ISSUE TITLE
Create frontend `surplus` store

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#300]
### Goal
Have store for surplus auctions

### Context
The issue is a subset of the implementation proposal you can find [here](https://github.com/sidestream-tech/unified-auctions-ui/issues/188#issuecomment-1152161469)

Work should be done inside `surplus.ts`

### Tasks
- [ ] Create frontend `surplus` store
   - [ ] create new store `Record<surplusAuction.id, SurplusAuction>`
   - [ ] action to `setup`
      - [ ] set is loading
      - [ ] call `subscribeToSurplusAuctions`
      - [ ] populate auctions
   - [ ] action to reset
   - [ ] action to bid
   - [ ] action to collect
   - [ ] setup action to call all related fetching /
