### ISSUE TITLE
Implement /surplus page

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#301]
### Goal
Basic layout of surplus auction page in place

### Context
We will include the next auction type to the unified auctins UI: Surplus auctions. 
You can find an implementation plan for the whole feature here: https://github.com/sidestream-tech/unified-auctions-ui/issues/188#issuecomment-1152161469

With this issue we want to create create the basic page for interaction with surplus auctions similar but not identical to the existing `/collateral` page

### Tasks
- [ ] Create a new subpage for surplus auctions that will be available under the route `.../surplus` (see Mock below)
- [ ] Adjust existing header 
   - [ ] replace "Collateral auctions" with "Surplus Auctions"
   - [ ] logo should route to the `.../surplus` 
- [ ] use existing footer (no adjustment needed)
- [ ] Adjust existing `LandingBlock` 
   - [ ]  heading: "Surplus auctions" 
   - [ ] same buttons to show/hide explanations
- [ ] Include TextBlocks
   - [ ] "What is the Maker Protocol?" (can be re-used one to one)
   - [ ] "What are the surplus auctions?" (use lorem ipsum text for now -> text will be provided later on)
   - [ ] "Why would I participate?" (use lorem ipsum text for now -> text will be provided later on)
   - [ ] "What is the catch?" (use lorem ipsum text for now -> text will be provided later on)
- [ ] Ensure that TextBlocks can be shown/hidden with explanation toggle (similar to existing logic)

### Assets
<img src=https://user-images.githubusercontent.com/36229155/173763409-4eea8df2-22fc-440d-afcf-e6c67208b2df.png width=600>
