### ISSUE TITLE
Create `SurplusAuctionsTable`

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#302]
### Goal
User is provided with surplus auctions via dedicated table

### Context
We will include the next auction type to the unified auctins UI: Surplus auctions. 
You can find an implementation plan for the whole feature here: https://github.com/sidestream-tech/unified-auctions-ui/issues/188#issuecomment-1152161469

This issue covers the creation of the `SurplusAuctionTable`. Similar to the collateral auction table this table will later on be displayed on the main `/surplus` page

### Tasks
- [x] Create `SurplusAuctionTable` by adjusting the existing the existing `AuctionsTable`
- [x] Use the columns shown in the Mock
   - [x] Id -> integer 
   - [x] auction amount -> number in DAI
   - [x] highest bid -> number in MKR
   - [x] auction price -> number in DAI per MKR 
   - [x] market value -> percentage in relation (ie. with "above" or "below" indicator)
      - [x] twist to the mock: this time the "above" values should be marked in green
   - [x] state
      - [x] differentiate: "ends in [counter]", "expires in [counter]", "expired [counter]", "ended [counter]", "Collected [counter]"
   - [x] action column
       - [x] differentiate: "Participate", "Restart", "Collect DAI", "See details" 
       - [x] match the actions to the different states as shown in the mock 
- [x] Apply existing styling (hovering, greyed out rows if inactive)
   - [x] greyed out for the following action/states: Restart, See details 
   - [x] normal white for the following action/states: Participate, Collect DAI  
- [x] create stories 
   - [x] ensure that different states and actions are included
   - [x] include error state 
   - [x] include loading state  

### Assets
<img width="800" alt="image" src="https://user-images.githubusercontent.com/36229155/173766990-73c87374-917f-44ba-8112-1d29fe378885.png">
