### ISSUE TITLE
Create `SurplusEventsTable`

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#303]
### Goal
The user has transparency on the different activity for the auction at hand via a dedicated `SurplusEventsTable`

### Context
We will include the next auction type to the unified auctins UI: Surplus auctions. 
You can find an implementation plan for the whole feature here: https://github.com/sidestream-tech/unified-auctions-ui/issues/188#issuecomment-1152161469

This issue covers the creation of the `SurplusEventsTable`. It will later on be displayed on the auction page of one specific surplus auction. The table covers the basic events of a surplus auction. These are "start" , several "bid" events and a closing "collect" event

### Tasks
- [ ] Create the `SurplusEventsTable` (see mock below)
- [ ] Transaction column should include a clickable transaction hash that links to etherscan `https://etherscan.io/tx/[tx-hash]`
- [ ] type column -> string
- [ ] wallet -> wallet address with a clickable etherscan link `https://etherscan.io/address/[address]`
   - [ ] if the wallet address matches the wallet that is currently connected we will display "You"
- [ ] amount is empty for start and collect and contains number in MKR for the bid type entries
- [ ] When column provides counter that points back to the event  
- [ ] Create stories
   - [ ] error state in case there was a problem fetching the events
   - [ ] loading state

### Assets
`SurplusEventsTable`:
<img src=https://user-images.githubusercontent.com/36229155/173769771-099759a7-264b-490e-980e-642bbf435273.png width=750>

Broader context:
<img src=https://user-images.githubusercontent.com/36229155/173769920-0c8a31df-2d2a-48a7-932e-10e9137228c3.png width=600>
