### ISSUE TITLE
Create `SurplusAuctionTransactionTable` 

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#309]
### Goal
The user gets an overview on different transactions of one auction

### Context
We will include the next auction type to the unified auctins UI: Surplus auctions. 
You can find an implementation plan for the whole feature here: https://github.com/sidestream-tech/unified-auctions-ui/issues/188#issuecomment-1152161469

This issue covers the creation of the `SurplusAuctionTransactionTable` . It will later on be displayed on the surplus auction transaction page inside one of the panels where the user will finally place a bid.

### Tasks
- [ ] Create the `SurplusAuctionTransactionTable`  (see mock below)
- [ ] Transaction column -> include a clickable transaction hash that links to etherscan `https://etherscan.io/tx/[tx-hash]`
   - [ ] note: compared to the `SurplusAuctionEventTable` this one only displays transactions of type `bid` (no start and collect) 
- [ ] Bidder column -> wallet address as a clickable etherscan link `https://etherscan.io/address/[wallet-address]`
   - [ ] if the bidder address matches the connected wallet we also display "(you)" after the link
- [ ] Amount column -> number in MKR
- [ ] When column -> counter that points back to the moment of the bid
- [ ] Create stories
   - [ ] error state in case there was a problem fetching the events
   - [ ] loading state
   - [ ] No data state (see Mock below)

### Assets
`SurplusAuctionTransactionTable` (with transactions):
<img src=https://user-images.githubusercontent.com/36229155/174249381-50c1fb24-e763-471e-ad38-4665ebb1fc4b.png width=500>

`SurplusAuctionTransactionTable` (not data state):
<img src=https://user-images.githubusercontent.com/36229155/174249430-b87a7f9e-04b4-4eb7-b6a0-0856a695af44.png width=500>

Broader context:
<img src=https://user-images.githubusercontent.com/36229155/174249507-c2713308-0a0a-4920-b0cf-0fbd51779c85.png width=500>

**Comment by benediktkaiser** [comment]
> * [ ]  note: compared to the `SurplusAuctionEventTable` this one only displays transactions of type `bid` (no start and collect)

Looking at the issue, I believe it would not make sense to completely create a new table. I would purpose to refactor the Event Table slightly (make it say `No transactions yet` instead or `No Bids yet` (or just keeping no bids yet, as it is impossible to have an Event Table with no data (as the start event is always needed))).

Then we can just filter the events on only pass bids to this table.

**Comment by LukSteib** [comment]
Based on latest information regarding not being able to fetch history of events for an auction let's pause the work in this component for now. It is no longer part of the latest mock
