### ISSUE TITLE
Support new collateral types

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#31]
### Goal
Support new collateral types like `MATIC`, `WSTETH` and others.

### Context
- if https://github.com/sidestream-tech/auction-ui/issues/328 is implemented
  - update collateral config and test that all collaterals are tradable on uniswap
- if we don't implement https://github.com/sidestream-tech/auction-ui/issues/328
  - update dai.js version, which [was updated very recently](https://github.com/makerdao/dai.js/commit/1328fc42b7152297372f53f6e19254f7af132b04), with new collateral types
  **Note**: updating dai.js version may break kovan support as its no longer officially supported.

### Tasks 
- [x] determine full list of collateral types that needs to be added, document it here
- [x] add new collateral types to the `/constants/COLLATERALS.ts` config
- [ ] extensively test
  - [ ] create new auction types on kovan
  - [ ] test bidding for new and old auction types
  - [ ] test auth/deauth for new collateral types
  - [ ] validate that new collateral types have icons

**Comment by valiafetisov** [comment]
Final list of new collaterals that will be added (based on https://github.com/sidestream-tech/unified-auctions-ui/issues/31#issuecomment-1010744322)

- MATIC-A
- WBTC-B
- WBTC-C
