### ISSUE TITLE
Create `WalletMkrDepsoitCheckPanel`

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#310]
### Goal
The user is able to deposit MKR to the VAT if needed to make the desired bid

### Context
We will include the next auction type to the unified auctins UI: Surplus auctions. 
You can find an implementation plan for the whole feature here: https://github.com/sidestream-tech/unified-auctions-ui/issues/188#issuecomment-1152161469

This issue covers the creation of the `WalletMkrDepsoitCheckPanel` . It follows the same structure as depositing of DAI via the wallet popup that was already implemented. 

### Tasks
- [x] Create `WalletMkrDepsoitCheckPanel` (see Mock below)
- [x] Account for the different states of the panel and sub-panels
   - [x] states are similar to the depositDaiPanel that we currently use for the wallet popup (states are also covered in the Mocks below)
   - [x] apply existing rule of collapsing and expanding based on panel state
- [x] Create stories and cover the different possible panel states
   - [x] Include states seen in mock 
   - [x] include unknown state if no wallet is connected (not in mock but also needed)
 
### Assets
MKR token address (mainnet): 0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2

<details><summary>Mocks of `WalletMkrDepsoitCheckPanel`:</summary>
<p>

<img src=https://user-images.githubusercontent.com/36229155/174256898-e5476c92-2d99-4bd6-868a-1e6331ff8b25.png width=500>

<img src=https://user-images.githubusercontent.com/36229155/174256988-79bd433c-0ec1-4fec-99ca-6228a5aa7053.png width=500>

<img src=https://user-images.githubusercontent.com/36229155/174257050-d4c04105-3cb3-4155-9a3f-61faec3f477d.png width=500>

<img src=https://user-images.githubusercontent.com/36229155/174257108-dda1da68-6de3-4754-9b37-68ecd034c086.png width=500>

<img src=https://user-images.githubusercontent.com/36229155/174257258-0a99549b-463e-479f-b999-026a9222e981.png width=500>

</p>
</details>
