### ISSUE TITLE
Create `HighestBidCheckPanel`

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#312]
### Goal
The user is informed whether he is about to place the highest bid and able to actually place the bid via a dedicated panel

### Context
We will include the next auction type to the unified auctins UI: Surplus auctions. 
You can find an implementation plan for the whole feature here: https://github.com/sidestream-tech/unified-auctions-ui/issues/188#issuecomment-1152161469

This issue covers the creation of the `HighestBidCheckPanel` . Later on it will be used on the surplus transaction page and facilitate bids of the user

### Tasks
- [ ] Create `HighestBidCheckPanel` (see Mock below) 
   - [ ] Use the `SurplusTransactionsTable` component 
- [ ] Account for the different states of the panel
   - [ ] apply existing rule of collapsing and expanding based on panel state
- [ ] Create stories and cover the different possible panel states

 
### Assets
<img src=https://user-images.githubusercontent.com/36229155/174280769-13f4ed5d-c36a-4ce6-ba7f-189c09ea8531.png width=600>

**Comment by benediktkaiser** [comment]
Edge cases:

- Loading Events/Auction: If I do not have the Auction I cannot display the correct text in the button (`Bid X MKR on Y DAI`). What should I show instead? For know I just put the text `Loading...`
- The same issue is also when the component is in an error state. Meaning that the Auction failed to load

**Comment by LukSteib** [comment]
Based on recent discussions regarding the fetching of past auction events, the mock was updated and this component is affected by the change. 

Resulting in following tasks:
- [ ] Adjust the component (see Mock below) by removing the table
   - [ ] We only display "Current highest bid" with MKR figure (or hint "they were no bids yet")

Regarding the questions:
> Loading Events/Auction: If I do not have the Auction I cannot display the correct text in the button (Bid X MKR on Y DAI). What should I show instead? For know I just put the text Loading...

Fine to show "Loading..." only in this case 

> The same issue is also when the component is in an error state. Meaning that the Auction failed to load

Let's go with "Unknown" like we do for other components already in this case
