### ISSUE TITLE
Create `CollectSurplusAuctionPanel`

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#316]
### Goal
The user is can trigger the collection of an auction via a dedicated panel

### Context
We will include the next auction type to the unified auctins UI: Surplus auctions. 
You can find an implementation plan for the whole feature here: https://github.com/sidestream-tech/unified-auctions-ui/issues/188#issuecomment-1152161469

This issue covers the creation of the `CollectSurplusAuctionPanel`. Later on it will be used on the surplus transaction page and facilitate the collection of DAI. 
Context: Once an auction is finished and no more bid can be placed, it needs to be collected. In the process of collection the amount of DAI that was auctioned off is transferred to the highest bidding wallet and the MKR is burned. Collection can be triggered by every wallet and is not restricted to be done by the wallet that made the highest bid

### Tasks
- [x] Create `CollectSurplusAuctionPanel` (see Mock below) 
- [x] Account for the different states of the panel
   - [ ] apply existing rule of collapsing and expanding based on panel state
- [ ] Create stories and cover the different possible panel states

 
### Assets
<img src=https://user-images.githubusercontent.com/36229155/174772550-553eb6b4-d943-4082-895a-eeeb07f41ddf.png width=700>
