### ISSUE TITLE
Create new `SurplusAuctionRestartPanels` 

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#319]
### Goal
The user is can trigger the restart of an auction 

### Context
We will include the next auction type to the unified auctins UI: Surplus auctions. 
You can find an implementation plan for the whole feature here: https://github.com/sidestream-tech/unified-auctions-ui/issues/188#issuecomment-1152161469

This issue covers the creation of the `SurplusAuctionRestartPanels`. This is similar to the restart panel that we already have in place for the collateral auctions. Only texts need to be adjusted

### Tasks
- [x] Create `SurplusAuctionRestartPanels` (see Mock below for the restart panel that already exist)
- [x] Change text of existing restart panels (see comment 1 below) 
- [x] Account for the different states of the panel
   - [x] apply existing rule of collapsing and expanding based on panel state
- [x] Create stories and cover the different possible panel states

 
### Assets
<img width="700" alt="image" src="https://user-images.githubusercontent.com/36229155/175883490-5c955281-df8d-486f-8ff9-9100cae6f060.png">
