### ISSUE TITLE
Release 0.6.0

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#32]
### Planned Release Scope
-   Finish repository switch
    -   [ ] Rename `unified-auctions-ui` to `unified-auctions`?
    -   [ ] Rename old `auction-ui` to `unified-auctions-private`
    -   [x] https://github.com/sidestream-tech/unified-auctions-ui/pull/37
-   Product stream
    -   [x] Add link to the deployed UI to this repo title/description
    -   [x] Contact Chaoslabs
    -   [x] Follow up discussion with PE on callees https://github.com/sidestream-tech/auction-ui/issues/388
    -   [ ] Get makerdao.com domain https://github.com/sidestream-tech/auction-ui/issues/287
-   Blockchain stream
    -   [x] Discuss limitations of DAI.js in supporting new collaterals https://github.com/sidestream-tech/unified-auctions-ui/issues/34
    -   [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/44
    -   [x] #31
-   Devops stream
    -   [x] Enable drone in the public repo https://github.com/sidestream-tech/auction-ui/issues/385
        -   Restrict drone to the team members https://github.com/sidestream-tech/devops/issues/90
    -   [ ] #25
    -   [x] Investigate RPC proxy caching https://github.com/sidestream-tech/unified-auctions-ui/issues/22
-   UI/fixes stream
    -   [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/24
    -   [x] Address feedback to the previous release #39 
        -   Set default network to mainnet
        -   Improve error formatting in the dashboard
    -   [x] Add banner to staging (via frontend env variable) #41 
    -   [ ] Indicate time estimate for auction turning profitable #43 
    -   [ ] Add links to the contracts (token, clip) to the dashboard table and maybe to the auction/transaction page text
-   Bonus
    -   [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/21
    -   [ ] https://github.com/sidestream-tech/unified-auctions-ui/issues/35
    -   [ ] https://github.com/sidestream-tech/unified-auctions-ui/issues/45
    -   [ ] Support UniV3 (depends on "support new collaterals") https://github.com/sidestream-tech/unified-auctions-ui/issues/36
    -   [ ] https://github.com/sidestream-tech/unified-auctions-ui/issues/33

_Note: final scope needs to be discussed_

---

Predecessor: #23 

- [x] double-check with @valiafetisov and @LukSteib whether release makes sense
- [x] release images via UI https://github.com/sidestream-tech/auction-ui/releases/new 
- [x] Deploy staging to production _goal: 28.01. , 12:00_ 
   - [x] Test prod environment
- [x] Share release notes in makerForum _goal: 28.01

**Comment by valiafetisov** [comment]
-   Product stream
    -   [ ] Contact Chaoslabs
    -   [ ] Follow up discussion with PE on callees
    -   [ ] Get makerdao.com domain
-   Blockchain stream
    -   [ ] display finished auctions
        -   subscribe/fetch auction events (`Kick`, `Take`, `Redo`)
        -   enrich data to the minimal Auction type (as an event only contains `(index_topic_1 uint256 id, uint256 top, uint256 tab, uint256 lot, index_topic_2 address usr, index_topic_3 address kpr, uint256 coin)`)
        -   store auctions in a database
        -   fetch them on the dedicated frontend page (if the auction is not found, or always)
    -   [ ] Discuss limitations of DAI.js in supporting new collaterals
    -   [ ] Support server-side wallets (for the keeper stream)
-   Devops stream
    -   [ ] Enable drone in the public repo https://github.com/sidestream-tech/auction-ui/issues/385
        -   Restrict drone to the team members
    -   [ ] Investigate RPC proxy caching
-   UI stream
    -   [ ] Address feedback
        -   Default network
        -   Improve error formatting in the dashboard
    -   [ ] Add links to the contracts (token, clip) to the dashboard and maybe UI in general
-   Bonus
    -   [ ] Try to update DAI.js to support new collaterals
    -   [ ] Support UniV3 (depends on "support new collaterals")

Side note. Working on `auction history` is a stream on its own. Eventually it will enable us to:

-   Use cached auctions in the frontend (and therefore spend fixed amount of quota)
-   Fetch additional info for a finished auction: profit, transaction fee
-   Show table with finished auctions on the main page
-   Retweet finished auctions
-   Show analytics on the auction page (eg average market difference/profit)
-   Show analytics on the auction start tweet

**Comment by LukSteib** [comment]
>  display finished auctions

any idea on actual implementation in UI? I want to prevent showing the finished ones in the existing `auctionTable` and instead maybe provide a dedicated second table for the finished ones.

**Comment by valiafetisov** [comment]
> instead maybe provide a dedicated second table for the finished ones

Yes, that would also be my proposal: to add another table to the bottom of the main page, as part of the section where we explain "what's the catch" and show transaction fees, profit, etc. Then, newly finished auctions would also go into this separate table instead

**Comment by BracketJohn** [comment]
it would also be nice if we can move the production deployment into our main cluster in this sprint (: See a backlog issue in the "old" repo for this.

**Comment by valiafetisov** [comment]
I've create all major issues for the sprint, @LukSteib please check them and add yours. I also think that we can expend a little bit the UI stream

> it would also be nice if we can move the production deployment into our main cluster in this sprint

I've added it! Please note that https://github.com/sidestream-tech/auction-ui/issues/385 is the current priority, since no CI will block all other PRs 🙂

**Comment by valiafetisov** [comment]
> Follow up discussion with PE on callees

- Where to reliably find callee addresses? If they are not in chainlog, maybe we can have a separate repo/json file in the existing repo with the addresses for each callee?
- What is the `charterManager`? How does it affect us?
- Is there any plans to update ERC20 callee to support Uniswap v3?

**Comment by LukSteib** [comment]
Created release images:
https://github.com/sidestream-tech/unified-auctions-ui/releases/tag/v0.6.0

**Comment by BracketJohn** [comment]
> Predecessor: #23

very helpful link for me (to find the deploy command), gracie!


---

it'se deployed, but sadly the staging banner is also displayed in production:
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/25911230/151547486-d34f0320-461f-4f2b-9d7a-8af5a6b9ed35.png">

From my understanding this is due to it being set during build time:
https://github.com/sidestream-tech/unified-auctions-ui/blob/5593885f2da7a4b5302306435ff60b3d555e980d/.drone.yml#L87-L88

I've opened #71 to address this. We will need to release `v0.6.1` afterwards!

**Comment by LukSteib** [comment]
New images: 
https://github.com/sidestream-tech/unified-auctions-ui/releases/tag/v0.6.1

**Comment by BracketJohn** [comment]
Thanks! v0.6.1 is deployed and banner is gone now (for me) - ready for testing!

cc @valiafetisov and team: For the future it should be a  tell-tale sign that something is wrong when you mix secrets of two different environments for one build!

**Comment by LukSteib** [comment]
Prod testing is done and release v.0.6.1 as well ✅ 
Release notes will follow...
