### ISSUE TITLE
Weekly Scope Unified Auctions UI KW 26

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#321]
## Weekly Scope

The weekly scope is about all the work that should happen in this week in this project. It is the task of the project / product manager to plan this in advance. This issue can then be used to discuss and adapt scope or to retroactively check what was planned for a week.

### Tasks

PM
- [ ] Conduct meeting with Chaoslabs on the following topics a) access to their UI b) surplus auction testing c) testing scenario for rETH
- [ ] Reach out to PE for keeper

Development

Surplus auction (logic) stream:
- [ ] #295 
- [ ] #301 

Surplus auction (UI) stream:
- [ ] #302 
- [ ] #301 
- [ ] #310 
- [ ] #312 
- [ ] #316 
- [ ] #319 
- [ ] tbc

Keeper stream:
- [ ] #284 

End-to-end tests:
- [ ] #282 (missing part: integrate to CI)
