### ISSUE TITLE
Create `SurplusAuction` component with page

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#327]
### Goal
The user is informed about surplus auction via a dedicated SurplusAuciton page
### Context
We will include the next auction type to the unified auctins UI: Surplus auctions. 
You can find an implementation plan for the whole feature here: https://github.com/sidestream-tech/unified-auctions-ui/issues/188#issuecomment-1152161469

This issue covers the creation of the `SurplusAuction` component together with its page. 
It is very similar to the already existing `Auction` component (and page) -> please check this to get a good understanding what needs to be build.

### Tasks
- [x] Create `SurplusAuction` component and page (see Mock below)
- [x] Create a table with new values similar to the already existing table we use for `Auction` component already
- [x] Ensure that the text below the table is based on dynamic input where needed
   - [x] for `AuctionAmount`
   - [x] for `HighestBid` 
   - [x] for `AuctionPrice` 
   - [x] for `MarketDifference`
- [x] Account for a `finished` state of the auction
   - [x] This includes an alert (again similar to `Auction` component) 
   - [x] And changing the text below the table (see assets for the finished text)
   - [x] dark overlay of table
- [x] Include button 
- [x] Create stories (also for the finished state) 

 
### Assets
<img width="600" alt="image" src="https://user-images.githubusercontent.com/36229155/176649536-1d6e1ecd-7b72-4e90-ba21-0a7264be845e.png">

Finished text:
This auction was finished at {auctionEndTime} at a closing auction price of {highestbidAmount} MKR.

**Comment by zoey-kaiser** [comment]
Needed values:

- fetchedAt
- marketUnitPriceToUnitPriceRatio
- marketUnitPrice

**Comment by zoey-kaiser** [comment]
> This auction was finished at {auctionEndTime} at a closing auction price of {highestbidAmount} MKR.

As discussed in the daily today, this text will not be possible when an auction was collected. Therefore I will change the text to:

"This auction was collected"

This is also just an edge case, as we wont fetch any auctions that were collected. Therefore it would only be shown to the user who collected the auction and is on the page.
