### ISSUE TITLE
Create `SurplusAuctionTransaction` component and page

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#333]
### Goal
The user is provided with an overview on different surplus auction transaction related parameters

### Context
We will include the next auction type to the unified auctins UI: Surplus auctions. 
You can find an implementation plan for the whole feature here: https://github.com/sidestream-tech/unified-auctions-ui/issues/188#issuecomment-1152161469

This issue covers the creation of the `SurplusAuctionTransaction`. This will be the page where the user is finally able to engage in the surplus auction and place a bid

### Tasks
- [ ] Create the `SurplusAuctionTransaction` component (see mock below) and page (`BidTransaction` component can be used as a reference here)
   - [ ] since the page itself will include all of the different panels (which are not yet merged) we can also go with a plane page in the first place here and just account for the top level information
- [ ] ensure to display all keys with respective values as shown in the mock
- [ ] Implement `The Amount to Bid` as an input field
   - [ ] borrow logic from the existing input field of the `BidTransaction` component
   - [ ] default value should be set to `Lowest next bid` on default
   - [ ] throw an error when the input value is set to a value that is lower than `lowest next bid` 
   - [ ] allow for all values as input that are greater than the `lowest next bid`
- [ ] create stories 

### Assets
`SurplusAuctionTransaction`:
<img src=https://user-images.githubusercontent.com/36229155/177597174-6603a53c-f202-4a11-8853-652fc4e31d85.png width=800>
