### ISSUE TITLE
Create `MKRCheckPanel` component

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#342]
### Goal
The user is provided with a panel that checks whether enough MKR is in the wallet and whether the allowance set is high enough to place the intended bid

### Context
We were actively working on #310 to include in the MKR bidding flow for the surplus auctions. 
However, we figured along the way that actually one can directly bid from wallet without the need to deposit to `VAT` in the first place. 
This is why we need a slightly adjusted component to include in our overall flow that 
a) checks whether enough `MKR` is in connected wallet for the bid
b) checks whether allowance for `MKR` is high enough for the bid

### Tasks
- [ ] Create `MKRCheckPanel` component (see Mock below). You might be able to borrow from what we have built for #310 already 
- [ ] Create stories
   - [ ] cover the different states
      - [ ] wallet not connected
      - [ ] MKR in wallet not high enough
      - [ ] MKR allowance not high enough
      - [ ] MKR high enough and allowance high enough  

### Assets
**Note:** The text for allowance panel needs to be updated. So please go with a placeholder for now
<img src=https://user-images.githubusercontent.com/36229155/178465740-e98706f2-1344-4980-84b5-d2827d7d9dab.png width=700>
