### ISSUE TITLE
Add our `SurplusAuctionPortal` to our auctions tools list

### ISSUE THREAD

**Issue by zoey-kaiser** [sidestream-tech/unified-auctions-ui#348]
### Goal
On the start page of our web app, we have a list featuring multiple tools users can use to interact with auctions. With the release of our new SurplusAuctionPortal we want to add our own product to the list.

### Context
The list of products is defined [here](https://github.com/sidestream-tech/unified-auctions-ui/blob/main/frontend/components/UnifiedAuctionsView.vue#L75). Please add a new entry below our CollateralAuctionsPortal called "Surplus auctions portal". Link the page `/surplus` and our source code (just this repo). Ensure the filtering works correctly. 

### Tasks

- [x] Add the new entry to the list
- [x] ensure filtering works

### Questions
@LukSteib we also feature the other SurplusAuctionPortal, that we do not maintain. Do we want to continue featuring it, or should it be removed. If we decide to keep it, I would advocate to at least rename it to avoid confusion.

**Comment by LukSteib** [comment]
Following suggestion:
- [ ] Keep reference to old UI
   - [ ] rename title from "Surplus Auction Portal" to "Maker Auction (surplus)"
   - [ ] rename title from "Debt Auction Portal" to "Maker Auction (debt)" 
- [ ] take over the exact styling of the existing "Surplus Auction Portal" for the reference to our page
   - [ ] `participate` link to `.../surplus` (ie. the page @zoey-kaiser is creating)
   - [ ] `source code` link to our repo
