### ISSUE TITLE
Support server-side auth

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#35]
### Goal
Extend our `core/src/maker` init script to support server-side wallet

### Context
Currently we only support execution of read methods server-side (ie fetching auctions inside `bot-twitter`), but we want to improve it to also execute write methods (such as authorizations or bidding). This require providing a wallet information to dai.js. For an example, see [create-auctions.js#L229](https://github.com/makerdao/auction-demo-keeper/blob/bca09252af029448ff67823b0b7825ad8c6feff8/scripts/create-auctions.js#L229)

### Todo
- [x] Create dev wallet with enough ETH on a test network, add private/public key pair to secrets / bitwarden
- [x] Modify `getMaker` function (or add another one) in order to pass account info to dai.js
- [ ] Test by creating a function that checks auth (and calls it if auth is missing) inside `bot-twitter` on auction start
- [ ] Bonus: add testchain test

**Comment by benediktkaiser** [comment]
> * [ ]  Create dev wallet with enough ETH on a test network, add private/public key pair to secrets / bitwarden

I will ask Flo about this, as I think he already has a wallet we might be able to use (or he can give me some of his 300ETH :D)

**Comment by valiafetisov** [comment]
Since we no longer use dai.js, adding a private key should be done via ethers: https://docs.ethers.io/v5/api/signer/#Wallet-constructor
