### ISSUE TITLE
Investigate WalletConnect support

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#353]
### Goal
Outline on how to implement WalletConnect support

### Context
Current we support metamask only. Although this is the wallet with highest adoption so far, chances are that users would like to interact with our UI using a different wallet.
In the early days we arleady decided that WalletConnect would be a good way to go since this service constitutes a wallet aggregator on its own. So implementing support for WalletConnect would allow us to support a range of other wallets as well.

### Tasks
- [ ] Understand the current wallet implementation
- [ ] Understand WalletConnect preferred way of interaction
- [ ] Come up with a plan on how to support walletConnect and make a proposal in this issue

### Assets
WalletConnect docs: 
https://docs.walletconnect.com/

**Comment by valiafetisov** [comment]
- There is already a scaffold ready to be filled in with `WalletConnect` api calls: https://github.com/sidestream-tech/unified-auctions-ui/blob/main/frontend/lib/wallets/WalletConnect.ts
- You can get inspiration from the metamask integration https://github.com/sidestream-tech/unified-auctions-ui/blob/main/frontend/lib/wallets/MetaMask.ts

**Comment by valiafetisov** [comment]
> Through `.env` as usual

We already have `RPC_URL` env variable and don't want to extend it or provide it via another way. So my suggestion is to adapt out logic which parses `RPC_URL` into one or an array of chain ids and call/reuse it here
