### ISSUE TITLE
Sprint Scope Unified Auctions UI KW 29+30

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#356]
### Tasks

Harden surplus auctions:
- [ ] Fix input overflow
- [ ] adjust allowance check panel (in confirmed state)
- [ ] Include DAI withdrawal panel on the tx page
- [ ] make simulation work
- [ ] improve fetching behavior when switching between `/collateral` and `/surplus` 
- [ ] find a way to allow users testing the feature (stub data?, simulation?)

Investigate and fix existing problems:
- [ ] #308 
- [ ] #247 

Investigation script:
- [ ] Finish script improvements

repo cleanup:
- [ ] #226 

misc:
- [ ] #355 

conceptualisation:
- [ ] investigate flop auction logic
- [ ] investigate barking on underwater vaults

**Comment by valiafetisov** [comment]
From my point of view, the main priority of this sprint (at least blockchain-wise) should be:
- https://github.com/sidestream-tech/unified-auctions-ui/issues/232
- https://github.com/sidestream-tech/unified-auctions-ui/issues/308

since we now have a perfect (test) setup for that. I've updated the issue description with the proposals on how to approach it.

**Comment by valiafetisov** [comment]
I've created two new issues for investigation (also linked above): 
- https://github.com/sidestream-tech/unified-auctions-ui/issues/361
- https://github.com/sidestream-tech/unified-auctions-ui/issues/363
