### ISSUE TITLE
Add Dai withdrawal panel to the transaction page

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#359]
### Goal
A user is able to withdraw DAI from VAT from within the SurplusTransaction page

### Context
After the test made we know now that once the `deal()` method on a collactable auction is called, the obtained DAI is transferred to the user's VAT balance. From there it can be withdrawn. 
Hence we want to include the WithdrawDaiPanel to the TransactionPage

### Tasks

- [ ] Create WithdrawDAIPanel (for the base you might re-use the existing `WithdrawCollateralPanel`) - see Mock below
   - [ ] adjust to DAI
   - [ ] adjust the text
- [ ] Include the existing `WalletAuthorizationCheckPanel` inside the withdrawal panel
- [ ] Create stories for the different possible states
   - [ ] no DAI available in VAT
   - [ ] DAI available but authorization not given
   - [ ] DAI available and auth given 
   - [ ] missing wallet
   - [ ] Loading
   - [ ] expert mode 

### Assets
WithdrawDAIPanel including the `WalletAuthorizationCheckPanel` 
<img src=https://user-images.githubusercontent.com/36229155/179498901-fd7fca1b-8fb1-4c74-b25f-d6978395eb31.png width=400>
