### ISSUE TITLE
Support UniV3 collaterals

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#36]
### Goal
Full support of the new `UNIV3*` collaterals

### Context
Recently, `UNIV3*` collaterals were introduced, trading which on uniswap require another callee contract. 

Note: supporting new callee in general requires two _independent_ changes: 
1. Passing proper contract callee address and callee data (as in `getUniswapParametersByCollateral`)
2. Fetching and properly calculating exchange rates displayed on the frontend

Note 2: code of the other callee contracts was also updated recently and now require additional parameter to be passed, so adding support for `UNIV3*` _may_ require us to update other callees.

### Todo
- [ ] Wait till #31 is closed
- [ ] Add callee addresses to the config
  - [ ] Gather callee addresses on different networks
  - [ ] Or deploy the same callee code to the test networks as found on the main
- [ ] Fetch and calculate exchange price of the new collateral
- [ ] Test that new callee is executable on the test networks
- [ ] Bonus: Refactor `core/src/uniswap.ts` to support future callees via configuration, without significantly changing the code, ie split callee-dependent code and make it config based

**Comment by valiafetisov** [comment]
`UNIV3` collaterals are not yet supported by the maker, so we can close this issue for now
