### ISSUE TITLE
Investigate UniV3 automatic routing support

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#375]
### Goal
Make use of uni v3 automatic routing feature

### Context
For a lot of the collateral types we are supporting the uniswap v3 callee. However the routes for the token swap are not determined automatically.
Since uniswap provides an automatic routing feature this issue is meant to investigate whether/how we are able to support it and get rid of hardcoding the routes.

### Tasks
- [ ] Investigate how we might support univ3 automatic routing feature

### Assets
* docs: https://docs.uniswap.org/sdk/guides/auto-router

**Comment by valiafetisov** [comment]
Ok, the number of splits can be controlled via `maxSplits`, see [my commit here](https://github.com/sidestream-tech/unified-auctions-ui/pull/467/commits/ce84e3c01e4f14fcec1a27d86fbe8a98901d2798).

**Comment by LukSteib** [comment]
> Ok, the number of splits can be controlled via maxSplits, see [my commit here](https://github.com/sidestream-tech/unified-auctions-ui/pull/467/commits/ce84e3c01e4f14fcec1a27d86fbe8a98901d2798).

What is the final outcome of this investigation? Is there a need for us to take action?

My current interpretation:
* we can use the auto-router to determine the best possible swapping route (ie. moving away from having the hardcoded paths)
  * however we constrain the auto-router suggestion to not split routes
* we can use the auto-router proposed swapping route (e.g. WETH-USDC-DAI) to pass as calldata to exchangeCallee

**Comment by valiafetisov** [comment]
> What is the final outcome of this investigation?

Your summary is correct. It seems that we will be able to both a) get the prices and also b) pass routing information to the callee. Proposed next step is to:
- [ ] integrate `a)` into the dashboard to see if the prices or the routes differ (so it makes sense to integrate it)
- [ ] create concept and the mock to show how to integrate this functionality 
    - the question of how to work with multiply callees per collateral can be relative here (is it user-selectable?)
    - do we replace or make hardcoded routes selectable?
    - how do we display routes?
- [ ] integrate `a)` and `b)` into the actual execution flow

Proposed concept is: automatic routing can be integrated as a "separate route" where we can have 1. Uniswap v3 hardcoded route; 2. Uniswap v3 automatic route with X slippage; 3. Uniswap v3 automatic route with Y slippage. Then, we fetch all prices and propose the most profitable in the UI, but a user can still select another one manually.

Note that "multiply callees per collateral" is a bigger feature that requires a refactoring (eg logic of the keeper will change), and can technically be done before or after "automatic routing". The only reason for the proposed order is the _fallback mechanism_ that "multiply callees per collateral" provides.
