### ISSUE TITLE
Extend twitter bot to tweet about surplus auctions

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#385]
### Goal
The twitter bot informs about the start of a surplus auction

### Context
Our bot currently tweets about each new started collateral auction. 
With the support for surplus auctions that was recently introduced we also want to make sure that the bot tweets about a started surplus auction

### Tasks
- [x] make sure that collateral and surplus auctions are running in independent loops. Meaning that
  - [x] if fetching ones takes longer or throws an error, that shouldn't affect the others
  - [x] the logic for different auction types should not live in the same files
- [x] get live surplus auctions every `DEFAULT_REFETCH_INTERVAL`
- [x] determine which ones are new via `THRESHOLD_FOR_NEW_AUCTIONS`
- [x] send notification if there is a new surplus auction using the same notification logic, using the same `FRONTEND_ORIGIN` logic

### Assets
Example tweet text:
```
Surplus auction with 30000 DAI just started. Follow the link to participate:
https://auctions.makerdao.network/surplus/?network=mainnet&auction=1849
```
