### ISSUE TITLE
Adress UI related release feedback

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#39]
**Goal:**
Adjust UI to improve overall UX and reduce confusion

**Context:**
After our Release `v0.5.1` we received some feedback from the community. 
1) It was asked why certain collateral types on `/dashboard` page show an error -> this is intended and due to the fact that `kovan` network (or `goerli`) were selected and the collateral types there are not supported by uniswap. We show this on hover. We can assume that the user asking the question in the first place did not recognise that hovering over `error` will provide popup with explanation to his question. Let's change that 

2) 
We are in a phase now where there are a decent amount of auctions happening on `mainnet` and it seems that for now rather experienced and auction interested people are using our UI. Hence we decided to switch our default network for all relevant pages from `kovan` to `mainnet` 

**Tasks:**
1)
- [x] extend the error indication in the `/dashboard` table with small `...` button that makes it clear from UX perspective that one can hover to see more information
   - [x] apply same hover effect on this button as currently applied to error 

2) 
- [x] switch default network from `kovan` to `mainnet`
