### ISSUE TITLE
Finish `WalletMkrDepositCheckPanel` PR

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#393]
### Goal
Have a panel component that facilitates VAT check and depositing of requried funds 

### Context
For the surplus flow we started to work on WalletMkrDepositCheckPanel. 
Then we figured that MKR doesn't need to be deposited to the VAT in the first place. 
For the debt auction however this is needed but instead of MKR in the VAT, DAI needs to be deposited to the VAT. 
This is why we want to finish work on this component and tailor it to DAI

### Tasks
- [ ] Change `WalletMkrDepositCheckPanel` to `WalletDAIDepositCheckPanel`
- [ ] finish implementation (check wether there is much left)
- [ ] create relevant stories

### Assets
PR: https://github.com/sidestream-tech/unified-auctions-ui/pull/314

Broader picture how this should look in the debt flow:
![MakerDAO debt@2x (2)](https://user-images.githubusercontent.com/36229155/182579450-6d103d17-8c32-41af-a91c-111b2fe74581.png)
