### ISSUE TITLE
Create `DebtAuction` page

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#395]
### Goal
Debt auction page similar to the other auction types displays general information and allows a user to move on to the transaction page

### Context
We want to stick to the known UX flow for the debt auctions as well. Hence `DebtAuction` page will be required. This is a storybook only issue.
In order to understand the broader scope of the debt auctions it is recommended to look into #361 

### Tasks
- [x] Implement `DebtAuction` page
- [x] Copy as much as possible from `SurplusAuction` component
- [x] adjust the naming of the rows as indicated in the mock
- [x] ensure that price denotation now is DAI per MKR
- [x] change the explanation text
- [x] change the button copy
- [x] create same stories as for `SurplusAuction` 

### Assets
Mock:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/36229155/182629261-4af1d210-cc43-4c74-9bc6-a35dc13d1053.png">
