### ISSUE TITLE
Create `BidCheckPanel`

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#397]
### Goal
Debt auction page similar to the other auction types displays general information and allows a user to move on to the transaction page

### Context
We want to stick to the known UX flow for the debt auctions as well. While we have a `HighestBidCheckPanel` for the surplus auctions this needs to be adjusted in order to follow the logic of the debt auctions. This is what the `BidCheckPanel` will be used for
In order to understand the broader scope of the debt auctions it is recommended to look into #361

### Tasks
- [ ] Create `BidCheckPanel` (see Mocks below)
- [ ] Copy the `HighestBidCheckPanel` from surplus auctions and adjust accordingly
    - [ ] Adjust the status messages
    - [ ] Adjust the text block
    - [ ] Adjust indicator of current compensation
    - [ ] adjust button copy 

### Assets
<img src=https://user-images.githubusercontent.com/36229155/183023574-c6653bcd-40d7-4284-baab-a34875addd7f.png width=800>
