### ISSUE TITLE
Create `CollectDebtAuctionPanel`

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#399]
### Goal
Faciliate collection of MKR once the debt auction is over

### Context
Similar to surplus auction, debt auctions need to be dealt once finished.
In order to understand the broader scope of the debt auctions it is recommended to look into #361

### Tasks
- [x] Create `CollectDebtAuctionPanel` (see Mocks below)
- [x] Copy the `CollectSurplusAuctionPanel` from surplus auctions and adjust accordingly
    - [x] Change DAI to MKR
    - [x] Change button

### Assets
<img width="700" alt="image" src="https://user-images.githubusercontent.com/36229155/183380763-1d5324d1-c7a0-4681-b159-212d10c45fb4.png">
