### ISSUE TITLE
Implement price change animation for the `AuctionPrice`

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#4]
**Goal**
When the price drops, it counts down dynamically.

**Context**
When the new price for an auction is fetched, we currently just override the old price with the new one, without any animation. Now, we would like to have an animation that visualizes this price change a bit better. 
See https://makerburn.com/#/liquidations for inspiration.
<details>
  <summary>Switch between Quarter, Month, Week, Day to see the animation</summary>
  
https://user-images.githubusercontent.com/36764271/140878366-6e3e6ba9-2f4f-4783-ab0b-0d5bfca4198c.mp4

</details>

**Tasks**
- [ ] Research a library which can be used for this (or propose another solution)
  - [ ] If there are multiple, please bring up Pro & Contra
- [ ] Ping @florianstoecker for quick discussion on Slack
- [ ] Implement this component (storybook only)
