### ISSUE TITLE
Add debt auction simulation logic, test frontend and fix debt auction bugs.

### ISSUE THREAD

**Issue by KirillDogadin-std** [sidestream-tech/unified-auctions-ui#409]
### Goal

Make sure that the debt auction functionality works via allowing to test it and testing it.

### Context

There were no debt auction until now. That means that it's necessary to artificially change the state of the blockchain fork to test the application with it. After being able to initiate a fake debt auction it's necessary to make sure that the UI is capable of communicating with the debt auction contract (`Flopper`).

### Tasks

- [ ] Provide a tool that allows to start a fake debt auction on the fork
  - [ ] write a test that assures that it works.
  - [ ] write a script that is launchable so that it's possible to run it and then use frontend to see the created debt auction
- [ ] Test the debt auction participation flow
  - [ ] fix the discovered bugs.
