### ISSUE TITLE
Add staging banner

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#41]
**Goal:**
Have a permanent banner that is indicating to the user that he is currently using staging environment

**Context:**
In Release v0.5.1 we introduced automated deployments to our staging environment. (staging URL: https://main.auction-ui.k8s.sidestream.tech).
While publishing release notes we discussed whether to share staging URL publicly as it would be a cool feature for the community to check in and see changes already during our sprint. However, finally decided against it due to the fact that a user on staging can also interact with `mainnet` and hence bears the risk of loosing funds. This might be especially a problem if there a un-discovered problems on `staging`. Finally it is still a testing environment. 
In order to mitigate the risk and increase awareness for users being on staging we want to introduce a permanent banner that signals staging environment usage to the user.

**Tasks:**
- [x] Implement a banner to signal staging environment usage
   - [x] color: light red
   - [x] placement: At top of the page
   - [x] text: `This is a staging environment. Please use for testing purposes only.`
   - [x] display banner both in expert mode and explanatory mode
- [x] use frontend env variable to show banner
