### ISSUE TITLE
Weekly Scope Unified-Auctions-UI KW 33

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#411]
## Weekly Scope

The weekly scope is about all the work that should happen in this week in this project. It is the task of the project / product manager to plan this in advance. This issue can then be used to discuss and adapt scope or to retroactively check what was planned for a week.

### Tasks

- [ ] Conceptualise the barking via UI feature
   - [ ] #363 
   - [ ] Create Mock
   - [ ] Create Breakdown
- [ ] Improve the debt auction feature
   - [ ] push #408 
   - [ ] thorough testing
   - [ ] (optional): deploy hotfix release
- [ ] Push investigation of collateral onboarding 

Misc
- [ ] extend keeper with surplus auction support
- [ ] align with PE on onboarding walk through -> push rETH onboarding
