### ISSUE TITLE
Investigate `chaos-proxy`'s failure to run

### ISSUE THREAD

**Issue by aomafarag** [sidestream-tech/unified-auctions-ui#416]
### Goal

Get `chaos-proxy` up and running again.

### Context

Recently, I tried running `chaos-proxy` and ran into the following error (screenshot under Assets): `Chaoslabs API request failed with error: Request failed with status code 400`.

### Assets

```bash
aomafarag@HP-Pavilion-Notebook ~/sidestream/unified-auctions-ui/chaos-proxy (keeper-surplus)$ npm run dev

> dev
> npx ts-node src/index.ts

✔ Please select the simulation › Single Flapper
Starting simulation "[secret]"...
/home/aomafarag/sidestream/unified-auctions-ui/chaos-proxy/src/api.ts:20
        throw new Error(`Chaoslabs API request failed with error: ${error instanceof Error ? error.message : error}`);
              ^
Error: Chaoslabs API request failed with error: Request failed with status code 400
    at executeAPIrequest (/home/aomafarag/sidestream/unified-auctions-ui/chaos-proxy/src/api.ts:20:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async startSimulationInstance (/home/aomafarag/sidestream/unified-auctions-ui/chaos-proxy/src/api.ts:25:22)
    at async getSimulationUrl (/home/aomafarag/sidestream/unified-auctions-ui/chaos-proxy/src/api.ts:51:24)
    at async /home/aomafarag/sidestream/unified-auctions-ui/chaos-proxy/src/index.ts:22:23
```

### Tasks

- [ ] Investigate

**Comment by valiafetisov** [comment]
Thanks for submitting this, @aomafarag! Please next time prefer posting actual logs over the screenshot of the code. The reasons are:
- code is copy-pastable and searchable
- you can remove sensitive information from the code that is normally stored in secrets (in this case, simulation id is exposed)

**Comment by valiafetisov** [comment]
Subject-wise:
- [ ] Please check that you're using the latest values from the secrets
- [ ] Please check whether they've updated API/simulation ids https://github.com/sidestream-tech/auction-ui/issues/421#issuecomment-1168618091
  - [ ] Update simulation ids in the secrets
  - [ ] Or update the code via a separate PR

**Comment by valiafetisov** [comment]
Does the updated link works?

**Comment by valiafetisov** [comment]
Outdated, closed via https://github.com/sidestream-tech/unified-auctions-ui/pull/543
