### ISSUE TITLE
Weekly Scope [PROJECT NAME] KW [CALENDAR WEEK]

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#421]
## Weekly Scope

The weekly scope is about all the work that should happen in this week in this project. It is the task of the project / product manager to plan this in advance. This issue can then be used to discuss and adapt scope or to retroactively check what was planned for a week.

### Tasks

- [ ] Conceptualise the barking via UI feature (@zoey-kaiser , @KirillDogadin-std )
   - [ ] #363 
   - [ ] #419 
   - [ ] Create Breakdown
- [ ] Improve the debt auction feature
   - [ ] push #408 
   - [ ] #409 
- [ ] Push investigation of collateral onboarding 

Misc
- [ ] #415 
- [ ] #413
- [ ] Improve tweets (link not properly dispalyed; image not properly rendered) 

PM
- [ ] align with PE on onboarding walk through -> push rETH onboarding
- [ ] conduct sync meeting with data insights CU
