### ISSUE TITLE
Weekly Scope unified-auctions-ui KW 35

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#427]
## Weekly Scope

The weekly scope is about all the work that should happen in this week in this project. It is the task of the project / product manager to plan this in advance. This issue can then be used to discuss and adapt scope or to retroactively check what was planned for a week.

### Tasks

- [ ] Conceptualise the barking via UI feature (@zoey-kaiser , @KirillDogadin-std )
   - [ ] #363 
   - [ ] #419 
   - [ ] Create Breakdown
   - [ ] investigate vault API repository
- [ ] Push clean simulation setup
   - [ ] push #426 
- [ ] Push investigation of collateral onboarding 

Misc
- [ ] #415 
- [ ] Extend keeper to bid on debt auctions

PM
- [ ] align with PE on onboarding walk through -> push rETH onboarding
- [ ] push exchange with data insights cu on vault API
