### ISSUE TITLE
Implement indicator on when auctions turn profitable

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#43]
**Goal:**
The user is provided with an indicator on when the auction at hand is becoming profitable

**Context:**
We are already calculating and showing time till next price drop and the actual next price (done via `step` `cut` parameters). We also have the current price on Uniswap for the collateral. 
Based on this information we should be able to project when an auction is turning profitable. 
With this issue we want to add a new row to the `transaction` page that gives exactly that indicator.

**Tasks:**
- [x] Include a new row `TimeTillProfitablity` in the tables on auction page and transaction page
   - [x] include new row below existing `Market difference` row
   - [x] naming of row: `Time till profitability`
- [x] Show downwards counting timer (similar to existing `Auction Ends` timer) 
- [x] Implement logic to compute `TimeTillProfitability`
   - [x] use `step` `cut` parameters
   - [x] extrapolate price changes and calculate time till `auction price` < `price on unsiwap` for the first time
   - [x] display computed time in tables
