### ISSUE TITLE
Remove dai.js dependency for wallet connection, fee estimation, authorisation and execution

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#44]
### Goal
Do not depend on dai.js for wallet connection, fee estimation, authorisation and execution, while preserving the same functionality.

### Context
Due to the limitations outlined in https://github.com/sidestream-tech/unified-auctions-ui/issues/34#issuecomment-1015225432, we decided to move away from dai.js, or at least try to see how feasible it is for our current code base. Therefore, the plan is to reimplement most of the functionality provided by dai.js inside our `/core` folder. Reference implementation can be found in [`auction-demo-keeper/src/transact.js`](https://github.com/makerdao/auction-demo-keeper/blob/main/src/transact.js) file. Otherwise, reading [dai.js source](https://github.com/makerdao/dai.js/tree/dev/packages/dai/src/eth) should also help.

Note: auction fetching will be reimplemented in another issue.

### Tasks
- [x] Reimplement fee estimation
- [x] Reimplement wallet connection
- [x] Reimplement authorisation and bidding execution, transaction tracking
- [x] Extensively test to validate that existing functionality is not affected by this refactoring
