### ISSUE TITLE
Create `AnimatedArrow` component

### ISSUE THREAD

**Issue by zoey-kaiser** [sidestream-tech/unified-auctions-ui#441]
### Goal
In our new Vaults flow, we require an arrow, from which we can change the direction. Similarly to the `AnimatedNumber` component, we want to show a small animation when a user is viewing a page and the arrow changes direction. Therefore we want to have a arrow component, that shows an arrow that receives the property "direction". This can be "up", "right", "down" or "left". This value can change during the lifecycle of the arrow and when it does, the arrow should spin into the correct alignment. Please also take different sizing options into account.

### Context
In order to properly add the arrow we will first need to find a suitable arrow icon. You can find a free SVG icon (with a commercial license) that we are allowed to use. Once deciding on one design please use a [SVG Cleaner](https://jakearchibald.github.io/svgomg/) to remove any unneeded meta tags. Then you can import the arrow into the project.

### Tasks

- [x] Decide on an Arrow Icon to use inside of the project
- [x] Implement the new `AnimatedArrow` component
- [x] Add stories for all directions and an example in which the arrows direction is changed periodically
