### ISSUE TITLE
Extend `Explain` component to work with icons

### ISSUE THREAD

**Issue by zoey-kaiser** [sidestream-tech/unified-auctions-ui#442]
### Goal
In our new `vault` flow we are looking to introduce a new kind of explain component. Rather then hovering over a certain piece of text, we want to display a small info icon (just a "I" surrounded by a circle), over which the user can hover to receive more information.

### Context
In order to implement this you can either extend the current `Explain` component or you can create a new component. The key differences between the current `Explain` component and this new one are as follows:
- It uses an icon instead of text
- It does not have a different coloured background or font

It is up to you to decide in which way you would like to implement it. However please take into account that we will need to line it up with other text blocks, therefore it should be able to match the font size and orientation of the text we use. 

### Tasks

- [ ] Propose a way to add the new component
- [ ] Create the new component (or extend the explain component)
- [ ] Add (or modify) stories

**Comment by valiafetisov** [comment]
> In our new vault flow we are looking to introduce a new kind of explain component. Rather then hovering over a certain piece of text, we want to display a small info icon (just a "I" surrounded by a circle), over which the user can hover to receive more information.

I actually think that we should avoid using `i` icons and instead incorporate explainers directly to the text. So my proposal is to adjust the design, not the component

**Comment by zoey-kaiser** [comment]
> I actually think that we should avoid using `i` icons and instead incorporate explainers directly to the text. So my proposal is to adjust the design, not the component

Okay! I had seen you use them when you modified the mock, so I thought this was the right idea. Do we want to close this issue and I will think of more ideas until Monday? I currently have no ideas, so if you have any it would be great if you could list them under #419! Thank you 🤗

**Comment by valiafetisov** [comment]
Yes, sorry for the confusion, this suggestion came from the https://github.com/sidestream-tech/unified-auctions-ui/issues/419#issuecomment-1231937953, where I already proposed to explain each number individually rather than everything together. This can be applied to the other places as well: wherever there is an `i` icon, let's instead apply `Explain` to the actual word/phrase we intend to explain
