### ISSUE TITLE
Improve the flow to start auctions

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#443]
### Goal
Extend the flow to start collateral auctions with possibility to call `drip` and `poke` via the UI.

### Context
During our investigation of the functionality to start auctions (see: #363) we figured that `drip` and `poke` are two un-protected functions that both directly impact the state of a vault. 
In the future we want to offer users the possibility to call these two functions via our UI. This will improve the overall UX to liquidate a given vault.

The related issue for the first iteration of the mock can be found here: #419 

### Tasks

- [ ] Reference the functionality of `drip` and `poke` in the issue
- [ ] Extend the mock accordingly
- [ ] Outline implementation approach to add desired functionality
