### ISSUE TITLE
Weekly Scope Unified-Auctions-ui KW 36

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#445]
### Tasks

- [ ] Finish the v1 of the "simulation suite" (release relevant)
   - [ ] related PR: #426 
- [ ] Extend keeper functionality to work with debt auctions (release relevant)
   - [ ] related PR: #430 
- [ ] #433 (release relevant)
   - [ ] #434 
   - [ ] #435 
   - [ ] #436 
   - [ ] #437 
   - [ ] #439 
   - [ ] #440 
- [ ] Start implementation of the vault logic
   - [ ] Conclude the discussion in #363 with clear actionables and a way to proceed
   - [ ] (Ongoing) Update implementation stream with information from DICU (see https://github.com/sidestream-tech/auction-ui/issues/433#issuecomment-1235232969)

Optional:
- [ ] Push exchange with PE on Keeper and collateral onboarding topics

### Alternative Scenario
Input in case we are blocked on the vault logic implementation stream:
- [ ] Extend the simulation suite by surplus auction simulation

**Comment by valiafetisov** [comment]
Bonus point: 
- https://github.com/sidestream-tech/unified-auctions-ui/issues/450

**Comment by valiafetisov** [comment]
Main features released this week:
- https://github.com/sidestream-tech/unified-auctions-ui/pull/426
   - This adds a developer friendly CLI interface to test different types of auctions in a simulated environment, step by step
   - It is part of the core functionality, so it can be used to test both frontend, bot as well as external tools that interact with maker protocol
   - We plan to expand it with more simulations in the future (and replace those which were provided by chaoslabs)
- https://github.com/sidestream-tech/unified-auctions-ui/pull/430
   - The keeper was extended to participate in the debt auctions
   - It is of course optional and the keeper user can decide in which auction types to participate and which collaterals to whitelist
- We started the development of the vault liquidation feature: added types, working on the components and the new service which will collect information about active vaults

**Comment by valiafetisov** [comment]
<img width="689" alt="Screenshot 2022-09-08 at 16 44 12" src="https://user-images.githubusercontent.com/3393626/189152517-bea31b96-db7c-49d1-8b3d-a218be96b2bb.png">
