### ISSUE TITLE
Write keeper algorithm

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#45]
### Goal
A single function which executes appropriate transaction or voids.

### Context
Since we want to enable our code to automatically participate in the auctions, we want to make the "keeper algorithm": a function which determines if an auction is worth participating and execute the appropriate transaction. This function should receive an `Auction`/`Auction.id` and a `minimum profit` (amount in DAI) as input. It should then first check if current wallet already have appropriate authorizations, and depending on that, compute final profit. If the transaction is potentially profitable, it should execute authorization and then potentially restart itself with the fresh auction data.

Important implementation considerations:
- Fee estimation is currently done inside the store, therefore it needs to be refactored to the `/core` folder and use `memoizee` as a caching solution instead of the store
- Since transaction execution takes significant amount of time, we need to expect that this function will be called again, during the execution of the same parameters. Therefore:
  - While an auction is passing through the function, calling the function again with the same auction should not trigger the same transaction (so we probably need to keep pool of transactions that are currently executed, and if they called again we can return the same promise)
  - After one transaction is executed (eg authorization) the auction may already be finished, therefore the keeper function can not continue executing itself with the same parameters, but should restart with the fresh data

### Tasks
- [x] Move fee estimation, profitability calculation to `/core`
- [x] Implement keeper
  - [x] Fetch auction prices, market prices
  - [x] Fetch auth status
  - [x] Deduct auth fees from the outcome
  - [x] Check outcome/profit against some threshold, configurable via env variable
  - [x] Execute authorisations if needed
  - [x] Check outcome/profit again after each authorisation (cause auction may not exist already)
  - [x] Execute bidding
- [x] Check that it works on some test auctions
- [ ] Bonus: add end-to-end tests
