### ISSUE TITLE
Fix surplus-related minor issues

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#450]
### Goal

Test surplus participation using simulation, document and fix related problems

### Context

After the new surplus simulation was implemented in https://github.com/sidestream-tech/unified-auctions-ui/pull/449, we're discovered few issues already documented [in the comment there](https://github.com/sidestream-tech/unified-auctions-ui/pull/449#issuecomment-1239647134). Now we want to test it further and fix related problems.

### Tasks

- [ ] Test surplus participation via the UI using new simulation
- [ ] Test surplus participation via the bot using new simulation
- [ ] Please pay attention to various edge cases (eg testing participation if user is the latest bidder and if not the latest bidder)
- [ ] Document found problems, add them in the comments here
- [ ] Fix found issues, inclusing
  - [x] Fix uniswap price fetching when there is no bids
  - [x] Set `nextMinimumBid` to make sense (eg a uniswap price * gap to reach 1k net profit)
  - [x] `SurplusAuctionBidTransactionTable` "state" should display state, not just date
  - [x] `SurplusAuctionBidTransactionTable` end state should count down, but count up (ie Ended 2s ago, 3s ago, etc. First guess: can be caused by invalid determination of the `earliestEndDate`)

**Comment by zoey-kaiser** [comment]
I tried to start the single flapper simulation but it failed with the following error:

```sh
/Users/zoey/Documents/Development/SideStream/unified-auctions-ui/chaos-proxy/src/api.ts:20
        throw new Error(`Chaoslabs API request failed with error: ${error instanceof Error ? error.message : error}`);
              ^
Error: Chaoslabs API request failed with error: Request failed with status code 400
    at executeAPIrequest (/Users/zoey/Documents/Development/SideStream/unified-auctions-ui/chaos-proxy/src/api.ts:20:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async startSimulationInstance (/Users/zoey/Documents/Development/SideStream/unified-auctions-ui/chaos-proxy/src/api.ts:25:22)
    at async getSimulationUrl (/Users/zoey/Documents/Development/SideStream/unified-auctions-ui/chaos-proxy/src/api.ts:51:24)
    at async /Users/zoey/Documents/Development/SideStream/unified-auctions-ui/chaos-proxy/src/index.ts:22:23
```

**Comment by zoey-kaiser** [comment]
> * [ ]  `SurplusAuctionBidTransactionTable` "state" should display state, not just date

I do not understand this point. Currently the table state either displays:

- Expires in about 20 hours ago
- Collectable since about 2 hours ago
- Requires Restart
- Collected

A user can see if there are bids yet or not in the `Highest Bid` column, therefore I do not see the purpose in adding this information into the state column as well.

> * `SurplusAuctionBidTransactionTable` end state should count down, but count up (ie Ended 2s ago, 3s ago, etc. First guess: can be caused by invalid determination of the `earliestEndDate`)

I cannot test this as the simulation does not work properly.

**Comment by valiafetisov** [comment]
> I do not understand this point. Currently the table state either displays:
> 
> * Expires in about 20 hours ago
> * Collectable since about 2 hours ago
> * Requires Restart
> * Collected

The transaction table haven't showed this kind of thing, only the auction table. See the changes proposed in this PR to understand the difference. https://github.com/sidestream-tech/unified-auctions-ui/pull/451/files
I would actually create a separate small component to not repeat the same code to determine the state twice.

> I cannot test this as the simulation does not work properly

What exactly doesn't work with the simulation?

**Comment by valiafetisov** [comment]
The problem is related to the `hardhat-silent` command. `1>&/dev/null` is there to output stdout into /dev/null in order to not print hardhat logs into the console https://github.com/sidestream-tech/unified-auctions-ui/blob/be5f7f652b2dec805490afe8105c09cc3ecf96d6/core/package.json#L12

The quick fix would be to _temporary_ replace `1>&/dev/null` with `> /dev/null` or `&> /dev/null` (according to [this article](https://www.baeldung.com/linux/silencing-bash-output))
The proper fix would be to google for a command that works in all shells
