### ISSUE TITLE
Weekly Scope Unified-Auctions-UI KW 37

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#459]
### Tasks
- [ ] #433 (release relevant)
   - [ ] #434 
   - [ ] #435 
   - [ ] #436 
   - [ ] #437 
   - [ ] #439 
   - [ ] #440 
- [ ] https://github.com/sidestream-tech/unified-auctions-ui/issues/450
- [ ] Implement vault logic (release relevant)
   - [ ] (Ongoing) Update implementation stream with information from DICU (see https://github.com/sidestream-tech/auction-ui/issues/433#issuecomment-1235232969)
- [ ] Push communication with PE
  - [ ] on rETH onboarding topic
  - [ ] #375 
  - [ ] #373 

### Bonus
- [ ] https://github.com/sidestream-tech/unified-auctions-ui/issues/443
