### ISSUE TITLE
Implement vault liquidation service

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#466]
### Goal

PM is able to start a service, understand when its update is complete and fetch list of vaults at risk

### Context

After the conclusion of the related investigation issue, where the [implementation proposal was outlined](https://github.com/sidestream-tech/unified-auctions-ui/issues/363#issuecomment-1234396013), and [implementation of the core logic](https://github.com/sidestream-tech/unified-auctions-ui/issues/460) we need to implement the _backend service_ that keeps track of the vaults and determines which of them are at risk. Please use this issue to discuss implementation details.

### Assets

- Implementation proposal https://github.com/sidestream-tech/unified-auctions-ui/issues/363#issuecomment-1234396013
- Core functionality https://github.com/sidestream-tech/unified-auctions-ui/pull/457
- Discussion with the DICU https://github.com/sidestream-tech/auction-ui/issues/433#issuecomment-1235232969
- Related TS types https://github.com/sidestream-tech/unified-auctions-ui/blob/main/core/src/types.ts#L270-L333

### Tasks

- [ ] Use DICU endpoint to fetch list of active vaults
- [ ] Enrich this data with latest vault data
- [ ] Keep our own cache in a database
- [ ] Provide endpoint to fetch vaults at risk
- [ ] Provide endpoint to fetch DB dump
- [ ] Provide docker-compose or other ways to start both frontend and the service
- [ ] Provide store functionality to fetch and refetch vaults at risk
- [ ] Provide service readme with the list of env vars, start commands, etc
- [ ] Update main readme to outline new service
- [ ] Ensure that this feature doesn't affect the ability to use frontend independently (when no service is running)
- [ ] ? Update CI/CD to build and deploy new service (can be done in another PR)

**Comment by KirillDogadin-std** [comment]
I would suggest (since this was not mentioned before) to use `express` api in this case over more "advanced"/newer options such as [Ts.ED](https://tsed.io/docs/providers.html#dependency-injection) since:

  - it won't (likely) require a lot of time to set up and figure out to how to get to it since afaik at least 50% of the team members have seen it already
  - the api is not of an advanced kind and the currenly required features are very scoped. 
    - There're 2 endpoints, so this is small replacement effort if we will want to scale api with a more modern framework.

>  ? Update CI/CD to build and deploy new service (can be done in another PR)

I would suggest extracting this into another PR

> Ensure that this feature doesn't affect the ability to use frontend independently (when no service is running)

the frontend should nevertheless have missing functionality - right? (the vaults table will not be populated)

____

what about the functionality to continiously keep the database up-to-date? Is it going to be a different issue's scope?

**Comment by valiafetisov** [comment]
I would suggest to use [`h3`](https://www.npmjs.com/package/h3) instead of express since it is used under the hood in nuxt3 (which we might migrate this project as well in the future). It is very similar to express, so you should have no problem to get started.

I would also suggest to use `zod` the same way we use it in https://github.com/sidestream-tech/sidebase-libs/tree/main/packages/nuxt-sidebase-parse

What would you suggest to use to build/package and develop it with? [tsup](https://github.com/egoist/tsup)? Something better that uses `vite` under the hood?

> what about the functionality to continiously keep the database up-to-date? Is it going to be a different issue's scope?

It's expected to be covered by this issue.

> the frontend should nevertheless have missing functionality

I guess frontend integration can be moved to yet another issue. General idea: if endpoints are down, the frontend should have missing functionality, but not broken state. For example, if started locally (via isDev kind-of check) frontend can signal that the service is not running. In production it should say that endpoints are down and that specific vault ids can be used to liquidate them + point user to some other UI/way to get vaults at risk.

**Comment by KirillDogadin-std** [comment]
- have nothing against using h3 except for narrow documentation.
- zod approach seems solid
- we can use `tsup` since it does not require a config and also has proven to be useful in the other company's projects
  - i did not discover a package that is powered vite within ~15 mins

No further questions about the rest of the topics.

**Comment by valiafetisov** [comment]
> Should i propose the service structure in more detail

If you have any questions / unsure about structure or already have it in the notes and want to document it. For me the general structure doesn't raise any questions, I'm only unsure about enrichment and when/how it is triggered. Compared to the events that we could've subscribe to, now we would now need to refetch it periodically or parse every block (depending on what takes less resources). What's the approach here?

**Comment by KirillDogadin-std** [comment]
> What's the approach here?

Important terminology: in the answer for this q:
  - _events_ - general term
  - `events` - technical blockchain term

General scope: 

1. Determine the frequency we want to update our db with ( i would say each 12+3 seconds or in a "block-by-block" nature )
2. Define the _events_ we want to react to.
3. Investigate wether or not __all__ of the interesting `events` can be tracked in form of `events`  (answer is no: [jug contract / stability fee collection](https://github.com/makerdao/dss/blob/17187f7d47be2f4c71d218785e1155474bbafe8a/src/jug.sol#L122) does not have event emitters
4. For those _events_ that can't be tracked as `events`, we reside to "block-by-block" parsing: look at the transaction logs, take the topic of the log record and compare with the pre-defined list of the log entries we're looking for.
https://etherscan.io/tx/0xe71d267d7ef5f3314970b2b8cc25709007881f1341c553ebb82b46ba282d2939#eventlog for example contains the log with topic[0] `0xb65337df` which corresponds to the call of `vat.fold` ( update stability fee rates ). If you open the [JUG contract](https://etherscan.io/address/0x19c0976f590d67707e62397c87829d896dc0f1f1) and see its transactions that call `drip` - the same log topic will appear all the time.

Proposal So I would split the logic into two steps
