### ISSUE TITLE
Weekly Scope unified-auctions-ui KW 39+40

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#470]
### Tasks

- Barking feature related issues
  - UI related 
    - [ ] Extend liquidation flow with WithdrawDaiFromVat panel
    - [ ] introduce thousand limiters for big numbers
    - [ ] update the unified landing page to include vaults section
    - [ ] add table component (dependent on #466)
  - blockchain related
    - [ ] Re-check the profit calculation
    - [ ] #464 (also relevant for `rETH` onboarding)
    - [ ] #466 
- `rETH` onboarding
    - [ ] https://github.com/sidestream-tech/auction-ui/issues/430
- MISC
    - [ ] #373 
       - [ ] investigate feasibility to work with API from frontend (+ legally)
       - [ ] #374 

### Bonus
- [ ] #443

**Comment by LukSteib** [comment]
>  Re-check the profit calculation

Had another look. The discrepancy between actual profit and calculated profit during test runs is related to the estimated transaction fees on the fork being higher than actual. 
Other than that the calculation is accurate. So for me no need to investigate further at this point in time

**Comment by LukSteib** [comment]
> rETH onboarding

based on the discussion with PE yesterday work on rETH is pushed out until the 12.10 when there is a PR for the mainnet spell to onboard it.

Suggestions on the current sprint:

> https://github.com/sidestream-tech/unified-auctions-ui/issues/464 (also relevant for rETH onboarding)

I would suggest to keep on working on this PR, since we already made quite some progress and a generic simulation for vault creation + liquidation will help us in all of the future onboarding processes (including rETH). @valiafetisov what is your take on that? 

> https://github.com/sidestream-tech/auction-ui/issues/430

I would for now stop further investigation on that front and wait for the pair programming session scheduled on the 12.10 for a complete walk through of existing simulations by PE.

Instead my proposal:
Put more resources on the liquidity sources stream. See the two relevant issues in the top level comment. Besides that I'd suppose to proceed with 1inch as well. Currently I see two tasks:

- [ ] check wether API can be called from frontend
- [ ] include 1inch quoter information to the `/dashboard` table to compare prices

@valiafetisov what is your take?

**Comment by valiafetisov** [comment]
> I would suggest to keep on working on #464

Agree

>> https://github.com/sidestream-tech/auction-ui/issues/430
>
> I would for now stop further investigation on that front and wait for the pair programming session scheduled on the 12.10 for a complete walk through of existing simulations by PE.

In order to execute the spell, we need their cli tools working on our side. I would still push this PR _at least_ to the state where we have a robust setup. But based on what we learned yesterday, we can also move forward with spell execution.

> Put more resources on the liquidity sources stream.

Yes, we can further investigate 1inch or/and set the goal to conceptualise multi-callee support. Or set the goal to release the auto router for unswapv3 callee(s) even before multi-callee support (even if it's not optimal order).

**Comment by LukSteib** [comment]
> In order to execute the spell, we need their cli tools working on our side. I would still push this PR at least to the state where we have a robust setup

Fine to push it up until the point where we have a robust setup. As this will minimise the risk of unknown unknowns for the meeting on the 12th. Although I would not proceed further than that.

> Yes, we can further investigate 1inch or/and set the goal to conceptualise multi-callee support.

Yes, let's include both parts into the scope. 

> Or set the goal to release the auto router for unswapv3 callee(s) even before multi-callee support (even if it's not optimal order)

I would stick to the original order of having multi-callee support first. For me the risk of having a buggy auto router implementation without fallback outweighs its upside.
