### ISSUE TITLE
Add `WithdrawDaiFromVat` panel to liquidation flow

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#473]
### Goal
A user can withdraw DAI from Vat via a dedicated panel in the liquidation flow

### Context
The liquidation incentive after a succssful vault liquidation ends up in the user's VAT balance. Since this might be unintuitive we should provide a user with the known withdrawal panel directly within the liquidation flow.
Open question remains where to introduce the panel. See two alternative proposals in asset section below

### Tasks
- [x] Decide on step where to introduce the withdrawal panel
- [x] Implement panel to liquidation flow
   - [x] Use existing panel `WithdrawDAIPanel`
   - [x] Adjust text as shown in mock below
- [x] On the transaction page: replace "This vault was liquidated N x ago in the transaction" with "This vault was _last liquidated_ N x ago in the transaction" because we've learned that the vault can be liquidated many times
- [x] On the transaction page: add panel below this message to withdraw DAI
- [x]  On the vault page: replace `This vault was liquidated N x ago in the transaction` with the table of transactions (date, hash, auction id with the link) that will display all transactions (like initially planned), not just one 

### Assets
**Alternative 1: Withdraw panel on liquidated page**

![image](https://user-images.githubusercontent.com/36229155/192265662-63b22367-4e6d-4b44-a88c-544c9fd6418a.png)

+ +Only at this step it will be possible to withdraw DAI 
- -Panel appears only after vault is liquidated and hence user doesn't have the "full picture" of the flow on the transaction page; liquidation page has two CTAs (proceed to auction, withdraw Dai from VAT)

**Alternative 2: Include as last panel on liquidationTransactionPage**

+ +Full flow is displayed on the transaction page
- -The panel will no longer be available once it is actually needed (ie. after successful liquidation)

**Comment by valiafetisov** [comment]
> Alternative 2

In general, in order to keep users attention and not clatter the UI, we try to keep only a single active primary button on a page. Therefore, I think it will be more UX-friendly to include withdrawal step into the "vault transaction page". Also because this panel suppose to be contextually related to the transaction that was just executed and not the amount of DAI in the VAT (which can be managed on a separate screen) – if the user have DAI in their wallet before the participation, they might not want to withdraw it anyway. So the proposal would be to:

- Include DAI withdrawal to the "vault transaction page" in its "liquidated state"
- Have only one active button (in the mock, both auth and withdraw buttons are active, which can't be the case)
- Replace `Refresh DAI balance in VAT` with `Manage DAI in VAT` or `Withdraw DAI partially` button in case user wants to withdraw not the whole amount (because now it's unclear how to do it or if it's even possible)

**Comment by LukSteib** [comment]
> Include DAI withdrawal to the "vault transaction page" in its "liquidated state"

What are you referring to with "liqudated state"? The page that is displayed in mock above?

> Have only one active button (in the mock, both auth and withdraw buttons are active, which can't be the case)
> Replace Refresh DAI balance in VAT with Manage DAI in VAT or Withdraw DAI partially button in case user wants to withdraw not the whole amount (because now it's unclear how to do it or if it's even possible)

Agree, adjusted the mock

**Comment by LukSteib** [comment]
Right now (except for the heading) both pages vault page and transaction page look exactly the same (see screenshot below). But still would be fine for me to indicate it on the transaction page, below the info box with redirect to auction. Do you agree

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/36229155/192265470-3e92592b-13fe-4a53-a5ae-2b6585a1c4b7.png">

**Comment by valiafetisov** [comment]
> look exactly the same

Except for the title 🙂 

> would be fine for me to indicate it on the transaction page, below the info box with redirect to auction

I would recommend to:

- [ ] On the transaction page: replace "This vault was liquidated N x ago in the transaction" with "This vault was _last liquidated_ N x ago in the transaction" because we've learned that the vault can be liquidated many times
   - Use "last liquidation transaction" rather than "first liquidation transaction" (currently we use index `0` to select the transaction, but should be using `length - 1`, correct me if I'm wrong on the order of events @KirillDogadin-std, can't find our discussion about `eth_getLogs` order)
- [ ] On the transaction page: add panel below this message to withdraw DAI
- [ ]  On the vault page: replace `This vault was liquidated N x ago in the transaction` with the table of transactions that will display all transactions, not just one (like initially planned)

**Comment by KirillDogadin-std** [comment]
> " (currently we use index 0 to select the transaction, but should be using length - 1, correct me if I'm wrong on the order of events @KirillDogadin-std, can't find our discussion about eth_getLogs order)

https://github.com/sidestream-tech/unified-auctions-ui/blob/626392d7234643dfa9ae2c7430abcb6d3c556605/core/src/vaults.ts#L214

`[0]` is the latest because it's a stack-like order.

**Comment by valiafetisov** [comment]
Thx, edited my previous comment
