### ISSUE TITLE
Introduce thousand separators for big numbers

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#474]
### Goal
Numbers are displayed with thousand separators throughout our UI

### Context
The newly introduced barking on underwater vaults feature displays a lot of big numbers. Especially in the limits section (see screenshot below).
To improve the UX and make these numbers more understandable, we want to introduce thousand separators.

### Tasks
- [ ] Introduce thousand separators (ie. display e.g. `1,000,000.45` instead of `1000000.45`)
- [ ] Include dedicate story
- [ ] Ensure that generally our `AnimatedNumbers` do not break

### Assets
<img width="600" alt="image" src="https://user-images.githubusercontent.com/36229155/192258007-c6a9c4be-78a4-49fa-b576-a145609edf83.png">
