### ISSUE TITLE
Include vaults page to unified landing page

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#475]
### Goal
user is able to access the vault liquidations page via a list item on the unified landing page

### Context
The vault liquidations page currently is only accessible via direct URL or via the header based navigation menu. 
We also want to include a link via a list item on the landing page. Since it is highly related to collateral auctions the list item should appear in this list.

### Tasks
- [x] Create a new list item for the vault liquidations portal (see Mock below for text)
   - [x] `participate` link needs to point to https://unified-auctions.makerdao.com/vaults
   - [x] `source code` link needs to point to https://github.com/sidestream-tech/unified-auctions-ui
- [x] Ensure that the list item shows up for the collateral auctions related list
   - [x] second place below the collateral auctions portal 

### Assets
<img width="600" alt="image" src="https://user-images.githubusercontent.com/36229155/192259170-1605cc11-8704-4a57-9caf-802cf1bacd8d.png">
