### ISSUE TITLE
Re-enable CI pipelines after repo switch

### ISSUE THREAD

**Issue by BracketJohn** [sidestream-tech/unified-auctions-ui#48]
**Goal**

Re-enable CI pipelines for pull requests.

**Context**

We've recently open-sourced this repository. As part of this we've also disabled the CI pipelines to prevent:
- malicious attempts to leak secrets,
- malicious/accidental resource usage that incurs costs, downtime, ...

We want to re-enable this while at the same time preventing the problems listed above. 

**Tasks**

- [x] find a way to prevent malicious leaking of secrets
- [ ] find a way to prevent malicious/accidental over-usage of resources
- [ ] implement the found solutions
  - [x] malicious leaking
  - [ ] malicious/accidental over-usage of resources

**Comment by BracketJohn** [comment]
>  find a way to prevent malicious leaking of secrets

secrets currently could leak via:
- drone ci logs
- drone ci arbitrary code execution
- deployments: consuming and displaying secrets in an automatic deployment 
  - e.g.: consume some secret API key to then display it in an automatically deployed frontend

The first two would be mitigated by disallowing the alteration of the `.drone.yaml` drone config file. To prevent changes to the config file, we can sign it + then turn on drone protection on this repo. This is documented [here](https://docs.drone.io/signature/). This will block pipeline runs with code that changed the `.drone.yaml` file. To change the file one will need to:
- apply the changes
- `drone sign sidestream-tech/unified-auctions-ui --save`
  - this requires authentication to drone and uses a secret server side key

The last point only applies to the continuous staging deployment (https://main.auction-ui.k8s.sidestream.tech/). As this is only triggered on a merge to main we mitigate this as part of our code review flow.

> malicious/accidental resource usage that incurs costs, downtime, ...

for this point we may discuss necessity: If some external contributor wants to contribute via their fork, we should enable them to run our CI so that the code can be verified to pass automatically. I see the following options right now:
- keep it enabled and see what kind of traffic we get -> is this guard necessary at all?
- add a k8s resource limit to the drone-cu namespace -> allow all usage by anyone up to a certain limit
- add a author/source/... type validation step before running a pipeline
- discuss further

**Comment by valiafetisov** [comment]
> note: detecting forks is not easily possible with drone, [see here](https://discourse.drone.io/t/how-to-identity-a-pr-coming-from-a-forked-repo/7782)

Oh, I would expect this to be so common that it should be solved long time ago. If not via drone config, then via github settings to not fire hook on forks or something like that.

> we can sign it + then turn on drone protection on this repo

As you pointed out, this doesn't protect from someone modifying docker file to add `RUN curl`. Since we expose aws secrets, that could have bigger impact than just loosing our twitter account.

I think currently, we just want to disable the drone completely if the code is coming from a fork/unknown user. If it's not solved by github or drone, the solution will presumably be "hacky", otherwise we may contribute to the drone 🙂. Initially, I suggested to check the user rights here https://github.com/sidestream-tech/devops/issues/90

**Comment by BracketJohn** [comment]
> I think currently, we just want to disable the drone completely if the code is coming from a fork/unknown user. If it's not solved by github or drone, the solution will presumably be "hacky", otherwise we may contribute to the drone 🙂. Initially, I suggested to check the user rights here sidestream-tech/devops#90

I did find a less hacky way via drone - thanks to the extended context that is made available to the templating (this is also the reason why no forum post, previous solutions exist, I think).

 Anyways, once this is merged we will be safe against arbitrary external execution. One attack vector would remain: changing the drone yaml to not use the templating engine.

To mitigate this we should also merge #49. Please have a look at that.

**Comment by valiafetisov** [comment]
> I did find a less hacky way via drone

🎉 

> One attack vector would remain: changing the drone yaml to not use the templating engine

How is it possible to disable it via drone config? (just curious)

> To mitigate this we should also merge #49

Will this signature be required across all projects now?

One other hacky solution I thought of: can the drone be configured to only be triggered by hand? So if the PR is submitted, someone have to log in to drone and then trigger the execution (like it is now possible with restart functionality). Then, it will be possible to first review the code and then trigger the pipeline (I suppose that only org members are allowed to log into drone UI)

> evil @MainStream-Tech

The user already have a first follower curious of their mainstream evil plans 😆

**Comment by BracketJohn** [comment]
> How is it possible to disable it via drone config? (just curious)

Some explanation on this above: https://github.com/sidestream-tech/unified-auctions-ui/issues/48#issuecomment-1016312879

It works like this:
1. drone has a secret, server side key
2. i authenticate to drone as an admin, get the key
3. i use the key to sign the file and append the signature to the file (as can be seen in #49)
4. i enable "protection" mode -> drone starts to validate the signature by re-generating and comparing it before every pipeline execution

somebody else alters the file? the signature that drone generates on the fly does not match the signature in the file any longer.

somebody tries to update the signature as well? for this they would need to guess the correct key.

> The user already have a first follower curious of their mainstream evil plans 😆

😂

**Comment by BracketJohn** [comment]
CI is now enabled again, see sidestream-tech/devops#90 for the solution via undocumented `ignore_forks` settings.

@valiafetisov please verify and close this issue if everything is fine.
