### ISSUE TITLE
Display uniV3 auto router prices and routes in dashboard

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#483]
### Goal
The dashboard table includes prices and routes determined by uniV3 auto router

### Context
Currently the routes for token swaps that are facilitated by the exchange callee contracts are hardcoded. In the future we want to leverage the uniV3 auto router feature. 
In order to check whether there is a differences in prices compared to the as-is state we first want to display the information from auto router in the dashboard.

### Assets
- Investigation issue on uniV3 auto router: #375 
- Draft PR for auto router test: #467 

### Tasks
- [ ] Extend the collateral table of the `/dashboard` page with two columns
   - [ ] Market value (Uniswap v3 auto router)
   - [ ] Swapping route (Uniswap v3 auto router)
- [ ] For all tokens fetch and display the two information

**Comment by valiafetisov** [comment]
Please use and extend [existing `getTestQuote`](https://github.com/sidestream-tech/unified-auctions-ui/pull/467/files) function to:
- [ ] not require wallet address (you can use `0x0` or [dead](https://etherscan.io/address/0x000000000000000000000000000000000000dead) address for the quotes)
- [ ] accept `collateralSymbol` as argument
- [ ] return both the quoted price (per unit, `BigNumber`) and the exchange route (array like `['ETH', 'USDC', 'DAI']`)

**Comment by valiafetisov** [comment]
Closed in https://github.com/sidestream-tech/unified-auctions-ui/pull/467
