### ISSUE TITLE
Wallet balances refetched too much

### ISSUE THREAD

**Issue by aomafarag** [sidestream-tech/unified-auctions-ui#487]
### Goal

Optimize wallet setup and balances fetching.

### Context

Currently, we re-setup the wallet whenever the wallet modal is [opened](https://github.com/sidestream-tech/unified-auctions-ui/blob/main/frontend/containers/WalletModalContainer.vue#L82). This action [resets](https://github.com/sidestream-tech/unified-auctions-ui/blob/main/frontend/store/wallet.ts#L296) the wallet, which involves resetting its balances and re-fetching them. As a result, the `WithdrawDAIPanel`, whose current state and title is displayed via a [computed property](https://github.com/sidestream-tech/unified-auctions-ui/blob/main/frontend/components/panels/WithdrawDAIPanel.vue#L88) that depends on the amount of DAI in VAT, collapses and expands whenever the wallet modal is opened (see [Assets](#assets)). Additionally, whenever the withdraw button is clicked, the animation due to `AnimatedNumber` is rerun (see [Assets](#assets)). I guess this has to do with the fact that `BaseButton` treats the loading and non-loading cases as two [separate](https://github.com/sidestream-tech/unified-auctions-ui/blob/main/frontend/components/common/inputs/BaseButton.vue#L14) templates.

### <a name="assets">Assets</a>

https://user-images.githubusercontent.com/85403429/194283168-0cfd4e83-bebe-43db-9eb0-974ed0d574c8.mp4

### Tasks

- [ ] Suggest a modification to the `store` logic that allows wallet balances to persist when re-fetching isn't necessary.
- [ ] Modify `BaseButton` so that it switches between the loading and non-loading state in a single template (if this is why the animation is rerun)
- [ ] Implement that suggestion once approved.
