### ISSUE TITLE
Weekly Scope [PROJECT NAME] KW [CALENDAR WEEK]

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#493]
### Tasks
- `rETH` onboarding **deadline: Friday, 14.10**
   - [ ] https://github.com/sidestream-tech/auction-ui/issues/430 (@valiafetisov)
   - [ ] Extend the vault creation and liquidation simulation for rETH (@KirillDogadin-std)
- Liquidity sources stream
     - [ ] #483 (@zoey-kaiser)
     - [ ] finalise #374 with breakdown for a) logic and b) frontend (@valiafetisov)
        - [ ] frontend work (@aomafarag)
        - [ ] logic work (@?) 
     - [ ] Display 1inch prices and routes in dashboard (@aomafarag)
     - [ ] Implement uni v3 auto router support

### Bonus
- [ ] #474 
- [ ] #443
