### ISSUE TITLE
Change ERC20 balance for collateral auction simulation

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#495]
### Goal

Simulations of auctions is possible for newly onboarded collaterals

### Context

During the implementation of https://github.com/sidestream-tech/unified-auctions-ui/issues/464 it was discovered that proposed generic solution (of modifying VAT balance) wouldn't work in case join contract own balance is insufficient to open a vault. This is especially problematic for newly onboarded collaterals when join contract balance is 0. Therefore, we need to update the simulation to prepare for this step. 

Technical proposal: extend collateral config with _optional_ key(s) to overwrite join contract balance. In case this key (eg `collateralBalanceSlotAddress`) is present, modify the balance at the same time the VAT balance is modified. Provide instruction/script on how to discover + validate balance number. I imagine that we can even make this generic since `balanceOf` function is always public, we might even write generic function that modifies every possible slot (and then change it back if it didn't work) until `balanceOf` shows desired value – maybe there is already a library/hadhat plugin for this? (as we're certainly not the first to need this functionality, maybe we can use something like [slot20](https://github.com/kendricktan/slot20)?)

Another generic option instead of modifying slots: find address who owns enough of the desired tokens (eg based on the logs), impersonate that account and move funds from there.

### Assets

- Previous PR that implements auction simulation: https://github.com/sidestream-tech/unified-auctions-ui/issues/464
- Related article https://kndrck.co/posts/local_erc20_bal_mani_w_hh/
- Library that does something similar: https://github.com/kendricktan/slot20

### Tasks

- [x] Please research (ie google) if there is library for that
  - [x] Otherwise investigate if changing ERC20 balance via hardhat is possible in the generic way
- [x] Propose technical solution
- [x] Discuss
- [ ] Implement

**Comment by KirillDogadin-std** [comment]
CRVV1ETH token introduces some complexity and the mentioned technical proposal has to be extended to cover the following edge case:

 - the vat 'holds' tokens of the collateral
 - the join contract actually (instead of having collateral tokens on its balance) converts it into liquidity pool tokens - lido.

 Which means that when we overwrite the vat, we have to provide value in CRVV1ETH tokens. When we overwrite the join contract balance, we have to provide the value in Lido tokens.

 Therefore to simplify the process and still comply with the initial proposal i would say that additionally we should:

   - modify the join contract balance to be the maximal value
   - specify the token address as optional argument in the collateral config as well - by default the collateral token is used to add to balance of the join contract, if the address is specified, the token of the address is used instead

**Comment by KirillDogadin-std** [comment]
Ok, i have nothing against dropping the VAT approach in this light.

This though requires us to generate the slot ourselves. I lean towards just hardcoding it, documenting how to use the cli-tool that you've linked and call it a day. Writing generic logic ourselves will likely result into time consumed and the edge-cases not covered.

After hardcoding the slots and overwriting the balance cutting out the VAT overwrite&extract logic, as you mentioned, should suffice. I do not foresee any additional required actions.

Hence, mechanical work which can be automated a bit:

 1. for every collateral generate the name of the join contract
 2. for every join contract call `gem` function and receive the address of the token
 3. for every token address call the cli tool `slot20` with the argument of the const `HARDHAT_PUBLIC_KEY` and the token address
 4. add the slot to the collateral config

Then replace the logic of vat-overwrite&extract with the logic of balance overwrite

**Comment by valiafetisov** [comment]
> Writing generic logic ourselves will likely result into time consumed and the edge-cases not covered

Not agree, quite the opposite, hardcoding will fire back at us and introduce extra complexity to onboard new collateral

> This though requires us to generate the slot ourselves

Please, as suggested in the issue, before proceeding to hardcoding, investigate the workarounds. 

1. What tools/hardhat plugins already exists?
2. Estimate both proposed solutions (automatically finding a slot vs automatically impersonate someone with tokens)

**Comment by KirillDogadin-std** [comment]
> Ie

there's no guarantee that the pool holds the amount as well, is there? Or does uniswap have some smart logic behind it that will top up the pool if requried?

if there's no guarantee, then we also are not solving any problem here: instead of join not holding enough token, now the pool holds insufficient amount instead
