### ISSUE TITLE
Create `MarketPriceSelection` component

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#496]
### Goal
Modify UI elements to support multiple callees

### Context
As part of our liquidity sources stream we decided to implement multi callee support. For background discussions and overall concept please read #374 

This issue tackles all of the required adjustments to the UI in order to finally enable the new feature

### Tasks
- [x] Modify `Auction` type to contain new keys (see E below for a proposal)
   - [x] note: `marketData` and `suggestedMarketId` are the new keys to be introduced
- [x] Modify fake function to create desired type (note that `unitPrice` can also be `new BigNumber(NaN)`)
- [x] Create `MarketPriceSelection` component as shown in the mock
   - [x] Use animation as in the `BasePanel`
   - [x] Expect `BigNumber.isNaN()` to be true for some markets (so they should display unknown and not be selectable)
   - [x] Use `synced` prop `marketId` to emit and receive currently selected `marketId`
   - [x] Expect that `suggestedMarketId` might change after the component render –> meaning that
      - [x]  in case no selection was made by the user, selected market might change by itself
      - [x] in case a selection was made by the user, it should stay fixed even if `suggestedMarketId` changes
- [x] Send `marketId` (`suggestedMarketId` if none selected) to the `bidWithCallee` action
 
### Assets

Mock:
![MakerDAO collateral@2x](https://user-images.githubusercontent.com/36229155/195309471-bba9a05f-b5ee-4a8e-a9f4-cd02d68fcb67.png)

E: 

```ts
    marketUnitPrice: BigNumber
    suggestedMarketId: 'Uniswap v3'
    marketData: {
            "Uniswap v3": {
                 unitPrice: BigNumber,
                 route: string[],
            },
            "Uniswap v2": {
                 unitPrice: BigNumber,
                 route: string[],
            },
        }
    },
```

**Comment by valiafetisov** [comment]
Very good question that I missed. I think we have to reapply calculation of the profits (basically all rows below `Market Unit Price will be changed). We can only do this in the store based on the selected market. This means, you will need to pass `marketId` variable all the way to the store. Other solution would be to receive all those parameters inside `marketData` already pre-calculated, eg


```ts
    marketUnitPrice: BigNumber
    suggestedMarketId: 'Uniswap v3'
    marketData: {
            "Uniswap v3": {
                 marketUnitPrice: BigNumber,
                 route: string[],
                 transactionGrossProfit: BigNumber,
                 transactionGrossProfitDate: Date,
                 transactionNetProfit: BigNumber,
                 // etc
            },
            "Uniswap v2": {
                 marketUnitPrice: BigNumber,
                 route: string[],
                 transactionGrossProfit: BigNumber,
                 transactionGrossProfitDate: Date,
                 transactionNetProfit: BigNumber,
                 // etc
            },
        }
    },
```

**Comment by valiafetisov** [comment]
> Is my task just to pass a third property in the object parameter, i.e. `{ id, marketId, alternativeDestinationAddress }`, and not worry about the logic that will follow

Yes, you need to pass is to the `dispatch`, log it in the action, but not pass down to the core until the core is updated in another PR

**Comment by valiafetisov** [comment]
yes, since this parameter also depends on the `marketUnitPrice`
