### ISSUE TITLE
Refactor core for multi callee support

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#497]
### Goal
Adjust core in a way to allow for multi callee support

### Context
As part of our liquidity sources stream we decided to implement multi callee support. For background discussions and overall concept please read #374 

This issue tackles all of the required adjustments to the core. 

### Tasks
- [x] Update collateral config `exchange` key to `exchanges` 
    from
    ```ts
    exchange: {
        callee: 'UniswapV3Callee',
        route: ['ETH'],
    },
    ```
    to
    ```ts
    exchanges: {
        "Uniswap v3": {
            callee: 'UniswapV3Callee',
            route: ['ETH'],
        },
        "Uniswap v2": {
            callee: 'UniswapV2CalleeDai',
            route: ['ETH'],
        },
        // "Uniswap v3 automatic route": {
        //    callee: 'UniswapV3Callee',
        //    route: undefined,
        // },
    },
    ```

    So basically prepending it with unique id, which will also be displayed on the frontend as title
- [x] Create function `getMarketData` that use `exchanges` configs and returns 

    ```ts
    {
        "Uniswap v3": {
             unitPrice: BigNumber,
             route: string[], // passed from the config in this PR, generated in case of automatic router in another PR
        },
        //...
    }
    ```

Notes: 
        - In case it's impossible to fetch specific market, the object should still be there, but `unitPrice` should be set to `new BigNumber(NaN)`
        - The main complexity here is that returned unit prices should all include exchange fees in order to be comparable between each other, see discussion above. For this, existing bid transaction fee logic should be reworked: `swapTransactionFee` should be split into variable part (that depends on the callee) and on constant part (basically the should be much more close to the `bidTransactionFee`); the variable part will then be hidden in the `unitPrice`. Technically that means, that while computing unit price (eg [here](https://github.com/sidestream-tech/unified-auctions-ui/blob/d5325f33edbf3fe588b2670d8b5eb0d1ae82f0b0/core/src/calleeFunctions/UniswapV3Callee.ts#L37)) we should first remove exchange fees (can be hardcoded per callee per route length)
- [x] Create `getBestMarketData` function that sort output of the `getMarketData` by `unitPrice` and return the lowest (together with it's id)

    ```ts
    {
         marketId: "Uniswap v3"
         unitPrice: BigNumber,
    }
    ```
- [x] Modify `_getMarketPrice` to use `getBestMarketData` and just output `unitPrice`
- [x] During collateral auction enrichment
   - [x] Keep `marketUnitPrice` as is (but put the best market price there)
   - [x] Add result of the `getMarketData` under new `marketData` key along existing `marketUnitPrice`
   - [x] Add `suggestedMarketId` key to the auction type along existing `marketUnitPrice`
- [x] Extend `bidWithCallee` to accept `marketId` required argument
   - [x] Generate callee data based on the `marketId`
- [x] Modify store to send `suggestedMarketId` to the `bidWithCallee`
- [x] Modify bot to send `suggestedMarketId` to the `bidWithCallee`

**Comment by valiafetisov** [comment]
@KirillDogadin-std, please see the discussion on extending `MarketData` type to also contain other fields that depends on the market price https://github.com/sidestream-tech/unified-auctions-ui/issues/496#issuecomment-1277750679

The approach here will be the same: old keys stays, displaying "best market", but duplicated inside `MarketData`. Please make sure to reuse types for the duplicated keys, not copy-paste and otherwise cleanup the type structure if possible.

**Comment by valiafetisov** [comment]
Please come up with yours by the analogy. If it's not optimal, it will be proposed during both reviews 🙂 

Also note that all collaterals with `UniswapV3Callee` can already have second callee `UniswapV2CalleeDai` like in the example since they are interchangeable at the moment.

**Comment by valiafetisov** [comment]
> Why are we checking [here](https://github.com/sidestream-tech/unified-auctions-ui/blob/main/core/src/calleeFunctions/helpers/uniswapV2.ts#L21) for Uniswap V3 as well?

That was the workaround (to specify that some collaterals actually support multiple callees) before current refactoring. This is why I suggest to already add two callees here: https://github.com/sidestream-tech/unified-auctions-ui/issues/497#issuecomment-1285345962

> the returned unitPrice should be: unitPrice - ([gasPrice * 722651](https://github.com/sidestream-tech/unified-auctions-ui/blob/main/core/src/fees.ts#L19) * route.length). Is this correct?

No. You will need to have something like `calleeExchangeFee` returned by the `getMarketData` per callee. For the existing callees (for which we don't know the actual fees) you will need to specify (ie hardcode) something like `gasPrice(722651 - 145438)` in the function `getMarketData` (then later on we will compute it per callee). Returned unit price that will be shown in the frontend (on by which the best market price is determined) will then will be
```
unitPriceWithFees = unitPrice + calleeExchangeFee
```

Does it sounds right?
