### ISSUE TITLE
Improve Table widths

### ISSUE THREAD

**Issue by zoey-kaiser** [sidestream-tech/unified-auctions-ui#502]
### Goal
We noticed that when switching between views on the pages, the column width of the table would change greatly. We want to introduce fixed width (or min widths) that fix this issue. 

However, we need to keep in mind that the table still works on:
- Mobile view
- Explanations on mode
- Explanations off mode

### Assets

https://user-images.githubusercontent.com/30908158/196419818-7c79da72-be71-41a3-8f4c-002bf5195ee7.mov

### Tasks

- [x] Introduce a fix
- [x] Test it in all circumstances
  - [x] Mobile View
  - [x] Explanations On mode
  - [x] Explanations Off mode

**Comment by valiafetisov** [comment]
> so why would we need a detailed time-elapsed format?

Because:
1. It's more compact and has less unpredictable length
2. If always shows `Last updated less than a minute ago` user might have a feeling that is it broken/statically rendered, so we want to show that it actually changes

If `TimeTill` is used in other places, maybe you can introduce new prop to control which format to use for the "future time"?
