### ISSUE TITLE
Feat: add vault opening simulation for CRVV1ETHSTETH

### ISSUE THREAD

**Issue by KirillDogadin-std** [sidestream-tech/unified-auctions-ui#503]
### Goal

Add functinality to enable simulation of CRVV1ETHSTETH vaults

### Context

Currently the simulations for the mentioned vault type are disabled because the mechanism for opening the vaults is different.

we can add support to `PROXY_ACTIONS_DSR` type contracts (which also is the [cropper](https://etherscan.io/address/0xa2f69f8b9b341cfe9bfbb3aab5fe116c89c95baf#code)):
  - add the corresponding key into the `COLLATERALS` config that specifies: `contractType: Standard | Proxied` where

```ts
interface Standard {
  type: 'standard'
}

interface Proxied {
  type: 'proxied';
  proxyName: string;
}
```

`Standard` logic executes the alrady existing code.
`Proxied` logic:
  1. calls `build` of [PROXY_FACTORY](https://etherscan.io/address/0xa26e15c895efc0616177b7c1e7270a4c7d51c997#writeContract) contract, creates the proxy and sets the `HARDHAT_PUBLIC_KEY` as owner.
  2. calls the function `execute(address _target, bytes _data)` of the created proxy. extracts the proxy from the chainlog - in this case [cropper](https://etherscan.io/address/0xa2f69f8b9b341cfe9bfbb3aab5fe116c89c95baf#code). Passes it as target. Passes `_data` where each point takes 32 bytes:
   - method id (`utils.id('transfer(address,uint256)').substring(0, 10)`). E.g. `openLockGemAndDraw(address,address,address,bytes32,uint256,uint256)` is converted into `0xff9a89c6` via https://emn178.github.io/online-tools/keccak_256.html
   - ...all the other args needed to call the method

the (2) from above is assembled via a helper function
the function to be called in the crveth case is `openLockGemAndDraw`. This immediately should result in debt drawn

example transaction: https://etherscan.io/tx/0x489d3cfc27f648dc2e79866b4a60bc8f57b836dbdd9ee5ce02dcb294d787cb6b

### Assets

Overview issue #501

### Tasks

- [ ] Discuss the proposed implementation
- [ ] Discover edgecases / questions and discuss them as well
- [ ] Implement vault opening mechanism
- [ ] remove the type from unsupported collaterals

**Comment by KirillDogadin-std** [comment]
With the implementation outlined in the header this should actually not be super complicated. The way contracts are aligned together for opening this type of vaults is quite clear.
