### ISSUE TITLE
Onboard rETH

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#507]
### Goal

Onboarded new rETH collateral

### Context

The new collateral will be onboarded by the protocol called `rETH`. This issue is to collect related information, lings and keep track of the progress.

### Assets

- New rETH mainnet spell draft PR https://github.com/makerdao/spells-mainnet/pull/281
- New rETH exchange callee draft PR https://github.com/makerdao/exchange-callees/pull/31
  - Exchange callee address on the mainnet https://etherscan.io/address/0x7cdAb0fE16efb1EFE89e53B141347D7F299d6610#code
- New rETH contracts https://github.com/makerdao/spells-mainnet/blob/cce4304aa6934c904bfceccaf39a9fcbdb764b16/src/test/addresses_mainnet.sol#L402-L406
- Example code to vote, lift and cast the spell https://github.com/makerdao/dss-simulation-scripts/pull/11

### Tasks

- [x] Create new callee code to display correct prices and build callee data following the onboarding guide
- [x] Validate (by reading relevant contracts) that the new collateral is compatible with our auction simulation
- [x] Create a new simulation
    - [x] Compile and deploy spell to a fork
    - [x] Vote, lift and cast the spell
    - [x] Create new auction
- [ ] Execute our bot against the simulation
- [ ] Check our frontend against the simulation
