### ISSUE TITLE
Weekly Scope unified-auctions-ui KW 43+44

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#509]
### Tasks
- multi-callee-support feature
   - [ ] #497
- Simulation stream (hardening and improving)
   - [ ] #505 (@KirillDogadin-std)
   - [ ] #503 (@KirillDogadin-std)
   - [ ] Extending the current state of the simulations suite with relevant tests (tbd) 
   - [ ] Refactor the oracle price adjustment part of existing simulation (@valiafetisov)
- Conceptualisation stream
     - [ ] strategic concept on 1inch callee development
     - [ ] short term concept for upcoming sprint

### Fixes / Finish up
- [ ] #488 (@aomafarag)
- [ ] #481 (@zoey-kaiser)

### Bonus

- [ ] #443
