### ISSUE TITLE
Refactor oracle logic

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#513]
### Goal

Simpler oracle logic, support for oracle writing

### Context

During the implementation of #506, we figured out that fetching oracle prices is cumbersome and not that clear at the moment. We also want to be able to change oracle price for any supported collaterals. For this, we want to introduce simpler and universal config for reading and writing data.

### Tasks

- [ ] Come up with a better config structure
- [ ] Refactor existing code
- [ ] Update `overwriteCurrentOraclePrice` to support all collaterals
- [ ] Update readme "collateral onboarding section"
