### ISSUE TITLE
Weekly Scope unified-auction-ui KW 45 + 46

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#522]
### Tasks
- Simulation stream (hardening and improving)
   - [ ] Refactor the oracle price adjustment part of existing simulation (@valiafetisov)
   - [ ] Extending the current state of the simulations suite with relevant tests (tbd) 
- Conceptualisation stream
     - [ ] strategic concept on 1inch callee development
     - [ ] conceptualise partial liquidation
- Wallet support extension
    - [ ] #521
    - [ ] #353

**Comment by LukSteib** [comment]
Discuss scope addition for week 2
* Take over fixes from above
* Integrate simulation into UI
