### ISSUE TITLE
Discuss time till profitability

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#533]
### Goal
Callee selection affects time till profitability

### Context
We have introduced multi callee support that allows a user to select between different exchange callees. These come with different market price. 
So ultimately one can expect that the "Time till profitability" indicator would need to change based on the callee selection. 
Currently unsure whether we take this into account. 
If the market prices of different callees only slightly differ chances are high that auction price will drop below all with the same price drop step. 
However if prices of different callees differ quite a lot the time till profitability might also be different since the thresholds won't be reached with the same price drop

Let's use this issue to discuss whether the assumption above is correct and if so how to address

### Tasks

- [x] Discuss effect of callee selection on "Time till profitability"
- [x] (if needed)Outline approach for adjustment
- [x] (if needed) Implement adjustment

**Comment by valiafetisov** [comment]
> and lines where it is changed based on the selected callee

What about this question? It is currently calculated, but not changed on the frontend?
