### ISSUE TITLE
Conceptualise partial swapping

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#534]
### Goal

A developer is able to implement the desired feature.

### Context

Currently, we only allow _partial bidding_ on collateral auctions when participating with your own DAI. But it's also possible to do so with swap-like transaction using callee. The only technical problem (and the advantage for the user) is that every time the bid amount is changed, the market unit prices will also change (and we might also need to refetch them in order to display correct numbers).

Note: 
- This feature was first time proposed in https://github.com/sidestream-tech/unified-auctions-ui/issues/229
- This feature was mocked in https://github.com/sidestream-tech/unified-auctions-ui/issues/528

### Assets

Latest mock: https://whimsical.com/makerdao-new-collateral-BT3LASEF2aRAQEuav79UUw

![MakerDAO new collateral@2x (9)](https://user-images.githubusercontent.com/3393626/201707766-f9a51aaf-2e4c-4940-9521-06889043e9d7.png)

#### Requirements

- The proposal _for the first iteration of this feature_ is to limit swap amount choices to a few predefined "probes" per market (but in the future we want to provide user with the regular input)
- UI-wise we want to show those options in a table, so the user can full overview of all "probed" prices and can choose other markets/amounts
  - the same component should be used to show those numbers inside `Market unit price` expandable block as well as in the `Amount to swap` expandable (with same tooltips, but with different main values: `marketUnitPrice` vs `netTransactionProfit`)
- The bot will need to have not just `suggestedMarketId`, but also suggested swap amount

### Tasks

- [ ] Conceptualise implementation/refactoring
  - [ ] Outline what needs to be done
  - [ ] Outline new vs old data structures
  - [ ] Outline new bot behaviour
  - [ ] Propose roadmap, ie issue(s) to get there
