### ISSUE TITLE
Cleanup the repo

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#536]
### Goal

Unused services removed

### Context

We've accumulated quite some code since the start of the project. This is especially visible by the amount of folders on in the root directly. The proposal is to remove unused/stale code. More specifically:

- [x] Remove `/chaos-proxy` folder
- [x] Remove `/reverse-proxy` folder (since we actually don't need docker-compose to set project up)
  - [x] Remove `/docker-compose.yaml`
- [x] Decide if we want to move `notification-service` to another repo or just remove it (together with @LukSteib), since it's out of scope of the original repo
- [x] Propose other changes in the issue (eg make sure all docs are up-to-date)

### Tasks

- [x] Open a new PR for each major removal so we can keep of those in the commit history

**Comment by LukSteib** [comment]
>  Decide if we want to move notification-service to another repo or just remove it (together with @LukSteib), since it's out of scope of the original repo

I would suggest to move it to another repo. This gives us the ability to decide wether to deploy and actually run it or not at some later point

**Comment by zoey-kaiser** [comment]
> I would suggest to move it to another repo. This gives us the ability to decide wether to deploy and actually run it or not at some later point

Do I create a new repo under `sidestream-tech` for this or should I contact someone else? 

Todo for moving the notification service:

- [ ] Create a new repository named `maker-notification-service` (or another name)
- [ ] Move the files into the new repository
- [ ] Adjust the Readme (if needed)
- [ ] Remove the `notification service` from `sidestream_tech/unified-auctions-ui`

**Comment by valiafetisov** [comment]
> Do I create a new repo under sidestream-tech for this or should I contact someone else?

Can you please first validate if you can actually split those? Does `notification-service` heavily depends on the core (if at all)? If so, what would be the way forward to remove/replace the dependency?

**Comment by zoey-kaiser** [comment]
> Can you please first validate if you can actually split those? Does `notification-service` heavily depends on the core (if at all)? If so, what would be the way forward to remove/replace the dependency?

It does not depend on the core! https://github.com/sidestream-tech/unified-auctions-ui/blob/main/notification-service/package.json#L30

Therefore a move should be very straightforward.
