### ISSUE TITLE
Add Coinbase Wallet

### ISSUE THREAD

**Issue by aomafarag** [sidestream-tech/unified-auctions-ui#545]
### Goal

Add Coinbase Wallet to our UI.

### Context

Currently, we support both MetaMask and WalletConnect wallets. Additionally, we would like to support Coinbase Wallet.

### Assets

Coinbase Wallet SDK docs: https://docs.cloud.coinbase.com/wallet-sdk/docs

### Tasks

- [x] Read the docs
- [x] Understand how to implement the wallet
- [x] Integrate the wallet in our codebase
