### ISSUE TITLE
Fix "not found" messages before loading

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#550]
### Goal

Not found messages in the UI no longer displayed on load.

### Context

Currently, 
- When a page to an auction is opened directly via url, the UI first show "This auction was not found" error and only later (a few seconds later) change it into the loading state
- When the main page is opened with the table or auctions, we also first display "No active auctions" and only a few moments later show loading state

Instead, the pages should always show loading state first or somehow indicate proper state of the auction
Please note that we once had a similar problem that was previously fixed: https://github.com/sidestream-tech/unified-auctions-ui/pull/90#issuecomment-1063130777

### Assets
- Example url https://unified-auctions.makerdao.com/collateral?network=mainnet&auction=WBTC-A%3A26
- Example screenshot
  <img width="666" alt="Screenshot 2022-11-28 at 13 31 22" src="https://user-images.githubusercontent.com/3393626/204278715-d1d692fe-3517-4a31-a3b5-a1831e8898c0.png">

### Tasks

- [x] Come up with several approaches to fix it, choose the best (we also don't want to show loading when it's not actually loading yet)
- [x] Fix auction page error
- [x] Fix auction table error

**Comment by valiafetisov** [comment]
Much more simpler approach would be to set `areAuctionsFetching` to true by default _in the store_, which would produce exactly the same result, right?

**Comment by valiafetisov** [comment]
> as it does not take `areTakeEventsFetching` into consideration

Those are two sequential events. Currently, in the container, we wait for the `areAuctionsFetching` to finish, then check if something was fetched and if not, fetch events. This was a temporary and quick workaround since it should all happen in the core and hopefully later be refactored. So I don't want to overcomplicate this logic now, since it's also does not add any benefits

> I also have an improvement suggestion

This is out of scope of this issue, as far as I understand. `Promise.allSettled()` can create some undesired side-effects (eg 429 error codes). Instead, [fetching of all auction types](https://github.com/sidestream-tech/unified-auctions-ui/blob/ae40099105454a9b4f62e797fe0d80daa1ec772f/frontend/store/network.ts#L108-L115) should be improved by checking the page we're currently in and only firing related actions (and re-firing them when page changes). You can work on this in another PR/issue.

**Comment by valiafetisov** [comment]
Yes, I think it would be ok. You just need to make sure (by reading the code and testing it for all types of auctions/vaults) that we always do those requests and clear up them to false (inside `finally`)
