### ISSUE TITLE
Fix Metamask wallet support while Coinbase extension installed

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#551]
### Goal

MetaMask extension works even if Coinbase is also installed

### Context

It was discovered that as soon as Coinbase extension is installed, it also modifies global `window.ethereum` object which makes it incompatible with Metamask. More specifically, [Metamask docs specify `window.ethereum.isConnected` function](https://docs.metamask.io/guide/ethereum-provider.html#methods) which no longer exist after `Coinbase` overwrites the object. I don't know if it's intentional or not (at least sounds like a war between extensions), but we should figure out how those two can coexists or, if they can't, indicate to the user how to solve the problem.

### Assets

- Potential solution https://www.npmjs.com/package/@metamask/detect-provider
- Related answer https://stackoverflow.com/a/70796779

### Tasks

- [x] Investigate what can be used instead of `isConnected` or if we should drop support for "reconnection" after page restart
- [x] Investigate how Metamask can still be accessed even if Coinbase is installed
  - [x] Otherwise, propose how the conflict can be discovered
- [x] Discuss
- [x] Implement
