### ISSUE TITLE
Test forking of the goerli network

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#555]
### Goal

Simulations work on goerli

### Context

In order to work with the new spell on goerli, we should validate that it works if our setup works on goerli.

### Tasks

- [ ] Test collateral simulation script on goerli
- [ ] Document any problems here, propose solutions
- [ ] Fix, if required

**Comment by valiafetisov** [comment]
Currently, simulation script "Simulate collateral auction per collateral type" fails with `Error: No contract address found for "CDP_REGISTRY"` although it is clearly there, as double-checked on the [chainlog](https://chainlog.makerdao.com/)

**Comment by valiafetisov** [comment]
It turns out [chainlog](https://chainlog.makerdao.com/) on goerli doesn't have `CDP_REGISTRY` contract for whatever reason. Not sure if it's deployed whatsoever? Next actions:

- [ ] Find if it's deployed, but wasn't added to the chainlog
- [ ] Check if we can remove this dependency to create vaults

**Comment by valiafetisov** [comment]
CDP_REGISTRY address on the mainnet: https://etherscan.io/address/0xBe0274664Ca7A68d6b5dF826FB3CcB7c620bADF3

**Comment by KirillDogadin-std** [comment]
Does not seem like we can just _easily_ remove this dependency:
 - there's not only the cdp registry missing, but also the cropper contract infrastructure. so, for instance, we are not able to find the target contract to execute actions on because `PROXY_ACTIONS_CROPPER` is also missing from the chainlog.

**Comment by valiafetisov** [comment]
> Cdp registry on goerli is

Great. Have you found it just by searching in the `spells-goerli` repo?

> `PROXY_ACTIONS_CROPPER`

This seems unrelated to the GNO onboarding, as this collateral doesn't seem to require a cropper. 

By (temporary) hardcoding the `CDP_REGISTRY` address I was able to create a ETH-A vault on goerli in #556. Technically, `CDP_REGISTRY` should only be required for the proxied collaterals, so we might reimplement this dependency as a fallback, not main code
