### ISSUE TITLE
Do not require frontend required env variables

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#571]
### Goal
Frontend does not require env variables

### Context
This issue forms part of our roadmap to package the Unified Auctions UI into a standalone app. 
A first step to achieve that is to not require env variables to get the frontend started any longer.

### Tasks
- [ ] Refactor the frontend / core to accept `RPC_URL` async and to not require it on start
   - [ ] no error is shown
   - [ ] as soon as it's needed, everything is cleared (and refetched, if needed)
- [ ] Create UI dialog that is automatically shown if no `RPC_URL` is provided
