### ISSUE TITLE
Investigate callees for other DEX protocols

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#576]
### Goal

Research notes on how to implement callee for other DEX protocols

### Context

Currently, the main liquidity provider for unified-auctions swap transactions is UniswapV3. But we want to add at least one other callee, the one which is the easiest to integrate in the limited amount of time we have. For this, we need to investigate further the technical details of the implementation and testing framework and prepare proof-of-concept.

### Tasks

- [x] Collect notes along the way
- [x] Outline next steps
- [x] Discuss if required

**Comment by LukSteib** [comment]
Research done by @valiafetisov.

What a typical existing callee code does:

- while being deployed, `constructor` [takes and sets some values](https://github.com/makerdao/exchange-callees/blob/3c4055571c0ab17efbd9e7ed809862bc47d8c2fd/src/UniswapV3Callee.sol#L73-L79)
    - `*router` – address of the router contract – from which the flash loan will be provided
    - `daiJoin` – address of the `MCD_JOIN_DAI` contract – to which the DAI needs to be retured
    - it gets DAI address using the `MCD_JOIN_DAI` contract view method `.dai()`
    - it approves `MCD_JOIN_DAI` contract to take any amount of DAI from the callee address
- exposes a single external function `clipperCall`
    - which [have to accept](https://github.com/makerdao/exchange-callees/blob/3c4055571c0ab17efbd9e7ed809862bc47d8c2fd/src/UniswapV3Callee.sol#L85-L90)
        - `sender` address – the address of the contract calling the function, which suppose to pay back the loan
        - `owe` (`uint256` amount denominated in RAD) – DAI amount to pay back (otherwise the callee will fail)
        - `slice` (`uint256` amount denominated in WAD) – amount of the token "received" (or rather "approved", the amount that can be taken by the callee from the "gemJoin" address)
        - `data` (`calldata bytes`) – arbitary data that can be passed from the frontend to the callee. It is usually contains at least
            - `to` address - the address to send remaining DAI to
            - `gemJoin` address – address that holds `slice` amount of tokens that callee is allowed to take
            - `minProfit` (`uint256` amount denominated in WAD) – minimum profit in DAI to make
            - other params required by the callee
    - the function then:
        1. converts `slice` from WAD to the actual ERC20 amount of tokens (eg `sliceERC20`)
        2. moves `sliceERC20` amount of token from `gemJoin` to the callee address
        3. gives `*router` the approval to move `sliceERC20` amount of tokens away from the callee address
        4. converts `owe` from RAY to the actual ERC20 amount of DAI (eg `oweERC20`)
        5. execute external `*router` function to exchange `sliceERC20` into DAI
            - passing `oweERC20` as a parameter to validate that the transaction can succeed
        6. checks that exchange took complete `sliceERC20` amount, otherwise transfer back the leftovers
        7. send back `oweERC20` of DAI
        8. transfer remaining DAI to the `to` address

The only variations between callees that I've found so far:

- [Sometimes the callee wouldn't hardcode `*router` address](https://github.com/makerdao/exchange-callees/blob/58b762ad24d64df2a85a0cc5f245265fbc63eca4/src/PSMCallee.sol#L58-L63), therefore can receive a different router address on every execution
- Collateral might require [more steps to be exchnaged into DAI](https://github.com/makerdao/exchange-callees/blob/3c4055571c0ab17efbd9e7ed809862bc47d8c2fd/src/CurveLpTokenUniv3Callee.sol#L139-L166), so step 5 turns into several steps on itself

So the overall next questions:
1. What external function we need to call to swap using 1inch?
2. What data do we need to pass to 1inch swap function (eg a route, something else)?
