### ISSUE TITLE
Extend Unified Auctions UI with 1inch callee

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#580]
### Goal
Select 1inch callee via UI to participate in auctions

### Context
Recently we have implemented a 1inch base exchange callee contract. (see https://github.com/makerdao/exchange-callees/pull/34/files) 
We now want to move on and integrate it to the UI. For that we might need to refactor the `core`. 

### Tasks
- [ ] Deploy latest version of 1inch callee to chain
- [ ] Check which parts of the current Unified Auctions UI code base need to be adjusted in order to accommodate the 1inch callee
- [ ] Integrate 1inch callee and ensure that other callees are still working

**Comment by KirillDogadin-std** [comment]
Modules:
1. one-inch request handling: _(analogous to the script in the PR)_
	- sends the requests to the one_inch api
	- gets 1-inch swap parameters
2. callee module:
	- repackages the 1-i api data for the smart contract function call _(analogous to the script in the PR)_
	- calls the contract function (callee)
		 - `getCalleeData`
			1. verify callee name from market data
			2. call the 1inch api (use the above mentioned module) 
			3. repackage the data from the 1inch api (using the module mentioned above)
			4. build function call arguments. 
			5. call the contract function
			6. part of the functionality to implement the above process should be extracted into the corresponding helper file `calleeFunctions/helpers/oneinch.ts`
		 - `getMarketPrice`
			 1. call to the [quote route](https://docs.1inch.io/docs/aggregation-protocol/api/quote-params)
			 2. get the estimated gas price, get the route of the trade, amounts of sold and received tokens.
			 3. perform the necessary conversions.
1. Collaterals config
	- adjust `COLLATERALS.ts`: corresponding tokens' should include the market data for the 1inch callee.

**Comment by valiafetisov** [comment]
- https://github.com/sidestream-tech/unified-auctions-ui/pull/561 should be merged before implementation is started
- by analogy of the #561, `getCalleeData` should not do any API calls, instead `getMarketPrice` should just store calldata and router address inside auction object
- `OneinchCallee` -> `OneInchCallee `

**Comment by KirillDogadin-std** [comment]
> or did you had another approach in mind? 

nope, as I was asked by @LukSteib to estimate the changes to the core, i left the deployment out of the post's scope.

> by analogy of the ...

updated the comment 

> The name of the callee ...

updated the comment.

**Comment by KirillDogadin-std** [comment]
regarding gas price estimation:

please confim if the process is correct:

1. Grab bytecode from `out/UniswapV3SplitRouteCallee.sol/UniswapV3SplitCallee.json` (corresponding json field)
2. put the bytecode into the separate file
3. use `cast estimate --create $(cat bc.txt) "UniswapV3SplitCallee(address,address)" 0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45 0x9759A6Ac90977b93B58547b4A71c78317f391A28 -- --rpc-url $RPC_URL` command according to the test [added here](https://github.com/foundry-rs/foundry/pull/2470/files#diff-196085826f3dc27a2947c3b520c1e5b2782f2ac1de08ef4219deca99247e55fa)
4. receive gwei price

___ 

currently i'm experiencing the following problem:
  - the copied value of the bytecode does not get accepted by the tool with error `(code: 3, message: execution reverted, data: Some(String("0x")))`
  - if i remove the `0x` prefix, it still fails with the same error
  - if i randomly add `00` in front of the bytecode, it succeeds with output `115473` which seems extremely low.
  - if i copy over the bytecode from `main` branch'es `bytecode` directory, it generates the output without any adjustments.

do you have the idea of what is done incorrectly?

**Comment by valiafetisov** [comment]
> please confim if the process is correct:

I sadly don't know the process, but think it should be easy to figure out. You obviously don't have to use foundry for estimating, you can use any other tools (remix IDE, tenderly, hardhat, etc)

**Comment by KirillDogadin-std** [comment]
i've ran ethers.js script 

```js
import { ethers } from "ethers";
import abi from "./out/UniswapV3SplitRouteCallee.sol/UniswapV3SplitCallee.json";

const factory = ethers.ContractFactory.fromSolidity(abi)
const deploymentData = factory.interface.encodeDeploy(['0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45', '0x9759A6Ac90977b93B58547b4A71c78317f391A28'])
const provider = new ethers.providers.JsonRpcProvider(RPC_URL)
provider.estimateGas({ data: deploymentData }).then(gas => console.log(gas))

```

and got `53736`

**Comment by KirillDogadin-std** [comment]
1inch integration thing arose:

- it seems that the [api](https://docs.1inch.io/docs/aggregation-protocol/api/swagger/) does not provide the trade fee:
  - should i substitute it with smth like `undefined` or `3000`?

**Comment by valiafetisov** [comment]
Ok, to be clear, [the proposal](https://github.com/sidestream-tech/unified-auctions-ui/issues/580#issuecomment-1408409655) is to replace `pools` with something simpler like:
```js
{
    path: 'LINK -> ETH -> DAI', // this can be directly shown in the frontend
    calleeData: '0x...', // output of the `getCalleeData`
    exchangeFeeEth: new BigNumber(0.1),
    exchangeFeeDai: new BigNumber(100),
}
```
which for the oneinch migh look like
```js
{
    path: 'Uniswap V3 -> Uniswap V2', // using response.protocols or whatever is returned from the response
    calleeData: '0x...',
    exchangeFeeEth: new BigNumber(0.1), // using response.tx.gasPrice
    exchangeFeeDai: new BigNumber(100), 
}
```

When the auction is executed, `calleeData` is being taken from `auction.marketRecords[marketId]...calleeData` and NOT generated again.

Do you see any problem with this proposal?

> should i substitute it with smth like undefined or 3000?

If the question was about collateral config, then 1inch callee should have it's own type which doesn't require fee to be defined

**Comment by LukSteib** [comment]
> `{"error":"Rate limit exceeded. Contact o.kudinov@1inch.io for a dedicated enterprise endpoint"}`

If asking for enterprise API price quote would be good to tell what we are expecting:
What'd be an acceptable rate limit for us? 
Any other requirements that we'd have?

**Comment by KirillDogadin-std** [comment]
_reate limit_

assuming we're at 100 users simultaniously, there're 20 auctions open, and we're updating every second: at least 2000 requests per second (depending on the implementation)

_other requirements_

as of now, not aware of those.

____

alternative:

publicly accessible url limits the rate based on the IP address i would imagine. so having the response cached for e.g. 60 seconds would likely be enough ( https://help.1inch.io/en/articles/5998758-1inch-api-troubleshooting hints that the rate limit is scoped to the overall public. E.g. if the rate limit is 10 req/sec then it's either 1 person that can sends 10 req/sec or 2 ppl who each send 5 req/sec)

**Comment by LukSteib** [comment]
> assuming we're at 100 users simultaniously, there're 20 auctions open, and we're updating every second: at least 2000 requests per second (depending on the implementation can be more)

Reached out to mail address mentioned in error message above asking for enterprise API price points.

**Comment by valiafetisov** [comment]
> 2000 requests per second

I guess you meant per minute? We don't need to send request every second, only every 30 seconds as it is right now done for all other exchange platforms.

But it would also depends on how the count the quota. If it's `per origin`, then we need 4000 requests _per minute_ for 100 users and 20 auctions. If it's `per ip address`, then it's 40 requests _per minute_. In any case, we can just add a tiny proxy in front of it, to make it `per ip address` and probably never need enterprise plan

**Comment by KirillDogadin-std** [comment]
> I guess you meant per minute? We don't need to send request every second, only every 30 seconds as it is right now done for all other exchange platforms.

as per https://github.com/sidestream-tech/unified-auctions-ui/blob/4cb58a4f18ed2f53c3cc0a754050c1d77348c508/frontend/store/auctions.ts#L21 and my experience logging things: it is exeuted every second

**Comment by valiafetisov** [comment]
> https://github.com/sidestream-tech/unified-auctions-ui/blob/4cb58a4f18ed2f53c3cc0a754050c1d77348c508/frontend/store/auctions.ts#L21

This particular line ensures that refresh of the _calculated auction values_ is done once per second. Enriching the same auction should trigger the cache implemented inside the `core`. This was pointed out multiply times over multiply PRs: literally no requests should be send to the blockchain (and now to external APIs) every second. Currently the cache suppose to be 10 seconds. But we can increase is to 29

https://github.com/sidestream-tech/unified-auctions-ui/blob/4cb58a4f18ed2f53c3cc0a754050c1d77348c508/core/src/calleeFunctions/index.ts#L21

> and my experience logging things: it is exeuted every second

Please ensure via logging that no requests are send more often than every ~30 seconds. If it's not the case right now, please open a PR to fix that.

**Comment by KirillDogadin-std** [comment]
https://github.com/sidestream-tech/unified-auctions-ui/blob/4cb58a4f18ed2f53c3cc0a754050c1d77348c508/frontend/store/auctions.ts#L354

this is not cached and subcalls a bunch of functionality that queries the blockchain (and api)

> If it's not the case right now, please open a PR to fix that.

https://github.com/sidestream-tech/unified-auctions-ui/pull/588

**Comment by KirillDogadin-std** [comment]
https://github.com/sidestream-tech/unified-auctions-ui/issues/580#issuecomment-1424184354

the best answer i found is still contained in the comment:

https://github.com/sidestream-tech/unified-auctions-ui/issues/580#issuecomment-1424141671

which is in my understanding "treating all the incoming requests to public api as coming from the single user"

**Comment by LukSteib** [comment]
Can you please re-iterate on the excat question(s) I should forward to the 1inch customer support?
Not able to derive the missing puzzle piece from the linked comments above.

**Comment by KirillDogadin-std** [comment]
essentially 2 questions are outgoing:

- What is the request rate limit?
- Is it limiting per origin or per ip?

**Comment by LukSteib** [comment]
Based on feedback from 1inch customer support: 

> What is the request rate limit?

2 Requests per second

> Is it limiting per origin or per IP?

It is limiting per IP

**Comment by valiafetisov** [comment]
> 2 Requests per second

Is this a paid or unpaid tier?

2 requests per second, should be fine for us. We can use a queue-like structure to never send requests in parallel. This will allow us to fetch ~50 auctions per 30 seconds (our current refresh delay).

> It is limiting per IP

Great, so we don't need to introduce caching proxy

**Comment by LukSteib** [comment]
> Is this a paid or unpaid tier?

This refers to the publicly available API (so unpaid tier)
