### ISSUE TITLE
Implement banner to announce packaged version

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#581]
### Goal
Show banner to inform users about electron packaged app.

### Context
We've released the first version of the electron packaged app of the Auctions UI. 
Let's inform users who access the browser version about this new possibility.

### Tasks
- [ ] Implement an info banner (similar to the existing staging banner) that informs users about electron app option
   - [ ] use yellow background color coding for the banner (not red as on staging)
   - [ ] ensure that it's only shown on production deployment

### Assets
Banner text:
"You can now run the Unified Auctions UI locally as an electron-packaged application. Please see its release [here](https://github.com/sidestream-tech/unified-auctions-ui/releases/tag/v1.17.0)"

**Comment by KirillDogadin-std** [comment]
could you point to the existing staging banner? it is not really clear how it should look like / where it should be located

**Comment by LukSteib** [comment]
> could you point to the existing staging banner?

* UI: https://main.auction-ui.k8s.sidestream.tech/collateral
* Code: https://github.com/sidestream-tech/unified-auctions-ui/blob/3a7b392e5408daf9883fd52039dae76251c58288/frontend/components/layout/StagingBanner.vue


Also extended the scope of this issue as discussed in daily
