### ISSUE TITLE
Extend landingpage list with desktop app reference

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#582]
### Goal
Have a list entry for all three auction types that references the desktop app

### Context
With the introduction of the Unified Auctions UI as a desktop app there is a new asset to add to the auctions landingpage.

### Tasks
- [ ] Add another item to the list on landingpage (`/`) 
   - [ ] Call it Unified Auctions UI application
   - [ ] description: Electron packaged application to run the Unified Auctions UI locally.
   - [ ] link to the latest release https://github.com/sidestream-tech/unified-auctions-ui/releases/tag/v1.17.0 via new button called `view` 
   - [ ] should appear for all auction
