### ISSUE TITLE
Prepare electron version for release

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#596]
### Goal
Ensure that version numbers of release and electron match

### Context
The updation strategy for the electron app relies on correct version numbers. We need to ensure that the version in `package.json` equals the version of the release. 

For that some preparation needs to be done

### Tasks
- [ ] Implement automated script based step that ensures to have correct version numbers (time cap to 1h)
   - [ ] in case the automated approach doesn't work out: Manually update `package.json` of election to `v1.18.0`
- [ ] Adjust `Readme` to reflect the required version related preparation steps in the general release procedure
