### ISSUE TITLE
Deploy v1.18.0

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#598]
### Goal
Deploy release v1.16.0 to production

### Context
Latest changes will be deployed to production

### Tasks
- [x] Check staging
- [x] Create release images
   - [x] check app images
- [ ] Check production
- [x] Check electron app

**Comment by LukSteib** [comment]
Release images: 
https://github.com/sidestream-tech/unified-auctions-ui/releases/tag/v1.18.0

App images:

**Comment by LukSteib** [comment]
>  Check production

- [ ] The app announcement banner is not displayed on production.

> Check electron app

- [ ] NIT: Once the banner is closed the header is still extended with white element

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/36229155/223688567-8ae05085-bfbb-475e-a74b-3aa34c8c71d8.png">

**Comment by valiafetisov** [comment]
The env variable `` is missing from the frontend, according to `$nuxt.context.env`:
<img width="691" alt="Screenshot 2023-03-08 at 11 37 11" src="https://user-images.githubusercontent.com/3393626/223691008-55c984c3-9a1f-48b4-8710-1c64f79ad4d2.png">

But it's provided during frontend build on `publish-frontend-makerdao-on-tag`:
https://github.com/sidestream-tech/unified-auctions-ui/blob/f3a5969ff48cbe8d47d425d3810b3e8ac5889712/.drone.yml#L135-L136

And it's passed inside the frontend/Dockerfile:
https://github.com/sidestream-tech/unified-auctions-ui/blob/f3a5969ff48cbe8d47d425d3810b3e8ac5889712/frontend/Dockerfile#L47-L48

And it's configured in the nuxt:
https://github.com/sidestream-tech/unified-auctions-ui/blob/f3a5969ff48cbe8d47d425d3810b3e8ac5889712/frontend/nuxt.config.js#L27

And it's present in the secrets:
```
$ secret read auction-ui/production.auction-ui.k8s.sidestream.tech/frontend PRODUCTION_BANNER_URL
Key			Value									Version		LastModified		User
production_banner_url	https://github.com/sidestream-tech/unified-auctions-ui/releases/latest	1		2023-03-07 18:05:32
```

Any idea what's going on, @DeusAvalon?

**Comment by DeusAvalon** [comment]
Hmm i think the issue is that the SSM path are not matching. In the `.drone.yml` u r using 
```
auction-ui/main.auction-ui.k8s.sidestream.tech/frontend
```
but in your example you are reading from
```
auction-ui/production.auction-ui.k8s.sidestream.tech/frontend
```

I havent checked it myself but thats the first inconsistency i saw checking your snippes provided in ur comment :)
