### ISSUE TITLE
Add meta-tags for each auction page

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#6]
### Goal
Link to a particular auction posted on twitter should have proper text there.

### Context
When posting a link to a social network, it is scraped by it and a card is created based on the meta-tags. We want this card to be nice enough and to display information about actual content of the page.

Note that different pages of our website should have different meta-tags:
- `A`: `/` – description of the unified auctions
- `B`: `/collateral` – description of the collateral auctions
- `C`: `/collateral?network=X&auction=Y` – description of the particular auction. For example: `MakerDAO ETH-A collateral auction sidestream-tech/auction-ui#22 on the X ethereum network`

Note that in order to display the meta-tag from above you don't have to fetch its data (although it's not prone to joke attacks). For implementation: `head()` can be used to generate them dynamically: https://nuxtjs.org/docs/features/meta-tags-seo/

Tools to debug meta-tags: 
- https://cards-dev.twitter.com/validator
- https://developers.facebook.com/tools/debug/

Note: in order to test meta-tags from your development machine you may want to use a tunnel. There are plenty of services that provide this functionality, some of which are free https://github.com/anderspitman/awesome-tunneling#commercialclosed-source

### Todo
- [ ] confirm meta-tags content with PM for:
  - [ ] the title
  - [ ] the description
  - [ ] image (optional, you may need to add width + heigh tags in order to display an image)
- [ ] add meta-tags for at least `B` and `C`
- [ ] validate via twitter debugger
- [ ] validate via facebook debugger
