### ISSUE TITLE
PAXUSD-A:11 investigation

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#601]
### Goal

Investigate and potentially fix strange behaviour of the UI

### Context
Latest PAXUSD-A collateral auction that was recently started (and was still active at block `16834122`) resulted in invalid state, where it can not been taken, nor it's state is properly explained.

We need to investigate the reasons and fix them.

### Assets
- [PAXUSD-A:11](https://unified-auctions.makerdao.com/collateral?network=mainnet&auction=PAXUSD-A%3A11) auction
- Block `16834122`
- Failed transaction https://etherscan.io/tx/0x97e35c45eb72100c9ac9433d8126806cd75eee8a903879e360d0ee6e46355bd7

### Tasks
- [x] Investigate what lead to the current situation (code-wise)
- [x] Propose changes
- [ ] Implement them

**Comment by valiafetisov** [comment]
Bid parameters of the [failed transaction](https://etherscan.io/tx/0x97e35c45eb72100c9ac9433d8126806cd75eee8a903879e360d0ee6e46355bd7)  at block `16834122`
```ts
#	Name	Type	Data
0	id	uint256	11
1	amt	uint256	101.918099729767250518
2	max	uint256	0.998894444444444444444444444
3	who	address	0x2417B973754FD3b91Fe9D5916F3d70d0d0171A39
```

[Clipper.getStatus(11)](https://etherscan.io/address/0xbcb396cd139d1116bd89562b49b9d1d6c25378b0#readContract) result at a bit later state:
```ts
needsRedo bool: false
price  uint256: 0.998886111111111111111111111 // current auction unit price (changing over time) [RAY/27 decimals]
lot    uint256: 1144.000000000000000000 // total amount of the collateral in the vault [18 decimals]
tab    uint256: 101.805423608399341168522984214544545908674082026 // debt in dai [RAD/45 decimals]
```

[Transaction trace on tenderly](https://dashboard.tenderly.co/tx/mainnet/0x97e35c45eb72100c9ac9433d8126806cd75eee8a903879e360d0ee6e46355bd7?trace=0): it seems that the bid amount (`amt`) after it being multiplied by current unit price inside the contract becomes smaller (`101.804574290901593108395227766453544474470305498`) than the debt (see above `tab` value) and therefore doesn't cover it completely, therefore moving [to the branch of clipper logic](https://github.com/makerdao/dss/blob/fa4f6630afb0624d04a003e920b0d71a00331d98/src/clip.sol#L369-L380) which leads to the `Clipper/no-partial-purchase` error.

The conclusion that `amt` we supply is too low, even through we aim to cover all debt.

The `amt` we supply is calculated via [`calculateTransactionCollateralOutcome` function](https://github.com/sidestream-tech/unified-auctions-ui/blob/24a1932c9eb9e12c69f052a0b1788574cdda5833/core/src/price.ts#L58). Its input parameters are:
```ts
bidAmountDai 1000 // value supplied via UI – looks legit
unitPrice 0.998886111111111111111111111 // value fetched from the blockchain – looks legit
auction.debtDAI 101.805423608399341168522984215 // rounded up(?) value of the auction debt – shouldn't be rounded up
```

`auction.debtDAI` is rounded, so I increased max decimal places the bignumber to RAD across the core. New values are:

Also, if I don't enter anything to the input field, the input parameters are:

```ts
bidAmountDai 101.805423608399341168522984214544545908674082026 // same value as the debt
unitPrice 0.998886111111111111111111111 // same value as in the blockchain
auction.debtDAI 101.805423608399341168522984214544545908674082026 // same value as in the blockchain
auction.collateralAmount 1144 // same value as in the blockchain
auction.minimumBidDai 15000 // same value as in the blockchain
collateralToBuyForTheBid 101.918949994365286946482816474219323543439445069 // looks legit
potentialOutcomeCollateralAmount 101.918949994365286946482816474219323543439445069 // correct
potentialOutcomeTotalPrice 101.805423608399341168522984214544545908674082026411162058420075161840061659 // looks legit (if rounded it is the same as debtDAI)
approximateDebt 101.8054236083993
approximatePotentialOutcomeTotalPrice 101.8054236083993
"return tab / price"
```
Interestingly, even if `approximateDebt` and `approximatePotentialOutcomeTotalPrice`, the value is returned here:
https://github.com/sidestream-tech/unified-auctions-ui/blob/24a1932c9eb9e12c69f052a0b1788574cdda5833/core/src/price.ts#L72-L77

Meaning that BigNumbers `.isLessThan` method doesn't properly work when used in combination with `toPrecision`?

But it actually doens't matter, since retuned value of `auction.debtDAI.dividedBy(unitPrice)` (or `amt` that we will use in the blockchain) being `101.918949994365286946482816474219323543439445069` is exactly the same as `potentialOutcomeCollateralAmount` that will be retuned otherwise.

Is this number sufficient to cover the debt? It's not according to the logs, but it is according to the calculations:
`101.918949994365286946482816474219323543439445069 / 0.998886111111111111111111111` will be `102.03260297712591887278` which is bigger than `debtDAI` from above, so it should work without any multiplications

```
bidAmountDai 101.805423608399341168522984214544545908674082026
updatedAuction.unitPrice 0.998886111111111111111111111
collateralAmount 112.1108449938018156411310981216412558977833895759 
```

But sometimes, we end up in a different state `shouldnt be possible to left less than minimumBidDai`
```ts
bidAmountDai 101.805423608399341168522984214544545908674082026 // correct
unitPrice 0.997091435185185185185185185 // same as above, but lower
auction.debtDAI 101.805423608399341168522984214544545908674082026 // correct
auction.collateralAmount 1144 // correct
auction.minimumBidDai 15000 // correct
collateralToBuyForTheBid 102.102395042127194919486722814973262361283174392
potentialOutcomeCollateralAmount 102.102395042127194919486722814973262361283174392
potentialOutcomeTotalPrice 101.80542360839934116852298421454454590867408202583683836759754400716978252
"shouldnt be possible to left less than minimumBidDai"
```

Rounding `potentialOutcomeTotalPrice` up based on the RAD precision (to match `debtDAI`) results in correct processing of this data on the level of `calculateTransactionCollateralOutcome`, but still results in `reverted with reason string 'Clipper/no-partial-purchase'` while executing it.

If `calculateTransactionCollateralOutcome` is multiplied by `1.1`, we supply `amt` of `112.3126345463399144114353950964705885974114918312` and get back `102.136800784277218365` in VAT
when auction is taken, which is `0.0336972919546380098615299995103318399563208472`% bigger than `102.102395042127194919486722814973262361283174392` that we tried to supply initially :(

At this point, I would assume that the main error can be attributed to the _math_ differences between js and solidity, altrough the difference is quite significant to be attributed to it.

### Problems
- [x] Rounded `debtDAI` number
- [x] Invalid behaviour of `isLessThan` for two exactly the same numbers
  - [x] Arbitary rounding parameters (`toPrecision`) instead of metching them to the maker units
- [x] Different computations of big numbers in javascript versus solidity, eg `tab / price`
- [ ] Unhandled [`NaN` state](https://github.com/sidestream-tech/unified-auctions-ui/blob/24a1932c9eb9e12c69f052a0b1788574cdda5833/core/src/price.ts#L92) on the frontend (except that the button is disabled, no message is displayed) and during bidding

**Comment by LukSteib** [comment]
Thanks for this thorough investigation! Interesting to see the effects of these rounding operations.

The only part I cannot fully follow:
> If calculateTransactionCollateralOutcome is multiplied by 1.1

How do you end up at the multiplication of `1.1`? Is this an arbitrary number to get rid of rounding issues and in the end as per contract the `amt` will either way be reduced to the value required to clear the whole debt?

**Comment by valiafetisov** [comment]
> How do you end up at the multiplication of `1.1`? Is this an arbitrary number to get rid of rounding issues and in the end as per contract the `amt` will either way be reduced to the value required to clear the whole debt?

`1.1` was just an initial test. Since the contract wouldn't sell more collateral than is needed to cover debt and wouldn't also take more DAI than needed, it was just to ensure that the `take` will go through as expected. As soon as I took the auction and checked the actual amount of collateral that were given in return, I've estimated that the difference of js-calculated vs solidity-calculated to be `0.0336972919546380098615299995103318399563208472` percent. 

The multiplication in the fix PR #602 is [set to be `1.001`](https://github.com/sidestream-tech/unified-auctions-ui/blob/9d708eb5b9b1344a4661195afc9224fa50a7bcf8/core/src/price.ts#L76-L77) or only `0.1%`. It still bothers me that it's quite a lot to be the rounding issue, but I can't explain it better than that 🙁. We literally just divide `debtDAI` by `unitPrice` (both of which are exactly the same in js as in the blockchain) to get number which is a bit lower than computed in the contract.
