### ISSUE TITLE
Allow usage of flashbot RPC

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#603]
### Goal
Unified Aucitons UI works with flasbot RPC

### Context
During the course of the last weeks we saw users trying to run the Unified Auctions UI with flashbot RPC. 
This is currently not possible.
Since it is common practice and pattern that we might see among different users, let's explore and facilitate flashbot RPC usage

### Assets
- flashbots docs: https://docs.flashbots.net/flashbots-protect/rpc/quick-start

### Tasks
- [ ] Investigate and understand flashbot RPC mechanics and document in this issue
- [ ] Identify why current RPC approach doesn't support it and document
- [ ] Propose adjustment on how to ensure flashbot RPC support in the future
- [ ] Implement proposal
