### ISSUE TITLE
Improve bid with DAI UI

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#604]
### Goal
The bid with DAI flow doesn't show unintuitive numbers

### Context
In the light of recent auctions we experienced our UI to display unintuive numbers.
Let's first investigate how we ended up in this situation; what numbers are actually displayed and then improve it by either not showing numbers any more or showing them in a better representation

### Assets
<img width="550" alt="Screenshot 2023-03-15 at 16 02 33" src="https://user-images.githubusercontent.com/36229155/226844019-7dfab4ff-eb32-43f8-ae13-dad16f58ef72.png">

- The 15k number with the "AND" in the minimum leftover is unintuitive
  - why do we display the `chost` parameter here in the first place?

### Tasks
- [ ] Rethink the logic for the numbers we display in the min leftover row of the Bid with DAI tx page
- [ ] Propose a change to make it more intuitive
- [ ] Implement the change
