### ISSUE TITLE
Deploy v1.19.0

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#606]
### Goal
Deploy release v1.19.0 to production

### Context
Latest changes will be deployed to production

### Tasks
- [ ] Check staging
- [ ] Create release images
   - [ ] check app images
- [ ] Check production
- [ ] Check electron app

**Comment by LukSteib** [comment]
Images: 
https://github.com/sidestream-tech/unified-auctions-ui/releases/tag/v1.19.0
