### ISSUE TITLE
Stop fetching data through wallet

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#65]
### Goal
Stop fetching data through Metamask, use it only for signing write operations

### Context
Since Metamask started to apply rate limiting, frontend sometimes hits the limit due to the high number of requests that we have to make. The only downside of that is increased our infura usage, which will be mitigated in #38.

The proposed solution is to have two separate providers:
1. The provider created with our infura endpoint
2. The signer created with wallet signer
Therefore, it should be possible to `getContract`s by specifying which provider to use, possibly just adding extra argument `withSigner`, with `false` by default.

### Tasks
- [x] Store providers and signers separately
- [x] Extend `getContract` function
- [x] Validate that after connecting wallet read calls are still go through our endpoint
- [x] Validate that wallet functionality is not affected

**Comment by valiafetisov** [comment]
This issue was closed as part of the PR #74
