### ISSUE TITLE
Implement RPC caching proxy

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#66]
### Goal
Setup basic RPC caching proxy

### Context
After preliminary investigation in https://github.com/sidestream-tech/unified-auctions-ui/pull/38, it seems like caching RPC read requests can be a viable solution to make our website scalable and not significantly affected by it's popularity. But we still want to validate and test that it will not significantly affect the users.

### Tasks
- [ ] make RPC caching testable
  - [ ] make it work with kubernetes
  - [ ] make sure that container logs indicate hit/miss
  - [ ] create a separate `RPC-caching-test` infura key with no restrictions
- [ ] never fetch auctions via metamask in another PR https://github.com/sidestream-tech/unified-auctions-ui/issues/65 (and merge it here first)
- [ ] deploy the branch
- [ ] manually test it with several connected clients
- [ ] if all the above goes well, let's solve the problem of not exposing infura key to the frontend

**Comment by BracketJohn** [comment]
> To validate that opening several clients together will produce a lot of hit records and we can later estimate percentage of the cached requests

Configuring ingress logging is limited by ingress/nginx per default to a certain set of variables (https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/log-format/). This is because the log format is defined as part of the `http` directive, but the cache hit/miss is only captured on the lower `location` level - so turning on logging here is not easy.

I'd instead just want the team members to look into their networking tab to verify it - in general I don't see a point of extensive testing of the nginx caching functionality: Our request format is quite trivial and nginx likely implemented their caching correctly.

>  But if you want, you can!

I don't want to, the main point is that I don't see the implementation of:
- bot twitter code,
- networks.ts related code,
- adding hit/miss env vars,
- testing

on my task list, but rather on the list of members. If we can mange this with this one issue I'm fine with keeping it (:

**Comment by valiafetisov** [comment]
>  in general I don't see a point of extensive testing of the nginx caching functionality

As stated above, the the main reason for logging is to see caching _across_ connected clients. Single clients already cache requests and doesn't call the same contract method more often than 2 times per minute. Second reason is the estimation of the saved quota. Third reason is the bot, that doesn't have console to look into.

But if you say it's not easy, it's another point we need to estimate. What would be the workaround?

> I don't see the implementation on my task list
> bot twitter code

I am not sure who else will be able to figure out how to make bot-twitter pass requests through the ingress.

> networks.ts related code,

The expected change is to create and set env variable so if not set it falls back to pure infura endpoint. I think adding env variable and making sure it works can fall into category of tasks you can help with (: 

> adding hit/miss env vars

Do you mean logs? Then it's answered above.

> testing

This point is mainly for the functional review, but as the whole issue is not just implement, but also validate that it works properly, we need to also prepare means to conclude (eg logging):
- Frontend worked without issues
- Cache was actually hit
