### ISSUE TITLE
Adjust `Purchase with DAI` tooltip text

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#67]
**Goal:**
Point users to the correct UI as long as we haven't reached feature parity with [https://liquidations.makerdao.com/](Liquidation Portal).

**Context:**
In our discussion to align with DUX (maintainers of existing liquidation portal) we decided to improve guidance for users to the suitable UI depending on the current use case. Either participate without Dai in auctions (ie. flashloan based participation that we offer) and to bid with Dai (feature that we haven't implemented yet but liq portal has).
* Liq portal will show a banner that informs user on our UI being the one to participate via flashloan without capital requirements
* We point users that want to bid with Dai to liq portal

**Tasks:**
- [x] Adjust text of our `Purchase with DAI` button to `Bid with DAI` (reasoning: Bidding implies that the auction can still be won by somebody else)
   - [x] Adjust the explainer text above accordingly and write `Bid with DAI` for first option instead 
- [x] Adjust text of current tooltip for this button to `This website doesn't support to bid on the auction with your own DAI yet. You can do so on the [Liquidation Portal]<https://liquidations.makerdao.com/>`
