### ISSUE TITLE
Release 0.7.0

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#72]
### Planned Release Scope
-   Finish repository switch
    -   [ ] Rename `unified-auctions-ui` to `unified-auctions`?
    -   [ ] Rename old `auction-ui` to `unified-auctions-private`
-   Product stream
    -   [x] Follow up with Chaoslabs on testing setup
    -   [x] Follow up with PE on callee address PR
    -   [ ] Get makerdao.com domain https://github.com/sidestream-tech/auction-ui/issues/287
-   Blockchain stream
     -   [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/35
     - [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/80
     -   [ ] https://github.com/sidestream-tech/unified-auctions-ui/issues/45
     - [x] Streamline process to use new callees #77
     - [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/81
     - [x] Support `wstETH` https://github.com/sidestream-tech/unified-auctions-ui/issues/73
-   Devops stream
    -   [x] #25
    -   [ ] https://github.com/sidestream-tech/unified-auctions-ui/issues/66
-   UI/fixes stream
    -   [x] Indicate time estimate for auction turning profitable #43 
    -   [ ] Add links to the contracts (clipper, calc) to the dashboard table and maybe to the auction/transaction page text
    -   [x] Add networks + callees table to the dashboard page
    -   [ ] Interlink all other UIs with our UI (open PRs to other websites / source codes) - https://github.com/sidestream-tech/unified-auctions-ui/issues/93
    -   [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/28
    - [x] #58 
-   Bonus
    - [x] https://github.com/sidestream-tech/unified-auctions-ui/issues/65
    - [ ] introduce tests for critical functionality:  fetching, authorisation and execution
    - [ ] https://github.com/sidestream-tech/unified-auctions-ui/issues/33

---

Predecessor: #32

- [x] double-check with @valiafetisov and @LukSteib whether release makes sense
- [x] release images via UI https://github.com/sidestream-tech/auction-ui/releases/new 
- [x] Deploy staging to production _goal: 11.02. , 12:00_ 
   - [ ] Test prod environment
- [x] Share release notes in makerForum _goal: 12.02

**Comment by benediktkaiser** [comment]
Maybe we can also add #58 as I have almost finished it in #63?

**Comment by valiafetisov** [comment]
> introduce tests for critical functionality

I would move this to the bonus, since we're blocked by Chaoslabs here or need to set up our own hardhat. Instead, we can already start working on #35 and #45 since we're unblocked this last week (looking at you, @benediktkaiser).

**Comment by LukSteib** [comment]
Release Images created: 
https://github.com/sidestream-tech/unified-auctions-ui/releases/tag/v0.7.0

Testing on https://production.auction-ui.k8s.sidestream.tech successful ✔️

**Comment by BracketJohn** [comment]
Deploy complete - worked on first try. Please check it out!

**Comment by LukSteib** [comment]
New UI elements ✔️ 
Auction restart (on goerli) ✔️ 
Auction execution on testnet (pending)

However I already consider it as a successful deployment ✅
