### ISSUE TITLE
Add `wstETH` collateral support

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#73]
### Goal
Participation in `wstETH` collateral auctions is possible via the UI

### Context
`wstETH` collateral requires it's own callee contract and uses Uniswap v3 exchange, therefore:
- new callee address should be passed to the clipper contract (along with possibly different callee data)
- the price of the new collateral should be calculated separately

This issue will also be used to refactor callee logic to streamline collateral onboarding.

### Tasks
- [ ] Refactor callee / collateral logic
  - [ ] Import callee addresses from a single file (proposed in https://github.com/makerdao/exchange-callees/pull/22)
  - [ ] Make a declarative configuration: price calculation function + callee data generation per callee
- [ ] Add new callee support
  - [ ] Deploy callee to test networks if needed
  - [ ] Add uniswap v3 library
  - [ ] Generate callee data
  - [ ] Calculate price
- [ ] Add new collateral config
- [ ] Manually validate that new collateral is supported

**Comment by valiafetisov** [comment]
> Add new callee support

The callee in question is https://github.com/makerdao/exchange-callees/blob/master/src/WstETHCurveUniv3Callee.sol

But I can not find its address, since action-demo-keeper [doesn't seem to support this collateral](https://github.com/makerdao/auction-demo-keeper/blob/main/config/examples/mainnet-uniswapv3.json).

Till we get the address from the PR (by merging the PR and asking them to fill the json), I can try to deploy it myself, but it's not clear for me, what constructor parameters should be used. The contract accepts: 

- `address curvePool_`: supposedly `CurveContractV1.vy` contract from the official docs https://curve.readthedocs.io/ref-addresses.html, [but it can not be find on test chains](https://blockscan.com/address/0x845838DF265Dcd2c412A1Dc9e959c7d08537f8a2)
- `address uniV3Router_`: supposedly [`0xe592427a0aece92de3edee1f18e0157c05861564`](https://etherscan.io/address/0xe592427a0aece92de3edee1f18e0157c05861564#code) (across networks)
- `address daiJoin_`: `MCD_JOIN_DAI` from the https://chainlog.makerdao.com
- `address weth_`: supposedly `WETH` token address, also from the https://chainlog.makerdao.com

**Comment by valiafetisov** [comment]
It turns out, I've been looking into a wrong config file inside `action-demo-keeper` and it actually supports `wstETH`: https://github.com/makerdao/auction-demo-keeper/blob/bca09252af029448ff67823b0b7825ad8c6feff8/config/mainnet.json#L358-L373

Another interesting, but currently unrelated point: latest mainnet config uses `uniswapV2Callee` for `YFI-A` (while all other collaterals are traded via V3 callee) https://github.com/makerdao/auction-demo-keeper/blob/bca09252af029448ff67823b0b7825ad8c6feff8/config/mainnet.json#L189

**Comment by valiafetisov** [comment]
Based on the deployed callee, constructor parameters are:

| name | description | mainnet | kovan | goerli |
|:---|:---|:---|:---|:---|
| `curvePool` | [StableSwapSTETH.vy contract](https://curve.readthedocs.io/ref-addresses.html#:~:text=stETH-,StableSwapSTETH.vy,-0xDC24316b9AE028F1497c275EB9192a3Ea0f67022) | [`0xdc24316b9ae028f1497c275eb9192a3ea0f67022`](https://etherscan.io/address/0xdc24316b9ae028f1497c275eb9192a3ea0f67022) | unknown | unknown |
| `uniV3Router` | Same on all networks | `0xe592427a0aece92de3edee1f18e0157c05861564` | `0xe592427a0aece92de3edee1f18e0157c05861564` | `0xe592427a0aece92de3edee1f18e0157c05861564` |
| `daiJoin` | `MCD_JOIN_DAI` from the https://chainlog.makerdao.com | | `0x5AA71a3ae1C0bd6ac27A1f28e1415fFFB6F15B8c` |  |
| `weth` | `ETH` from the https://chainlog.makerdao.com | | `0xd0A1E359811322d97991E03f863a0C30C2cF029C` |  |

Unfortunately, StableSwapSTETH.vy doesn't seem to be deployed anywhere except main.

**Comment by valiafetisov** [comment]
@LukSteib can you maybe ask PE if they are aware of `WstETHCurveUniv3Callee` or the `StableSwapSTETH` addresses on the test chains? Or did they only test it on the mainnet/fork? Otherwise, we would need to prioritise #81 sooner than later to actually test something.

**Comment by LukSteib** [comment]
> Or did they only test it on the mainnet/fork? 

Yes, testing is based on the mainnet/fork approach and not on the testnet based approach. 

> Otherwise, we would need to prioritise #81 sooner than later to actually test something.

Given the above, I agree that we need to prioritise that. IMO the minimal testing setup that we requested from chaoslabs (ie. liquidation of one `urn` of a specific `ilk` at a time) would already help here.

**Comment by valiafetisov** [comment]
> Yes, testing is based on the mainnet/fork approach and not on the testnet based approach.

I tried forking mainnet a few blocks before active [`wstETH` auction was taken in block `14052147`](https://etherscan.io/tx/0xbfaaa3f07a138f2b3d1d01d231d325828a5a29b39510506217b9b99bb299b8b4), but it doesn't seem to work so far (it's not being fetched from the clipper).
