### ISSUE TITLE
Include callee contract reference to /dashboard

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#75]
**Goal:**
Reference the `exchange-callee` contracts we are using to execute the flash loans with their respective addresses on the dashboard

**Context:**
Depending on the collateral type we are using different exchange callee contracts in order to execute auctions. For each network these contracts need to be deployed separately. The dashboard page is a good place to show the contracts we are using and include a link to the respective etherscan page of the contract. Similar to us displaying the token addresses for the collateral types

Since the callee references do not fit in the collateral table let's create a second one. With a dedicated heading and text block. And show a two column table with `Callee` and `address`. 

Example:
| Callee Contract  | Address |
| ------------- | ------------- |
| uniswapV2Callee  | 0x5A40F810754f725DA93e2362775a0600468f7a83 |
| uniswapV2LpTokenCallee  | 0xDeC8b9c2829583A89f7F182DEeD7C12112dfAeD0 |

**Tasks:**
- [x] Include new text block to dashboard page below collateral table
   - [x] Heading: Exchange Callee Contracts
   - [x] Text: see file in assets below
- [x] Implement table following the example above
   - [x] Check with @valiafetisov whether it makes sense to wait for implementation of this one since we might have a more structure way in our files to store callee addresses 
   - [x] Ensure that we dynamically display the correct callee names and addresses depending on the network and what we support

**Assets:**
Doc with text: https://docs.google.com/document/d/1DdvTn84XpS4kaTk-oh1ADiTh38SDvvPE2i9IygCgWWQ/edit?usp=sharing

**Comment by fegbert** [comment]
> Check with @valiafetisov whether it makes sense to wait for implementation of this one since we might have a more structure way in our files to store callee addresses

Discussed in the daily: Going to implement this now and refactor it when the new changes get merged.
