### ISSUE TITLE
Discuss and implement Terms and Condition consent implementation

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#79]
**Goal:**
Define and implement the most appropriate user flow to give consent to our terms and conditions

**Context:**
As Is:
* The user is prompted with T&C consent popup when trying to connect wallet for the first time
* We currently store T&C consent in local storage for unlimited time once user has given consent

In the future we want to change that in order to being able to make adjustments to the T&S statement.
Discussed alternatives:
* A1: User has to agree to T&C on wallet connection for every new session 
* A2: User has to agree to T&C on wallet connection when we release a new version of T&S statement (implies to have T&C versioning)
* A3: User has to agree to T&C on wallet connection and we store consent with cookie for period of X days before consent expires

**Tasks:**
- [x] Discuss different possible approaches and decide
- [x] Implement approach to store user consent to T&C in session cookie
   - [x] see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie
   - [x] meaning: With each new browser session the user is provided with T&C popup when connecting wallet to UI

**Comment by LukSteib** [comment]
@valiafetisov can we find an agreement on our preferred approach here as input for the T&S stream? 
No need to move on with implementation right away

**Comment by valiafetisov** [comment]
I think the easiest for us and good enough for the user would be `A1`: to store the setting not in the [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage), but in the [`sessionStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) – follow the link to see technical description of when it expires. I think Metamask also prompts for your password as soon as you reopen the browser (so start a new session).

But my comments during the meeting was about legal technicalities:
 - Is it ok, that after refreshing the page, we would connect to the wallet without asking for user action and T&C?
 - Is it ok, that the user can change the wallet (disconnect and connect another wallet/account) and if it was done during the same session, it will not prompt for a new T&C agreement?

**Comment by LukSteib** [comment]
> I think Metamask also prompts for your password as soon as you reopen the browser (so start a new session).

True, if I understand the linked tech description for `sessionStorage` correctly this however would mean that user has to give concent to T&C also when opening a new tab in the same browser session. Is that the case or am I wrong?

**Comment by valiafetisov** [comment]
> this however would mean that user has to give consent to T&C also when opening a new tab in the same browser session

Ah, true! Then we can store it in a cookie, but without expiration date:

> If `expires` unspecified, the cookie becomes a session cookie. A session finishes when the client shuts down
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#:~:text=If%20unspecified%2C%20the%20cookie%20becomes%20a%20session%20cookie.%20A%20session%20finishes%20when%20the%20client%20shuts%20down

**Comment by LukSteib** [comment]
> Then we can store it in a cookie, but without expiration date:

Sounds good to me.

The questions on technicalities you have raised above would still apply, right?

**Comment by valiafetisov** [comment]
Yes, I think it's something a lawyer should consider.

**Comment by LukSteib** [comment]
Answers to legal considerations:

> Is it ok, that after refreshing the page, we would connect to the wallet without asking for user action and T&C?

Yes, fine.

> Is it ok, that the user can change the wallet (disconnect and connect another wallet/account) and if it was done during the same session, it will not prompt for a new T&C agreement?

Yes, fine.
