### ISSUE TITLE
Integrate testing environment 

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#83]
### Goal
Manual testing via the tool provided by ChaosLabs.

Note: this issue is a replacement of #81

### Context
We want to enable frontend-based manual testing of auctions on the mainnet fork. This should be possible with the help of the testing API that ChaosLabs are building. Documentation of their API can be found here: https://github.com/sidestream-tech/auction-ui/issues/392

I imagine the ideal testing scenario to be:
- Developer/product manager starts frontend locally, `CHAOSLABS_ACCESS_TOKEN` is set via `.env` file
- The user opens http://localhost:3000/ and able to see another network (`Mainnet Fork`) in the networks selector (since `CHAOSLABS_ACCESS_TOKEN` is present)
- After choosing this network
  - Page is navigated to the `?network=fork&rpc={encodedPRCendpoint}`
  - User sees a non-closable modal with the `simulation_details.status`, eg `pending`, `started`, `ready`, etc
- After the fork is created and the `status` is `simulation finished`
  - Modal goes away
  - New provider provider is created using `nodeUrl`
  - Auctions are refetched (or page is simply refreshed)

### Tasks
- [ ] add `CHAOSLABS_ACCESS_TOKEN` to dev secrets
- [ ] implement the algorithm from above
- [ ] test auction fetching and participation

**Comment by LukSteib** [comment]
The testing scenario sounds great in the described flow.

> New provider provider is created using nodeUrl

Can you give a quick explainer what that means?

**Comment by valiafetisov** [comment]
> Can you give a quick explainer what that means?

It's just a technical detail of what should happen under the hood. Basically a provider (part which is responsible for sending requests) should be recreated using the new RPC url provided by the chaoslabs.

**Comment by LukSteib** [comment]
> It's just a technical detail of what should happen under the hood. Basically a provider (part which is responsible for sending requests) should be recreated using the new RPC url provided by the chaoslabs.

Thx for the explainer - as stated above general setup looks very good

**Comment by valiafetisov** [comment]
Since we've discovered some complexities after trying out their API, I've decided to first create a mock to imagine how the ideal scenario may look like. So this is a UI that let us start a simulation and connect to it not only locally, but also on staging or production (the user have to know `ChaosLabs access token` to start a simulation):

![MakerDAO@2x (32)](https://user-images.githubusercontent.com/3393626/157669663-bc3dd571-4427-4c02-b320-8d783a06cddd.png)

**Comment by LukSteib** [comment]
Very lean and clean flow 👍 

One question to the last step: 
Once the simulation is ready the RPC url is automatically filled and Connection is initiated?

**Comment by valiafetisov** [comment]
> Once the simulation is ready the RPC url is automatically filled and Connection is initiated?

Yes, exactly: no additional interaction is required from the user side. This should give user a possibility to copy the RPC link from the input and share it with another user/tab/browser if needed.

**Comment by valiafetisov** [comment]
In the last meeting with agree with Chaoslabs to do an actual test of the Metamask's API for adding networks. Here is the result: as expected, without the possibility to create simulations with unique chainIds it's not possible to add them to Metamask. This feature (not yet supported by Chaoslabs) is essential to implement the flow prosed above.

Here is more details with the screenshots:

<details><summary>As expected, metamask doesn't allow adding a new network with already existing `chainId`</summary>
    <img width="603" alt="Screenshot 2022-03-23 at 10 09 52" src="https://user-images.githubusercontent.com/3393626/159663739-0d8a95af-5cbd-4ee0-a830-c31c6e8945c1.png">
</details>

<details><summary>(Adding new non-http network also doesn't work)</summary>
    <img width="608" alt="Screenshot 2022-03-23 at 12 38 49" src="https://user-images.githubusercontent.com/3393626/159694409-8e4078ce-206b-4a61-afcb-60b9d2582bbc.png">
</details>

<details><summary>As expected, adding new network with `chainId` that didn't existed in the metamask before works</summary>
    <img width="645" alt="Screenshot 2022-03-23 at 12 59 21" src="https://user-images.githubusercontent.com/3393626/159694940-f9403f51-d490-4956-9853-3886c945f497.png">
</details>

 - <details><summary>By showing a prompt</summary>
    <img width="472" alt="Screenshot 2022-03-23 at 12 56 16" src="https://user-images.githubusercontent.com/3393626/159694520-428cdafc-9eec-40d9-8c1d-3472f3ff9a85.png">
</details>

- <details><summary>After which metamask immediately propose to switch to the newly created network</summary>
    <img width="472" alt="Screenshot 2022-03-23 at 12 56 29" src="https://user-images.githubusercontent.com/3393626/159694527-035c4cb4-fdbe-452b-9969-b3cf792d081c.png">
</details>

<details><summary>But adding a new network with the same `chainId` as added above doesn't even throw an error, but doesn't add/modify anything</summary>
    <img width="611" alt="Screenshot 2022-03-23 at 12 58 04" src="https://user-images.githubusercontent.com/3393626/159694875-daef362f-7c13-42a5-bbc9-9429a4d21a27.png">
</details>

**Comment by LukSteib** [comment]
> But adding a new network with the same `chainId` as added above doesn't even throw an error, but doesn't add/modify anything

Does that mean that for each new simulation a new chainId would have to be generated? Or even on each new start of an existing simulation a chainId would have to be generated?

**Comment by valiafetisov** [comment]
> each new start of an existing simulation a chainId would have to be generated?

Yes, unfortunately, for each simulation run a new unique RPC url is created and therefore new network should be added. The downside is that metamask will have a bunch of `Simulation XXX` networks in the networks list that doesn't work anymore. Upside: the account doesn't need to be "reset" in the settings every time to fix `nonce too high` error.

**Comment by LukSteib** [comment]
>  bunch of Simulation XXX networks in the networks list that doesn't work anymore.

Think this is not that big of a deal tbh.

> Upside: the account doesn't need to be "reset" in the settings every time to fix nonce too high error.

Heard of this error in the past but cannot relate anymore. Can you briefly elaborate what this error is about so that I better understand this upside?
