### ISSUE TITLE
Investigate the failure of restarting a Link auction on the first attempt

### ISSUE THREAD

**Issue by florianstoecker** [sidestream-tech/unified-auctions-ui#86]
**Goal**
Have the bug fixed.

**Context**

While testing out the UI on Kovan, a link auction did not restart on the first attempt(on the second it did go through) & I've got the following error shown in the console:
Auction redo error: Error: transaction failed (transactionHash="0x9fffa5f09d7a34cef78b12e908305b5c7180ad66ce67cf5d048fa2023fce3ffe", transaction={"hash":"0x9fffa5f09d7a34cef78b12e908305b5c7180ad66ce67cf5d048fa2023fce3ffe","type":2,"accessList":null,"blockHash":null,"blockNumber":null,"transactionIndex":null,"confirmations":0,"from":"0x4f3B7fb6204C614B28F0e1f50Dc1C99175631678","gasPrice":{"type":"BigNumber","hex":"0x77359400"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x77359400"},"maxFeePerGas":{"type":"BigNumber","hex":"0x77359400"},"gasLimit":{"type":"BigNumber","hex":"0x022d9a"},"to":"0x1eB71cC879960606F8ab0E02b3668EEf92CE6D98","value":{"type":"BigNumber","hex":"0x00"},"nonce":1020,"data":"0xd843416d00000000000000000000000000000000000000000000000000000000000000c80000000000000000000000004f3b7fb6204c614b28f0e1f50dc1c99175631678","r":"0xd5e351c172ec2ec517470085b08b4e86cc6bf74e37bdd0e10dbba9e8de175bc0","s":"0x3de59b163aa0edeef348ed0cffc1f3c2ecc3de0efdda53db8d79aebe8e430bcd","v":1,"creates":null,"chainId":0}, receipt={"to":"0x1eB71cC879960606F8ab0E02b3668EEf92CE6D98","from":"0x4f3B7fb6204C614B28F0e1f50Dc1C99175631678","contractAddress":null,"transactionIndex":3,"gasUsed":{"type":"BigNumber","hex":"0x022d9a"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","blockHash":"0xebcaf2c0e55de53535e29fe7c8d35c95ac740d2d273cbff79cc18c22628c8baf","transactionHash":"0x9fffa5f09d7a34cef78b12e908305b5c7180ad66ce67cf5d048fa2023fce3ffe","logs":[],"blockNumber":29645633,"confirmations":1,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x0795e1"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x77359400"},"status":0,"type":2,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.4.5)

**Tasks**
- [ ] Investigate the console log 
- [ ] Document error reasoning
- [ ] Fix error if possible

**Comment by valiafetisov** [comment]
The reason is: out of gas
https://kovan.etherscan.io/tx/0x9fffa5f09d7a34cef78b12e908305b5c7180ad66ce67cf5d048fa2023fce3ffe

**Comment by florianstoecker** [comment]
> out of gas

"This means that your ETH/ERC20 transaction ran out of the assigned Gas Limit when executing a Smart contract operation on the Ethereum Virtual Machine (EVM) (Usually "Send" for the user). This most commonly happens with ERC20 tokens as they consume much more gas than plain ETH"

Screenshot from the transaction on Etherscan shows: 
![image](https://user-images.githubusercontent.com/36764271/152526696-69cde490-c926-4221-b173-4d5f5ab5b45c.png)


We do not define how much gas a transaction needs, am I right? So this error should be MetaMask-related?
