### ISSUE TITLE
Fix "Header not found"- error

### ISSUE THREAD

**Issue by florianstoecker** [sidestream-tech/unified-auctions-ui#9]
**Goal**
Error is fixed.

**Context**
Under unknown circumstances, we noticed, that a "Header not found" - error is shown in the auctions table 
![image](https://user-images.githubusercontent.com/36764271/144235503-eded7fc4-5fdf-443a-844e-41651388ed54.png)

**Tasks**
- [ ] Try to replicate this error
  - [ ] Suggestions: Let a tab with the auctions UI opened on it open in the background(/on a second screen if you have) and check in between.
  - [ ] Try to catch this error and screenshot the console output. NOTE: The error disappears after a few seconds again, however it is not clear, if the console error will disappear too!
- [ ] Fix the problem.
