### ISSUE TITLE
Spread the URL of our auctions UI to other Maker UIs

### ISSUE THREAD

**Issue by florianstoecker** [sidestream-tech/unified-auctions-ui#93]
**Goal**
The URL of our auctions UI is included in other Maker UIs

**Context**
In order to spread awareness of our UI, we want other Maker UIs to point at our domain.

**Tasks**
- [ ] Step 1: List all possible places (e.g. Makerburn, Maker Footer)
- [ ] Step 2: Check if there are public repos to the UIs + find out the maintainer
- [ ] Contact maintainer
- [ ] Draft the text for a PR to include our domain on others UIs
- [ ] Open PRs in all the repos
- [ ] (Make sure they get recognized & merged)

**Comment by valiafetisov** [comment]
> List all possible places 

I guess we already did this step on the unified page: https://auctions.makerdao.network

I would suggest to:
- [ ] Come up with a text of the link. Something like `All available tools related to maker auctions`? Or `Participate in the auctions`
- [ ] Create a basic mock proposal for each project (by editing html in the console, for example and adding a link). Would be nice to propose a common style for that (eg in a footer)
- [ ] Depending on the project:
  - [ ] Open PR with the changes for all projects which have source code
    - [ ] Make sure it get recognized & merged
  - [ ] Write to the maintainer if there is no source code

**Comment by fegbert** [comment]
My proposals (so far) would be:

## Dai Auctions

![image](https://user-images.githubusercontent.com/47861849/153200154-2dfeea8e-f6d0-4d33-94e6-5570d1bff9bf.png)

- Footer structure is perfect for just adding another link to it
- Length of sentence fits nicely
- Added to the end but ordering hasn't been considered yet, just an example 😄 

### Information

Maintainer: Martinlsanchez - https://twitter.com/0xMarto
Repo: https://github.com/martinlsanchez/daiauctions

## Dai Stats

![image](https://user-images.githubusercontent.com/47861849/153200728-73b2648a-d13a-42fb-8a88-14ca2a7746a0.png)

- Footer is very similar to daiauctions, so same points apply here.

### Information

Maintainer: nanexcool - https://twitter.com/nanexcool
Repo: https://github.com/nanexcool/daistats

## Surplus / Debt auctions portal

![image](https://user-images.githubusercontent.com/47861849/153200937-011219cc-fcab-4e17-9c2a-999c2f1febe0.png)

- Footer is smaller and horizontal with relatively large text, so adding the long sentence here in my opinion would look bad. That's why I went with the shorter option of `Participate in Auctions`. This of course is just an idea, but I think a sentence of this length would be better.

### Information

Maintainer: MakerDAO - https://twitter.com/MakerDAO
Repo: https://github.com/makerdao/auctions-ui

## Liquidations Portal

![image](https://user-images.githubusercontent.com/47861849/153201517-607a43e1-e978-4dbf-9c09-aa359433329e.png)

- Haven't added anything yet since they already have this massive banner at the top linking to us. Should we still add another link in the footer? 🙂 

### Information

Maintainer: MakerDAO - https://twitter.com/MakerDAO
Repo: https://github.com/makerdao/liquidations-portal

## Block Analitica

![image](https://user-images.githubusercontent.com/47861849/153201852-9914e415-e592-493b-941f-d24494d65c98.png)

- This one is a bit tricky since the page doesn't have anything other than the copyright notice in its footer. The only other place I could think of though would be the navigation menu, but I don't think it really belongs there. For now, I added it to the footer to keep a common style across pages.

### Information

Maintainer: Block Analitica, d.o.o - https://de.linkedin.com/company/block-analitica
Repo: unavailable

## Makerburn

![image](https://user-images.githubusercontent.com/47861849/153202273-b632ff11-53a2-44f1-b5e6-9c9b09e4bc20.png)

- Same thing as with `Block Analitica`. The only thing in the footer so far is a link to the creators' forum page.

### Information

Maintainer: makerburn - https://forum.makerdao.com/u/makerburn
Repo: unavailable

**Comment by LukSteib** [comment]
> Let's make it All available tools related to MakerDAO auctions or Unified MakerDAO auctions. I think this text is also a matter of SEO. @LukSteib, what's your take?

My personal preference would be to go with the shorter one and change it to `Unified Maker auctions`. Rationale behind `Maker` instead of `MakerDAO`: The auctions are related to the protocol structure and not to the DAO that is governing the protocol.

Generally agree with the footer based proposals. Some takes on particular tools / services:

> [Liquidations Portal](https://liquidations.makerdao.com/)

The old liq portal is using some sort of standard Maker related footer. I am trying to find out who's maintaining this footer in order to include our link there as well. This footer is also used by e.g. https://makerdao.com/en/


> [Block Analitica](https://maker.blockanalitica.com/)

Since there is no real footer I would suggest to somehow get a link on the auction related subpage https://maker.blockanalitica.com/auctions/
@fegbert can you make a proposal? As this one is maintained by the Risk core unit we can directly approach them with a proposal. 


> [Makerburn](https://makerburn.com/#/)

Here I would suggest a slightly different approach: Instead of linking to our root page we can ask the maintainer(s) to replace the existing link to the outdated liq portal by our `.../collateral` page as it directly tackles collateral auctions. See existing link on makerburn: 
<img width="918" alt="Screenshot 2022-01-21 at 10 15 54" src="https://user-images.githubusercontent.com/36229155/153234152-2a237f9d-7a2f-4365-9679-151efd0d5360.png">

**Comment by fegbert** [comment]
> My personal preference would be to go with the shorter one and change it to `Unified Maker auctions`.

I agree on this. I think it the short option would look better in most cases 🙂

> [Block Analitica](https://maker.blockanalitica.com/)

Good suggestion! Since they have everything inside cards I would suggest to add another one for participation with the sentence `Visit the Unified Auctions UI to participate in active auctions` that contains a link to our page.

![image](https://user-images.githubusercontent.com/47861849/153856958-3560c630-43d4-4123-bd3c-816e700e94bc.png)

> [Makerburn](https://makerburn.com/#/)

I totally missed that link. That's definitely the best approach in my opinion!
