### ISSUE TITLE
Add `CurveLpTokenUniv3Callee` callee support

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#94]
### Goal
Support new SteCRV collateral

### Prerequisite
- [x] [`CurveLpTokenUniv3Callee` callee PR](https://github.com/makerdao/exchange-callees/pull/21/) is merged
   - done
- [x] Callee is deployed at least on the mainnet
   - done https://etherscan.io/address/0x71f2198849f3b1372ea90c079bd634928583f2d2
- [x] Related addresses (token address, clip address, etc) become part of the [chainlog](https://chainlog.makerdao.com/)
   - done [`CRVV1ETHSTETH `](https://etherscan.io/address/0x06325440d014e39736583c165c2963ba99faf14e)
- [ ] At least one auction of this collateral type is executed on the mainnet (or we have another way to test it)
   - see [`MCD_CLIP_CRVV1ETHSTETH_A` events](https://etherscan.io/address/0x1926862f899410bfc19fefb8a3c69c7aed22463a#events)

### Context

New collateral types are coming and we need to add support for them. ~~This time it can be a bit more difficult, since we don't have yet reference implementation of the auction-demo-keeper.~~ There is a PR that implements auction-demo-keeper support for this callee: https://github.com/makerdao/auction-demo-keeper/pull/60, main price fetching logic is within [this block](https://github.com/makerdao/auction-demo-keeper/pull/60/files#diff-f32c179af9ae614aaf3dc8421e3ffa3f602e4b424a8a88c7c20bbab935b64041R29-R49).

### Tasks
- [x] Investigate callee implementation to document needed conversions
- [x] Implement callee functions, according to the [Collateral onboarding](https://github.com/sidestream-tech/unified-auctions-ui/tree/main/core#collateral-onboarding) guide
- [x] Test

**Comment by LukSteib** [comment]
> [`CurveLpTokenUniv3Callee` callee PR](https://github.com/makerdao/exchange-callees/pull/21/) is merged

It is deployed: https://etherscan.io/address/0x71f2198849f3b1372ea90c079bd634928583f2d2

> Related addresses (token address, clip address, etc) become part of the [chainlog](https://chainlog.makerdao.com/)

They are now: Searching chainlog for `CRVV1ETHSTETH`

**Comment by valiafetisov** [comment]
What about testing strategy for the callee? Would there be at least one auction on the mainnet?

**Comment by LukSteib** [comment]
> What about testing strategy for the callee? Would there be at least one auction on the mainnet?

Current status:
* no vault for the collateral type in existence on `mainnet` for now (checked via https://maker.blockanalitica.com/vaults/)
* not possible to create a vault via UI for now (checked via https://oasis.app/)
* reached out to PE to ask about existence of test vault / auction (answer pending)

**Comment by LukSteib** [comment]
Update:
* it is now possible to create vaults with `CRVV1ETHSTETH` as collateral
* 5 vaults exist already
  * I assume chaoslabs should be able to simulate a liquidation for this collateral type based on their existing approach

**Comment by valiafetisov** [comment]
Update from the chaoslabs:
> We located 6 CRVV1ETHSTETH-A vaults but they all appear in inactive state (no debt) and hence are not elegible for liquidations (even when simulating price drops).
We will work on implementing the support for creating active vaults for a given collateral type but it is a larger engineering lift and will take more time on our side.
If you have active vault ids that you can share with us we will be able to create a simulation quickly (~couple of hours).

**Comment by LukSteib** [comment]
Not good news.
I don't get the differentiation between active and inactive vaults tbh. The vault analytics (see below) show that the vaults associated to `CRVV1ETHSTETH-A` do have debt. However they seem to be different due to a) the vault ID doesn't follow the usual pattern b) there seems to be no Dai borrowed for these vaults c) no user wallet is associated with these vaults

https://maker.blockanalitica.com/vaults/CRVV1ETHSTETH-A/

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/36229155/159504437-f05b685f-e27d-4340-a14b-b1bf0b73e233.png">

**Comment by valiafetisov** [comment]
> no Dai borrowed for these vaults

I am not sure I understand how there can be a debt if no DAI was withdrawn. But yeah, I think this what they're referencing to: since no DAI was withdrawn, changing oracle price wouldn't make them "kickable"
